// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package storageidl

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/zeefan1555/commonloop/internal/idl/commonidl"
	"strings"
)

const (
	// Durable Requirement storage contract.
	//
	// This file owns every Commonloop-defined structured JSON/JSONL document under
	// .commonloop. It defines file schemas only: no public CLI methods or RPC service.
	FLOW_STATE_SCHEMA_VERSION = 12

	EVENT_SCHEMA_VERSION = 12

	OUTPUT_REGISTRY_SCHEMA_VERSION = 3

	CARD_PROJECTION_SCHEMA_VERSION = 5

	CARD_BINDING_SCHEMA_VERSION = 2

	TRACE_CONFIG_SCHEMA_VERSION = 2

	CLI_EXECUTION_LOG_SCHEMA_VERSION = 2
)

type StepStatus int64

const (
	StepStatus_unspecified StepStatus = 0
	StepStatus_ready       StepStatus = 1
	StepStatus_in_progress StepStatus = 2
	StepStatus_fixing      StepStatus = 3
	StepStatus_blocked     StepStatus = 4
)

func (p StepStatus) String() string {
	switch p {
	case StepStatus_unspecified:
		return "unspecified"
	case StepStatus_ready:
		return "ready"
	case StepStatus_in_progress:
		return "in_progress"
	case StepStatus_fixing:
		return "fixing"
	case StepStatus_blocked:
		return "blocked"
	}
	return "<UNSET>"
}

func StepStatusFromString(s string) (StepStatus, error) {
	switch s {
	case "unspecified":
		return StepStatus_unspecified, nil
	case "ready":
		return StepStatus_ready, nil
	case "in_progress":
		return StepStatus_in_progress, nil
	case "fixing":
		return StepStatus_fixing, nil
	case "blocked":
		return StepStatus_blocked, nil
	}
	return StepStatus(0), fmt.Errorf("not a valid StepStatus string")
}

func StepStatusPtr(v StepStatus) *StepStatus { return &v }

func (p StepStatus) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *StepStatus) UnmarshalText(text []byte) error {
	q, err := StepStatusFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *StepStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = StepStatus(result.Int64)
	return
}

func (p *StepStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type EvidenceSource int64

const (
	EvidenceSource_unspecified EvidenceSource = 0
	EvidenceSource_human       EvidenceSource = 1
	EvidenceSource_system      EvidenceSource = 2
	EvidenceSource_ai          EvidenceSource = 3
	EvidenceSource_file        EvidenceSource = 4
	EvidenceSource_url         EvidenceSource = 5
)

func (p EvidenceSource) String() string {
	switch p {
	case EvidenceSource_unspecified:
		return "unspecified"
	case EvidenceSource_human:
		return "human"
	case EvidenceSource_system:
		return "system"
	case EvidenceSource_ai:
		return "ai"
	case EvidenceSource_file:
		return "file"
	case EvidenceSource_url:
		return "url"
	}
	return "<UNSET>"
}

func EvidenceSourceFromString(s string) (EvidenceSource, error) {
	switch s {
	case "unspecified":
		return EvidenceSource_unspecified, nil
	case "human":
		return EvidenceSource_human, nil
	case "system":
		return EvidenceSource_system, nil
	case "ai":
		return EvidenceSource_ai, nil
	case "file":
		return EvidenceSource_file, nil
	case "url":
		return EvidenceSource_url, nil
	}
	return EvidenceSource(0), fmt.Errorf("not a valid EvidenceSource string")
}

func EvidenceSourcePtr(v EvidenceSource) *EvidenceSource { return &v }

func (p EvidenceSource) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *EvidenceSource) UnmarshalText(text []byte) error {
	q, err := EvidenceSourceFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *EvidenceSource) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = EvidenceSource(result.Int64)
	return
}

func (p *EvidenceSource) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OutputType int64

const (
	OutputType_unspecified OutputType = 0
	OutputType_string      OutputType = 1
	OutputType_boolean     OutputType = 2
	OutputType_integer     OutputType = 3
	OutputType_path        OutputType = 4
	OutputType_url         OutputType = 5
	OutputType_url_list    OutputType = 6
	OutputType_enum_value  OutputType = 7
	OutputType_object      OutputType = 8
)

func (p OutputType) String() string {
	switch p {
	case OutputType_unspecified:
		return "unspecified"
	case OutputType_string:
		return "string"
	case OutputType_boolean:
		return "boolean"
	case OutputType_integer:
		return "integer"
	case OutputType_path:
		return "path"
	case OutputType_url:
		return "url"
	case OutputType_url_list:
		return "url_list"
	case OutputType_enum_value:
		return "enum_value"
	case OutputType_object:
		return "object"
	}
	return "<UNSET>"
}

func OutputTypeFromString(s string) (OutputType, error) {
	switch s {
	case "unspecified":
		return OutputType_unspecified, nil
	case "string":
		return OutputType_string, nil
	case "boolean":
		return OutputType_boolean, nil
	case "integer":
		return OutputType_integer, nil
	case "path":
		return OutputType_path, nil
	case "url":
		return OutputType_url, nil
	case "url_list":
		return OutputType_url_list, nil
	case "enum_value":
		return OutputType_enum_value, nil
	case "object":
		return OutputType_object, nil
	}
	return OutputType(0), fmt.Errorf("not a valid OutputType string")
}

func OutputTypePtr(v OutputType) *OutputType { return &v }

func (p OutputType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *OutputType) UnmarshalText(text []byte) error {
	q, err := OutputTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *OutputType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OutputType(result.Int64)
	return
}

func (p *OutputType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type RegistryProfile int64

const (
	RegistryProfile_unspecified RegistryProfile = 0
	RegistryProfile_production  RegistryProfile = 1
	RegistryProfile_test        RegistryProfile = 2
)

func (p RegistryProfile) String() string {
	switch p {
	case RegistryProfile_unspecified:
		return "unspecified"
	case RegistryProfile_production:
		return "production"
	case RegistryProfile_test:
		return "test"
	}
	return "<UNSET>"
}

func RegistryProfileFromString(s string) (RegistryProfile, error) {
	switch s {
	case "unspecified":
		return RegistryProfile_unspecified, nil
	case "production":
		return RegistryProfile_production, nil
	case "test":
		return RegistryProfile_test, nil
	}
	return RegistryProfile(0), fmt.Errorf("not a valid RegistryProfile string")
}

func RegistryProfilePtr(v RegistryProfile) *RegistryProfile { return &v }

func (p RegistryProfile) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *RegistryProfile) UnmarshalText(text []byte) error {
	q, err := RegistryProfileFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *RegistryProfile) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = RegistryProfile(result.Int64)
	return
}

func (p *RegistryProfile) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type EventKind int64

const (
	EventKind_unspecified          EventKind = 0
	EventKind_flow_initialized     EventKind = 1
	EventKind_flow_progressed      EventKind = 2
	EventKind_flow_result          EventKind = 3
	EventKind_trace_document_bound EventKind = 4
	EventKind_trace_sync_started   EventKind = 5
	EventKind_trace_synced         EventKind = 6
)

func (p EventKind) String() string {
	switch p {
	case EventKind_unspecified:
		return "unspecified"
	case EventKind_flow_initialized:
		return "flow_initialized"
	case EventKind_flow_progressed:
		return "flow_progressed"
	case EventKind_flow_result:
		return "flow_result"
	case EventKind_trace_document_bound:
		return "trace_document_bound"
	case EventKind_trace_sync_started:
		return "trace_sync_started"
	case EventKind_trace_synced:
		return "trace_synced"
	}
	return "<UNSET>"
}

func EventKindFromString(s string) (EventKind, error) {
	switch s {
	case "unspecified":
		return EventKind_unspecified, nil
	case "flow_initialized":
		return EventKind_flow_initialized, nil
	case "flow_progressed":
		return EventKind_flow_progressed, nil
	case "flow_result":
		return EventKind_flow_result, nil
	case "trace_document_bound":
		return EventKind_trace_document_bound, nil
	case "trace_sync_started":
		return EventKind_trace_sync_started, nil
	case "trace_synced":
		return EventKind_trace_synced, nil
	}
	return EventKind(0), fmt.Errorf("not a valid EventKind string")
}

func EventKindPtr(v EventKind) *EventKind { return &v }

func (p EventKind) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *EventKind) UnmarshalText(text []byte) error {
	q, err := EventKindFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *EventKind) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = EventKind(result.Int64)
	return
}

func (p *EventKind) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ResultEffect int64

const (
	ResultEffect_unspecified ResultEffect = 0
	ResultEffect_advanced    ResultEffect = 1
	ResultEffect_looped      ResultEffect = 2
	ResultEffect_completed   ResultEffect = 3
)

func (p ResultEffect) String() string {
	switch p {
	case ResultEffect_unspecified:
		return "unspecified"
	case ResultEffect_advanced:
		return "advanced"
	case ResultEffect_looped:
		return "looped"
	case ResultEffect_completed:
		return "completed"
	}
	return "<UNSET>"
}

func ResultEffectFromString(s string) (ResultEffect, error) {
	switch s {
	case "unspecified":
		return ResultEffect_unspecified, nil
	case "advanced":
		return ResultEffect_advanced, nil
	case "looped":
		return ResultEffect_looped, nil
	case "completed":
		return ResultEffect_completed, nil
	}
	return ResultEffect(0), fmt.Errorf("not a valid ResultEffect string")
}

func ResultEffectPtr(v ResultEffect) *ResultEffect { return &v }

func (p ResultEffect) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *ResultEffect) UnmarshalText(text []byte) error {
	q, err := ResultEffectFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *ResultEffect) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ResultEffect(result.Int64)
	return
}

func (p *ResultEffect) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TransitionDirection int64

const (
	TransitionDirection_unspecified TransitionDirection = 0
	TransitionDirection_flow        TransitionDirection = 1
	TransitionDirection_loop        TransitionDirection = 2
)

func (p TransitionDirection) String() string {
	switch p {
	case TransitionDirection_unspecified:
		return "unspecified"
	case TransitionDirection_flow:
		return "flow"
	case TransitionDirection_loop:
		return "loop"
	}
	return "<UNSET>"
}

func TransitionDirectionFromString(s string) (TransitionDirection, error) {
	switch s {
	case "unspecified":
		return TransitionDirection_unspecified, nil
	case "flow":
		return TransitionDirection_flow, nil
	case "loop":
		return TransitionDirection_loop, nil
	}
	return TransitionDirection(0), fmt.Errorf("not a valid TransitionDirection string")
}

func TransitionDirectionPtr(v TransitionDirection) *TransitionDirection { return &v }

func (p TransitionDirection) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TransitionDirection) UnmarshalText(text []byte) error {
	q, err := TransitionDirectionFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TransitionDirection) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TransitionDirection(result.Int64)
	return
}

func (p *TransitionDirection) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TraceSyncOutcome int64

const (
	TraceSyncOutcome_unspecified TraceSyncOutcome = 0
	TraceSyncOutcome_succeeded   TraceSyncOutcome = 1
	TraceSyncOutcome_partial     TraceSyncOutcome = 2
	TraceSyncOutcome_skipped     TraceSyncOutcome = 3
)

func (p TraceSyncOutcome) String() string {
	switch p {
	case TraceSyncOutcome_unspecified:
		return "unspecified"
	case TraceSyncOutcome_succeeded:
		return "succeeded"
	case TraceSyncOutcome_partial:
		return "partial"
	case TraceSyncOutcome_skipped:
		return "skipped"
	}
	return "<UNSET>"
}

func TraceSyncOutcomeFromString(s string) (TraceSyncOutcome, error) {
	switch s {
	case "unspecified":
		return TraceSyncOutcome_unspecified, nil
	case "succeeded":
		return TraceSyncOutcome_succeeded, nil
	case "partial":
		return TraceSyncOutcome_partial, nil
	case "skipped":
		return TraceSyncOutcome_skipped, nil
	}
	return TraceSyncOutcome(0), fmt.Errorf("not a valid TraceSyncOutcome string")
}

func TraceSyncOutcomePtr(v TraceSyncOutcome) *TraceSyncOutcome { return &v }

func (p TraceSyncOutcome) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TraceSyncOutcome) UnmarshalText(text []byte) error {
	q, err := TraceSyncOutcomeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TraceSyncOutcome) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TraceSyncOutcome(result.Int64)
	return
}

func (p *TraceSyncOutcome) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TraceTarget int64

const (
	TraceTarget_unspecified      TraceTarget = 0
	TraceTarget_trace_document   TraceTarget = 1
	TraceTarget_registry         TraceTarget = 2
	TraceTarget_cli_log_document TraceTarget = 3
)

func (p TraceTarget) String() string {
	switch p {
	case TraceTarget_unspecified:
		return "unspecified"
	case TraceTarget_trace_document:
		return "trace_document"
	case TraceTarget_registry:
		return "registry"
	case TraceTarget_cli_log_document:
		return "cli_log_document"
	}
	return "<UNSET>"
}

func TraceTargetFromString(s string) (TraceTarget, error) {
	switch s {
	case "unspecified":
		return TraceTarget_unspecified, nil
	case "trace_document":
		return TraceTarget_trace_document, nil
	case "registry":
		return TraceTarget_registry, nil
	case "cli_log_document":
		return TraceTarget_cli_log_document, nil
	}
	return TraceTarget(0), fmt.Errorf("not a valid TraceTarget string")
}

func TraceTargetPtr(v TraceTarget) *TraceTarget { return &v }

func (p TraceTarget) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TraceTarget) UnmarshalText(text []byte) error {
	q, err := TraceTargetFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TraceTarget) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TraceTarget(result.Int64)
	return
}

func (p *TraceTarget) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TraceTargetStatus int64

const (
	TraceTargetStatus_unspecified TraceTargetStatus = 0
	TraceTargetStatus_succeeded   TraceTargetStatus = 1
	TraceTargetStatus_failed      TraceTargetStatus = 2
	TraceTargetStatus_skipped     TraceTargetStatus = 3
)

func (p TraceTargetStatus) String() string {
	switch p {
	case TraceTargetStatus_unspecified:
		return "unspecified"
	case TraceTargetStatus_succeeded:
		return "succeeded"
	case TraceTargetStatus_failed:
		return "failed"
	case TraceTargetStatus_skipped:
		return "skipped"
	}
	return "<UNSET>"
}

func TraceTargetStatusFromString(s string) (TraceTargetStatus, error) {
	switch s {
	case "unspecified":
		return TraceTargetStatus_unspecified, nil
	case "succeeded":
		return TraceTargetStatus_succeeded, nil
	case "failed":
		return TraceTargetStatus_failed, nil
	case "skipped":
		return TraceTargetStatus_skipped, nil
	}
	return TraceTargetStatus(0), fmt.Errorf("not a valid TraceTargetStatus string")
}

func TraceTargetStatusPtr(v TraceTargetStatus) *TraceTargetStatus { return &v }

func (p TraceTargetStatus) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TraceTargetStatus) UnmarshalText(text []byte) error {
	q, err := TraceTargetStatusFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TraceTargetStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TraceTargetStatus(result.Int64)
	return
}

func (p *TraceTargetStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TraceTargetErrorCode int64

const (
	TraceTargetErrorCode_unspecified            TraceTargetErrorCode = 0
	TraceTargetErrorCode_trace_update_failed    TraceTargetErrorCode = 1
	TraceTargetErrorCode_registry_update_failed TraceTargetErrorCode = 2
	TraceTargetErrorCode_network_failed         TraceTargetErrorCode = 3
	TraceTargetErrorCode_upstream_auth_failed   TraceTargetErrorCode = 4
)

func (p TraceTargetErrorCode) String() string {
	switch p {
	case TraceTargetErrorCode_unspecified:
		return "unspecified"
	case TraceTargetErrorCode_trace_update_failed:
		return "trace_update_failed"
	case TraceTargetErrorCode_registry_update_failed:
		return "registry_update_failed"
	case TraceTargetErrorCode_network_failed:
		return "network_failed"
	case TraceTargetErrorCode_upstream_auth_failed:
		return "upstream_auth_failed"
	}
	return "<UNSET>"
}

func TraceTargetErrorCodeFromString(s string) (TraceTargetErrorCode, error) {
	switch s {
	case "unspecified":
		return TraceTargetErrorCode_unspecified, nil
	case "trace_update_failed":
		return TraceTargetErrorCode_trace_update_failed, nil
	case "registry_update_failed":
		return TraceTargetErrorCode_registry_update_failed, nil
	case "network_failed":
		return TraceTargetErrorCode_network_failed, nil
	case "upstream_auth_failed":
		return TraceTargetErrorCode_upstream_auth_failed, nil
	}
	return TraceTargetErrorCode(0), fmt.Errorf("not a valid TraceTargetErrorCode string")
}

func TraceTargetErrorCodePtr(v TraceTargetErrorCode) *TraceTargetErrorCode { return &v }

func (p TraceTargetErrorCode) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TraceTargetErrorCode) UnmarshalText(text []byte) error {
	q, err := TraceTargetErrorCodeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TraceTargetErrorCode) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TraceTargetErrorCode(result.Int64)
	return
}

func (p *TraceTargetErrorCode) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type CLIExecutionLogEntry struct {
	SchemaVersion  int32    `thrift:"schema_version,1,required" json:"schema_version"`
	InvocationId   string   `thrift:"invocation_id,2,required" json:"invocation_id"`
	StartedAt      string   `thrift:"started_at,3,required" json:"started_at"`
	DurationMs     int64    `thrift:"duration_ms,4,required" json:"duration_ms"`
	CommandId      string   `thrift:"command_id,5,required" json:"command_id"`
	CliVersion     string   `thrift:"cli_version,6,required" json:"cli_version"`
	ReleaseVersion string   `thrift:"release_version,7,required" json:"release_version"`
	CommitSha      string   `thrift:"commit_sha,8,required" json:"commit_sha"`
	DryRun         bool     `thrift:"dry_run,9,required" json:"dry_run"`
	ExitCode       int32    `thrift:"exit_code,10,required" json:"exit_code"`
	ErrorCode      *string  `thrift:"error_code,11,optional" json:"error_code,omitempty"`
	Arguments      []string `thrift:"arguments,12,required,list<string>" json:"arguments"`
	Stdin          string   `thrift:"stdin,13,required" json:"stdin"`
	Stdout         string   `thrift:"stdout,14,required" json:"stdout"`
	Stderr         string   `thrift:"stderr,15,required" json:"stderr"`
}

func NewCLIExecutionLogEntry() *CLIExecutionLogEntry {
	return &CLIExecutionLogEntry{}
}

func (p *CLIExecutionLogEntry) InitDefault() {
}

func (p *CLIExecutionLogEntry) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

func (p *CLIExecutionLogEntry) GetInvocationId() (v string) {
	return p.InvocationId
}

func (p *CLIExecutionLogEntry) GetStartedAt() (v string) {
	return p.StartedAt
}

func (p *CLIExecutionLogEntry) GetDurationMs() (v int64) {
	return p.DurationMs
}

func (p *CLIExecutionLogEntry) GetCommandId() (v string) {
	return p.CommandId
}

func (p *CLIExecutionLogEntry) GetCliVersion() (v string) {
	return p.CliVersion
}

func (p *CLIExecutionLogEntry) GetReleaseVersion() (v string) {
	return p.ReleaseVersion
}

func (p *CLIExecutionLogEntry) GetCommitSha() (v string) {
	return p.CommitSha
}

func (p *CLIExecutionLogEntry) GetDryRun() (v bool) {
	return p.DryRun
}

func (p *CLIExecutionLogEntry) GetExitCode() (v int32) {
	return p.ExitCode
}

var CLIExecutionLogEntry_ErrorCode_DEFAULT string

func (p *CLIExecutionLogEntry) GetErrorCode() (v string) {
	if !p.IsSetErrorCode() {
		return CLIExecutionLogEntry_ErrorCode_DEFAULT
	}
	return *p.ErrorCode
}

func (p *CLIExecutionLogEntry) GetArguments() (v []string) {
	return p.Arguments
}

func (p *CLIExecutionLogEntry) GetStdin() (v string) {
	return p.Stdin
}

func (p *CLIExecutionLogEntry) GetStdout() (v string) {
	return p.Stdout
}

func (p *CLIExecutionLogEntry) GetStderr() (v string) {
	return p.Stderr
}

func (p *CLIExecutionLogEntry) IsSetErrorCode() bool {
	return p.ErrorCode != nil
}

func (p *CLIExecutionLogEntry) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CLIExecutionLogEntry(%+v)", *p)
}

func (p *CLIExecutionLogEntry) DeepEqual(ano *CLIExecutionLogEntry) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.InvocationId) {
		return false
	}
	if !p.Field3DeepEqual(ano.StartedAt) {
		return false
	}
	if !p.Field4DeepEqual(ano.DurationMs) {
		return false
	}
	if !p.Field5DeepEqual(ano.CommandId) {
		return false
	}
	if !p.Field6DeepEqual(ano.CliVersion) {
		return false
	}
	if !p.Field7DeepEqual(ano.ReleaseVersion) {
		return false
	}
	if !p.Field8DeepEqual(ano.CommitSha) {
		return false
	}
	if !p.Field9DeepEqual(ano.DryRun) {
		return false
	}
	if !p.Field10DeepEqual(ano.ExitCode) {
		return false
	}
	if !p.Field11DeepEqual(ano.ErrorCode) {
		return false
	}
	if !p.Field12DeepEqual(ano.Arguments) {
		return false
	}
	if !p.Field13DeepEqual(ano.Stdin) {
		return false
	}
	if !p.Field14DeepEqual(ano.Stdout) {
		return false
	}
	if !p.Field15DeepEqual(ano.Stderr) {
		return false
	}
	return true
}

func (p *CLIExecutionLogEntry) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field2DeepEqual(src string) bool {

	if strings.Compare(p.InvocationId, src) != 0 {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field3DeepEqual(src string) bool {

	if strings.Compare(p.StartedAt, src) != 0 {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field4DeepEqual(src int64) bool {

	if p.DurationMs != src {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field5DeepEqual(src string) bool {

	if strings.Compare(p.CommandId, src) != 0 {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field6DeepEqual(src string) bool {

	if strings.Compare(p.CliVersion, src) != 0 {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field7DeepEqual(src string) bool {

	if strings.Compare(p.ReleaseVersion, src) != 0 {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field8DeepEqual(src string) bool {

	if strings.Compare(p.CommitSha, src) != 0 {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field9DeepEqual(src bool) bool {

	if p.DryRun != src {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field10DeepEqual(src int32) bool {

	if p.ExitCode != src {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field11DeepEqual(src *string) bool {

	if p.ErrorCode == src {
		return true
	} else if p.ErrorCode == nil || src == nil {
		return false
	}
	if strings.Compare(*p.ErrorCode, *src) != 0 {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field12DeepEqual(src []string) bool {

	if len(p.Arguments) != len(src) {
		return false
	}
	for i, v := range p.Arguments {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *CLIExecutionLogEntry) Field13DeepEqual(src string) bool {

	if strings.Compare(p.Stdin, src) != 0 {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field14DeepEqual(src string) bool {

	if strings.Compare(p.Stdout, src) != 0 {
		return false
	}
	return true
}
func (p *CLIExecutionLogEntry) Field15DeepEqual(src string) bool {

	if strings.Compare(p.Stderr, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_CLIExecutionLogEntry = map[int16]string{
	1:  "schema_version",
	2:  "invocation_id",
	3:  "started_at",
	4:  "duration_ms",
	5:  "command_id",
	6:  "cli_version",
	7:  "release_version",
	8:  "commit_sha",
	9:  "dry_run",
	10: "exit_code",
	11: "error_code",
	12: "arguments",
	13: "stdin",
	14: "stdout",
	15: "stderr",
}

type Requirement struct {
	Title     string  `thrift:"title,1,required" json:"title"`
	SourceUrl *string `thrift:"source_url,2,optional" json:"source_url,omitempty"`
}

func NewRequirement() *Requirement {
	return &Requirement{}
}

func (p *Requirement) InitDefault() {
}

func (p *Requirement) GetTitle() (v string) {
	return p.Title
}

var Requirement_SourceUrl_DEFAULT string

func (p *Requirement) GetSourceUrl() (v string) {
	if !p.IsSetSourceUrl() {
		return Requirement_SourceUrl_DEFAULT
	}
	return *p.SourceUrl
}

func (p *Requirement) IsSetSourceUrl() bool {
	return p.SourceUrl != nil
}

func (p *Requirement) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Requirement(%+v)", *p)
}

func (p *Requirement) DeepEqual(ano *Requirement) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Title) {
		return false
	}
	if !p.Field2DeepEqual(ano.SourceUrl) {
		return false
	}
	return true
}

func (p *Requirement) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Title, src) != 0 {
		return false
	}
	return true
}
func (p *Requirement) Field2DeepEqual(src *string) bool {

	if p.SourceUrl == src {
		return true
	} else if p.SourceUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.SourceUrl, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_Requirement = map[int16]string{
	1: "title",
	2: "source_url",
}

type Release struct {
	Version  string                 `thrift:"version,1,required" json:"version"`
	Workflow *commonidl.WorkflowRef `thrift:"workflow,2,required" json:"workflow"`
}

func NewRelease() *Release {
	return &Release{}
}

func (p *Release) InitDefault() {
}

func (p *Release) GetVersion() (v string) {
	return p.Version
}

var Release_Workflow_DEFAULT *commonidl.WorkflowRef

func (p *Release) GetWorkflow() (v *commonidl.WorkflowRef) {
	if !p.IsSetWorkflow() {
		return Release_Workflow_DEFAULT
	}
	return p.Workflow
}

func (p *Release) IsSetWorkflow() bool {
	return p.Workflow != nil
}

func (p *Release) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Release(%+v)", *p)
}

func (p *Release) DeepEqual(ano *Release) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Version) {
		return false
	}
	if !p.Field2DeepEqual(ano.Workflow) {
		return false
	}
	return true
}

func (p *Release) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Version, src) != 0 {
		return false
	}
	return true
}
func (p *Release) Field2DeepEqual(src *commonidl.WorkflowRef) bool {

	if !p.Workflow.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_Release = map[int16]string{
	1: "version",
	2: "workflow",
}

type Evidence struct {
	Source  EvidenceSource `thrift:"source,1,required,EvidenceSource" json:"source"`
	Content string         `thrift:"content,2,required" json:"content"`
	Ref     *string        `thrift:"ref,3,optional" json:"ref,omitempty"`
}

func NewEvidence() *Evidence {
	return &Evidence{}
}

func (p *Evidence) InitDefault() {
}

func (p *Evidence) GetSource() (v EvidenceSource) {
	return p.Source
}

func (p *Evidence) GetContent() (v string) {
	return p.Content
}

var Evidence_Ref_DEFAULT string

func (p *Evidence) GetRef() (v string) {
	if !p.IsSetRef() {
		return Evidence_Ref_DEFAULT
	}
	return *p.Ref
}

func (p *Evidence) IsSetRef() bool {
	return p.Ref != nil
}

func (p *Evidence) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Evidence(%+v)", *p)
}

func (p *Evidence) DeepEqual(ano *Evidence) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Source) {
		return false
	}
	if !p.Field2DeepEqual(ano.Content) {
		return false
	}
	if !p.Field3DeepEqual(ano.Ref) {
		return false
	}
	return true
}

func (p *Evidence) Field1DeepEqual(src EvidenceSource) bool {

	if p.Source != src {
		return false
	}
	return true
}
func (p *Evidence) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Content, src) != 0 {
		return false
	}
	return true
}
func (p *Evidence) Field3DeepEqual(src *string) bool {

	if p.Ref == src {
		return true
	} else if p.Ref == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Ref, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_Evidence = map[int16]string{
	1: "source",
	2: "content",
	3: "ref",
}

type OutputValue struct {
	Type  OutputType           `thrift:"type,1,required,OutputType" json:"type"`
	Value *commonidl.JsonValue `thrift:"value,2,required" json:"value"`
}

func NewOutputValue() *OutputValue {
	return &OutputValue{}
}

func (p *OutputValue) InitDefault() {
}

func (p *OutputValue) GetType() (v OutputType) {
	return p.Type
}

var OutputValue_Value_DEFAULT *commonidl.JsonValue

func (p *OutputValue) GetValue() (v *commonidl.JsonValue) {
	if !p.IsSetValue() {
		return OutputValue_Value_DEFAULT
	}
	return p.Value
}

func (p *OutputValue) IsSetValue() bool {
	return p.Value != nil
}

func (p *OutputValue) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OutputValue(%+v)", *p)
}

func (p *OutputValue) DeepEqual(ano *OutputValue) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Type) {
		return false
	}
	if !p.Field2DeepEqual(ano.Value) {
		return false
	}
	return true
}

func (p *OutputValue) Field1DeepEqual(src OutputType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *OutputValue) Field2DeepEqual(src *commonidl.JsonValue) bool {

	if !p.Value.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_OutputValue = map[int16]string{
	1: "type",
	2: "value",
}

type ConditionResult struct {
	ConditionId string       `thrift:"condition_id,1,required" json:"condition_id"`
	Output      *OutputValue `thrift:"output,2,required" json:"output"`
}

func NewConditionResult() *ConditionResult {
	return &ConditionResult{}
}

func (p *ConditionResult) InitDefault() {
}

func (p *ConditionResult) GetConditionId() (v string) {
	return p.ConditionId
}

var ConditionResult_Output_DEFAULT *OutputValue

func (p *ConditionResult) GetOutput() (v *OutputValue) {
	if !p.IsSetOutput() {
		return ConditionResult_Output_DEFAULT
	}
	return p.Output
}

func (p *ConditionResult) IsSetOutput() bool {
	return p.Output != nil
}

func (p *ConditionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConditionResult(%+v)", *p)
}

func (p *ConditionResult) DeepEqual(ano *ConditionResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.ConditionId) {
		return false
	}
	if !p.Field2DeepEqual(ano.Output) {
		return false
	}
	return true
}

func (p *ConditionResult) Field1DeepEqual(src string) bool {

	if strings.Compare(p.ConditionId, src) != 0 {
		return false
	}
	return true
}
func (p *ConditionResult) Field2DeepEqual(src *OutputValue) bool {

	if !p.Output.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_ConditionResult = map[int16]string{
	1: "condition_id",
	2: "output",
}

type RegisteredOutput struct {
	Type           OutputType           `thrift:"type,1,required,OutputType" json:"type"`
	Value          *commonidl.JsonValue `thrift:"value,2,required" json:"value"`
	ProducerStepId string               `thrift:"producer_step_id,3,required" json:"producer_step_id"`
}

func NewRegisteredOutput() *RegisteredOutput {
	return &RegisteredOutput{}
}

func (p *RegisteredOutput) InitDefault() {
}

func (p *RegisteredOutput) GetType() (v OutputType) {
	return p.Type
}

var RegisteredOutput_Value_DEFAULT *commonidl.JsonValue

func (p *RegisteredOutput) GetValue() (v *commonidl.JsonValue) {
	if !p.IsSetValue() {
		return RegisteredOutput_Value_DEFAULT
	}
	return p.Value
}

func (p *RegisteredOutput) GetProducerStepId() (v string) {
	return p.ProducerStepId
}

func (p *RegisteredOutput) IsSetValue() bool {
	return p.Value != nil
}

func (p *RegisteredOutput) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisteredOutput(%+v)", *p)
}

func (p *RegisteredOutput) DeepEqual(ano *RegisteredOutput) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Type) {
		return false
	}
	if !p.Field2DeepEqual(ano.Value) {
		return false
	}
	if !p.Field3DeepEqual(ano.ProducerStepId) {
		return false
	}
	return true
}

func (p *RegisteredOutput) Field1DeepEqual(src OutputType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *RegisteredOutput) Field2DeepEqual(src *commonidl.JsonValue) bool {

	if !p.Value.DeepEqual(src) {
		return false
	}
	return true
}
func (p *RegisteredOutput) Field3DeepEqual(src string) bool {

	if strings.Compare(p.ProducerStepId, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_RegisteredOutput = map[int16]string{
	1: "type",
	2: "value",
	3: "producer_step_id",
}

type TraceBinding struct {
	DocumentUrl       string          `thrift:"document_url,1,required" json:"document_url"`
	Registry          RegistryProfile `thrift:"registry,2,required,RegistryProfile" json:"registry"`
	CliLogDocumentUrl *string         `thrift:"cli_log_document_url,3,optional" json:"cli_log_document_url,omitempty"`
}

func NewTraceBinding() *TraceBinding {
	return &TraceBinding{}
}

func (p *TraceBinding) InitDefault() {
}

func (p *TraceBinding) GetDocumentUrl() (v string) {
	return p.DocumentUrl
}

func (p *TraceBinding) GetRegistry() (v RegistryProfile) {
	return p.Registry
}

var TraceBinding_CliLogDocumentUrl_DEFAULT string

func (p *TraceBinding) GetCliLogDocumentUrl() (v string) {
	if !p.IsSetCliLogDocumentUrl() {
		return TraceBinding_CliLogDocumentUrl_DEFAULT
	}
	return *p.CliLogDocumentUrl
}

func (p *TraceBinding) IsSetCliLogDocumentUrl() bool {
	return p.CliLogDocumentUrl != nil
}

func (p *TraceBinding) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceBinding(%+v)", *p)
}

func (p *TraceBinding) DeepEqual(ano *TraceBinding) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.DocumentUrl) {
		return false
	}
	if !p.Field2DeepEqual(ano.Registry) {
		return false
	}
	if !p.Field3DeepEqual(ano.CliLogDocumentUrl) {
		return false
	}
	return true
}

func (p *TraceBinding) Field1DeepEqual(src string) bool {

	if strings.Compare(p.DocumentUrl, src) != 0 {
		return false
	}
	return true
}
func (p *TraceBinding) Field2DeepEqual(src RegistryProfile) bool {

	if p.Registry != src {
		return false
	}
	return true
}
func (p *TraceBinding) Field3DeepEqual(src *string) bool {

	if p.CliLogDocumentUrl == src {
		return true
	} else if p.CliLogDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CliLogDocumentUrl, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_TraceBinding = map[int16]string{
	1: "document_url",
	2: "registry",
	3: "cli_log_document_url",
}

type Integrations struct {
	Trace *TraceBinding `thrift:"trace,1,optional" json:"trace,omitempty"`
}

func NewIntegrations() *Integrations {
	return &Integrations{}
}

func (p *Integrations) InitDefault() {
}

var Integrations_Trace_DEFAULT *TraceBinding

func (p *Integrations) GetTrace() (v *TraceBinding) {
	if !p.IsSetTrace() {
		return Integrations_Trace_DEFAULT
	}
	return p.Trace
}

func (p *Integrations) IsSetTrace() bool {
	return p.Trace != nil
}

func (p *Integrations) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Integrations(%+v)", *p)
}

func (p *Integrations) DeepEqual(ano *Integrations) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Trace) {
		return false
	}
	return true
}

func (p *Integrations) Field1DeepEqual(src *TraceBinding) bool {

	if !p.Trace.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_Integrations = map[int16]string{
	1: "trace",
}

type FlowState struct {
	SchemaVersion      int32         `thrift:"schema_version,1,required" json:"schema_version"`
	Requirement        *Requirement  `thrift:"requirement,2,required" json:"requirement"`
	Release            *Release      `thrift:"release,3,required" json:"release"`
	CurrentStepId      *string       `thrift:"current_step_id,4,optional" json:"current_step_id,omitempty"`
	CurrentStepStatus  *StepStatus   `thrift:"current_step_status,5,optional,StepStatus" json:"current_step_status,omitempty"`
	CurrentStepSummary *string       `thrift:"current_step_summary,6,optional" json:"current_step_summary,omitempty"`
	CurrentEvidence    []*Evidence   `thrift:"current_evidence,7,optional,list<Evidence>" json:"current_evidence,omitempty"`
	Integrations       *Integrations `thrift:"integrations,8,required" json:"integrations"`
	LastEventId        string        `thrift:"last_event_id,9,required" json:"last_event_id"`
	CreatedAt          string        `thrift:"created_at,10,required" json:"created_at"`
	UpdatedAt          string        `thrift:"updated_at,11,required" json:"updated_at"`
}

func NewFlowState() *FlowState {
	return &FlowState{}
}

func (p *FlowState) InitDefault() {
}

func (p *FlowState) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

var FlowState_Requirement_DEFAULT *Requirement

func (p *FlowState) GetRequirement() (v *Requirement) {
	if !p.IsSetRequirement() {
		return FlowState_Requirement_DEFAULT
	}
	return p.Requirement
}

var FlowState_Release_DEFAULT *Release

func (p *FlowState) GetRelease() (v *Release) {
	if !p.IsSetRelease() {
		return FlowState_Release_DEFAULT
	}
	return p.Release
}

var FlowState_CurrentStepId_DEFAULT string

func (p *FlowState) GetCurrentStepId() (v string) {
	if !p.IsSetCurrentStepId() {
		return FlowState_CurrentStepId_DEFAULT
	}
	return *p.CurrentStepId
}

var FlowState_CurrentStepStatus_DEFAULT StepStatus

func (p *FlowState) GetCurrentStepStatus() (v StepStatus) {
	if !p.IsSetCurrentStepStatus() {
		return FlowState_CurrentStepStatus_DEFAULT
	}
	return *p.CurrentStepStatus
}

var FlowState_CurrentStepSummary_DEFAULT string

func (p *FlowState) GetCurrentStepSummary() (v string) {
	if !p.IsSetCurrentStepSummary() {
		return FlowState_CurrentStepSummary_DEFAULT
	}
	return *p.CurrentStepSummary
}

var FlowState_CurrentEvidence_DEFAULT []*Evidence

func (p *FlowState) GetCurrentEvidence() (v []*Evidence) {
	if !p.IsSetCurrentEvidence() {
		return FlowState_CurrentEvidence_DEFAULT
	}
	return p.CurrentEvidence
}

var FlowState_Integrations_DEFAULT *Integrations

func (p *FlowState) GetIntegrations() (v *Integrations) {
	if !p.IsSetIntegrations() {
		return FlowState_Integrations_DEFAULT
	}
	return p.Integrations
}

func (p *FlowState) GetLastEventId() (v string) {
	return p.LastEventId
}

func (p *FlowState) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *FlowState) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

func (p *FlowState) IsSetRequirement() bool {
	return p.Requirement != nil
}

func (p *FlowState) IsSetRelease() bool {
	return p.Release != nil
}

func (p *FlowState) IsSetCurrentStepId() bool {
	return p.CurrentStepId != nil
}

func (p *FlowState) IsSetCurrentStepStatus() bool {
	return p.CurrentStepStatus != nil
}

func (p *FlowState) IsSetCurrentStepSummary() bool {
	return p.CurrentStepSummary != nil
}

func (p *FlowState) IsSetCurrentEvidence() bool {
	return p.CurrentEvidence != nil
}

func (p *FlowState) IsSetIntegrations() bool {
	return p.Integrations != nil
}

func (p *FlowState) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowState(%+v)", *p)
}

func (p *FlowState) DeepEqual(ano *FlowState) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.Requirement) {
		return false
	}
	if !p.Field3DeepEqual(ano.Release) {
		return false
	}
	if !p.Field4DeepEqual(ano.CurrentStepId) {
		return false
	}
	if !p.Field5DeepEqual(ano.CurrentStepStatus) {
		return false
	}
	if !p.Field6DeepEqual(ano.CurrentStepSummary) {
		return false
	}
	if !p.Field7DeepEqual(ano.CurrentEvidence) {
		return false
	}
	if !p.Field8DeepEqual(ano.Integrations) {
		return false
	}
	if !p.Field9DeepEqual(ano.LastEventId) {
		return false
	}
	if !p.Field10DeepEqual(ano.CreatedAt) {
		return false
	}
	if !p.Field11DeepEqual(ano.UpdatedAt) {
		return false
	}
	return true
}

func (p *FlowState) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *FlowState) Field2DeepEqual(src *Requirement) bool {

	if !p.Requirement.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowState) Field3DeepEqual(src *Release) bool {

	if !p.Release.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowState) Field4DeepEqual(src *string) bool {

	if p.CurrentStepId == src {
		return true
	} else if p.CurrentStepId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CurrentStepId, *src) != 0 {
		return false
	}
	return true
}
func (p *FlowState) Field5DeepEqual(src *StepStatus) bool {

	if p.CurrentStepStatus == src {
		return true
	} else if p.CurrentStepStatus == nil || src == nil {
		return false
	}
	if *p.CurrentStepStatus != *src {
		return false
	}
	return true
}
func (p *FlowState) Field6DeepEqual(src *string) bool {

	if p.CurrentStepSummary == src {
		return true
	} else if p.CurrentStepSummary == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CurrentStepSummary, *src) != 0 {
		return false
	}
	return true
}
func (p *FlowState) Field7DeepEqual(src []*Evidence) bool {

	if len(p.CurrentEvidence) != len(src) {
		return false
	}
	for i, v := range p.CurrentEvidence {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FlowState) Field8DeepEqual(src *Integrations) bool {

	if !p.Integrations.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowState) Field9DeepEqual(src string) bool {

	if strings.Compare(p.LastEventId, src) != 0 {
		return false
	}
	return true
}
func (p *FlowState) Field10DeepEqual(src string) bool {

	if strings.Compare(p.CreatedAt, src) != 0 {
		return false
	}
	return true
}
func (p *FlowState) Field11DeepEqual(src string) bool {

	if strings.Compare(p.UpdatedAt, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_FlowState = map[int16]string{
	1:  "schema_version",
	2:  "requirement",
	3:  "release",
	4:  "current_step_id",
	5:  "current_step_status",
	6:  "current_step_summary",
	7:  "current_evidence",
	8:  "integrations",
	9:  "last_event_id",
	10: "created_at",
	11: "updated_at",
}

type OutputRegistry struct {
	SchemaVersion int32                        `thrift:"schema_version,1,required" json:"schema_version"`
	Workflow      *commonidl.WorkflowRef       `thrift:"workflow,2,required" json:"workflow"`
	Outputs       map[string]*RegisteredOutput `thrift:"outputs,3,required" json:"outputs"`
}

func NewOutputRegistry() *OutputRegistry {
	return &OutputRegistry{}
}

func (p *OutputRegistry) InitDefault() {
}

func (p *OutputRegistry) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

var OutputRegistry_Workflow_DEFAULT *commonidl.WorkflowRef

func (p *OutputRegistry) GetWorkflow() (v *commonidl.WorkflowRef) {
	if !p.IsSetWorkflow() {
		return OutputRegistry_Workflow_DEFAULT
	}
	return p.Workflow
}

func (p *OutputRegistry) GetOutputs() (v map[string]*RegisteredOutput) {
	return p.Outputs
}

func (p *OutputRegistry) IsSetWorkflow() bool {
	return p.Workflow != nil
}

func (p *OutputRegistry) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OutputRegistry(%+v)", *p)
}

func (p *OutputRegistry) DeepEqual(ano *OutputRegistry) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.Workflow) {
		return false
	}
	if !p.Field3DeepEqual(ano.Outputs) {
		return false
	}
	return true
}

func (p *OutputRegistry) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *OutputRegistry) Field2DeepEqual(src *commonidl.WorkflowRef) bool {

	if !p.Workflow.DeepEqual(src) {
		return false
	}
	return true
}
func (p *OutputRegistry) Field3DeepEqual(src map[string]*RegisteredOutput) bool {

	if len(p.Outputs) != len(src) {
		return false
	}
	for k, v := range p.Outputs {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_OutputRegistry = map[int16]string{
	1: "schema_version",
	2: "workflow",
	3: "outputs",
}

type OutputChanges struct {
	Accepted    []string `thrift:"accepted,1,optional,list<string>" json:"accepted,omitempty"`
	Invalidated []string `thrift:"invalidated,2,optional,list<string>" json:"invalidated,omitempty"`
}

func NewOutputChanges() *OutputChanges {
	return &OutputChanges{}
}

func (p *OutputChanges) InitDefault() {
}

var OutputChanges_Accepted_DEFAULT []string

func (p *OutputChanges) GetAccepted() (v []string) {
	if !p.IsSetAccepted() {
		return OutputChanges_Accepted_DEFAULT
	}
	return p.Accepted
}

var OutputChanges_Invalidated_DEFAULT []string

func (p *OutputChanges) GetInvalidated() (v []string) {
	if !p.IsSetInvalidated() {
		return OutputChanges_Invalidated_DEFAULT
	}
	return p.Invalidated
}

func (p *OutputChanges) IsSetAccepted() bool {
	return p.Accepted != nil
}

func (p *OutputChanges) IsSetInvalidated() bool {
	return p.Invalidated != nil
}

func (p *OutputChanges) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OutputChanges(%+v)", *p)
}

func (p *OutputChanges) DeepEqual(ano *OutputChanges) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Accepted) {
		return false
	}
	if !p.Field2DeepEqual(ano.Invalidated) {
		return false
	}
	return true
}

func (p *OutputChanges) Field1DeepEqual(src []string) bool {

	if len(p.Accepted) != len(src) {
		return false
	}
	for i, v := range p.Accepted {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *OutputChanges) Field2DeepEqual(src []string) bool {

	if len(p.Invalidated) != len(src) {
		return false
	}
	for i, v := range p.Invalidated {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}

var fieldIDToName_OutputChanges = map[int16]string{
	1: "accepted",
	2: "invalidated",
}

type Transition struct {
	Direction  TransitionDirection `thrift:"direction,1,required,TransitionDirection" json:"direction"`
	FromStepId string              `thrift:"from_step_id,2,required" json:"from_step_id"`
	ToStepId   *string             `thrift:"to_step_id,3,optional" json:"to_step_id,omitempty"`
}

func NewTransition() *Transition {
	return &Transition{}
}

func (p *Transition) InitDefault() {
}

func (p *Transition) GetDirection() (v TransitionDirection) {
	return p.Direction
}

func (p *Transition) GetFromStepId() (v string) {
	return p.FromStepId
}

var Transition_ToStepId_DEFAULT string

func (p *Transition) GetToStepId() (v string) {
	if !p.IsSetToStepId() {
		return Transition_ToStepId_DEFAULT
	}
	return *p.ToStepId
}

func (p *Transition) IsSetToStepId() bool {
	return p.ToStepId != nil
}

func (p *Transition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Transition(%+v)", *p)
}

func (p *Transition) DeepEqual(ano *Transition) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Direction) {
		return false
	}
	if !p.Field2DeepEqual(ano.FromStepId) {
		return false
	}
	if !p.Field3DeepEqual(ano.ToStepId) {
		return false
	}
	return true
}

func (p *Transition) Field1DeepEqual(src TransitionDirection) bool {

	if p.Direction != src {
		return false
	}
	return true
}
func (p *Transition) Field2DeepEqual(src string) bool {

	if strings.Compare(p.FromStepId, src) != 0 {
		return false
	}
	return true
}
func (p *Transition) Field3DeepEqual(src *string) bool {

	if p.ToStepId == src {
		return true
	} else if p.ToStepId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.ToStepId, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_Transition = map[int16]string{
	1: "direction",
	2: "from_step_id",
	3: "to_step_id",
}

type FlowInitializedPayload struct {
	StepId     string     `thrift:"step_id,1,required" json:"step_id"`
	StepStatus StepStatus `thrift:"step_status,2,required,StepStatus" json:"step_status"`
}

func NewFlowInitializedPayload() *FlowInitializedPayload {
	return &FlowInitializedPayload{}
}

func (p *FlowInitializedPayload) InitDefault() {
}

func (p *FlowInitializedPayload) GetStepId() (v string) {
	return p.StepId
}

func (p *FlowInitializedPayload) GetStepStatus() (v StepStatus) {
	return p.StepStatus
}

func (p *FlowInitializedPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowInitializedPayload(%+v)", *p)
}

func (p *FlowInitializedPayload) DeepEqual(ano *FlowInitializedPayload) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.StepId) {
		return false
	}
	if !p.Field2DeepEqual(ano.StepStatus) {
		return false
	}
	return true
}

func (p *FlowInitializedPayload) Field1DeepEqual(src string) bool {

	if strings.Compare(p.StepId, src) != 0 {
		return false
	}
	return true
}
func (p *FlowInitializedPayload) Field2DeepEqual(src StepStatus) bool {

	if p.StepStatus != src {
		return false
	}
	return true
}

var fieldIDToName_FlowInitializedPayload = map[int16]string{
	1: "step_id",
	2: "step_status",
}

type FlowProgressedPayload struct {
	FromStepId     string      `thrift:"from_step_id,1,required" json:"from_step_id"`
	FromStepStatus StepStatus  `thrift:"from_step_status,2,required,StepStatus" json:"from_step_status"`
	ToStepStatus   StepStatus  `thrift:"to_step_status,3,required,StepStatus" json:"to_step_status"`
	Summary        string      `thrift:"summary,4,required" json:"summary"`
	Evidence       []*Evidence `thrift:"evidence,5,optional,list<Evidence>" json:"evidence,omitempty"`
}

func NewFlowProgressedPayload() *FlowProgressedPayload {
	return &FlowProgressedPayload{}
}

func (p *FlowProgressedPayload) InitDefault() {
}

func (p *FlowProgressedPayload) GetFromStepId() (v string) {
	return p.FromStepId
}

func (p *FlowProgressedPayload) GetFromStepStatus() (v StepStatus) {
	return p.FromStepStatus
}

func (p *FlowProgressedPayload) GetToStepStatus() (v StepStatus) {
	return p.ToStepStatus
}

func (p *FlowProgressedPayload) GetSummary() (v string) {
	return p.Summary
}

var FlowProgressedPayload_Evidence_DEFAULT []*Evidence

func (p *FlowProgressedPayload) GetEvidence() (v []*Evidence) {
	if !p.IsSetEvidence() {
		return FlowProgressedPayload_Evidence_DEFAULT
	}
	return p.Evidence
}

func (p *FlowProgressedPayload) IsSetEvidence() bool {
	return p.Evidence != nil
}

func (p *FlowProgressedPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowProgressedPayload(%+v)", *p)
}

func (p *FlowProgressedPayload) DeepEqual(ano *FlowProgressedPayload) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.FromStepId) {
		return false
	}
	if !p.Field2DeepEqual(ano.FromStepStatus) {
		return false
	}
	if !p.Field3DeepEqual(ano.ToStepStatus) {
		return false
	}
	if !p.Field4DeepEqual(ano.Summary) {
		return false
	}
	if !p.Field5DeepEqual(ano.Evidence) {
		return false
	}
	return true
}

func (p *FlowProgressedPayload) Field1DeepEqual(src string) bool {

	if strings.Compare(p.FromStepId, src) != 0 {
		return false
	}
	return true
}
func (p *FlowProgressedPayload) Field2DeepEqual(src StepStatus) bool {

	if p.FromStepStatus != src {
		return false
	}
	return true
}
func (p *FlowProgressedPayload) Field3DeepEqual(src StepStatus) bool {

	if p.ToStepStatus != src {
		return false
	}
	return true
}
func (p *FlowProgressedPayload) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Summary, src) != 0 {
		return false
	}
	return true
}
func (p *FlowProgressedPayload) Field5DeepEqual(src []*Evidence) bool {

	if len(p.Evidence) != len(src) {
		return false
	}
	for i, v := range p.Evidence {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_FlowProgressedPayload = map[int16]string{
	1: "from_step_id",
	2: "from_step_status",
	3: "to_step_status",
	4: "summary",
	5: "evidence",
}

type FlowResultPayload struct {
	ConditionResults []*ConditionResult `thrift:"condition_results,1,required,list<ConditionResult>" json:"condition_results"`
	Evidence         []*Evidence        `thrift:"evidence,2,optional,list<Evidence>" json:"evidence,omitempty"`
	Summary          string             `thrift:"summary,3,required" json:"summary"`
	Effect           ResultEffect       `thrift:"effect,4,required,ResultEffect" json:"effect"`
	Transition       *Transition        `thrift:"transition,5,required" json:"transition"`
	OutputChanges    *OutputChanges     `thrift:"output_changes,6,required" json:"output_changes"`
}

func NewFlowResultPayload() *FlowResultPayload {
	return &FlowResultPayload{}
}

func (p *FlowResultPayload) InitDefault() {
}

func (p *FlowResultPayload) GetConditionResults() (v []*ConditionResult) {
	return p.ConditionResults
}

var FlowResultPayload_Evidence_DEFAULT []*Evidence

func (p *FlowResultPayload) GetEvidence() (v []*Evidence) {
	if !p.IsSetEvidence() {
		return FlowResultPayload_Evidence_DEFAULT
	}
	return p.Evidence
}

func (p *FlowResultPayload) GetSummary() (v string) {
	return p.Summary
}

func (p *FlowResultPayload) GetEffect() (v ResultEffect) {
	return p.Effect
}

var FlowResultPayload_Transition_DEFAULT *Transition

func (p *FlowResultPayload) GetTransition() (v *Transition) {
	if !p.IsSetTransition() {
		return FlowResultPayload_Transition_DEFAULT
	}
	return p.Transition
}

var FlowResultPayload_OutputChanges_DEFAULT *OutputChanges

func (p *FlowResultPayload) GetOutputChanges() (v *OutputChanges) {
	if !p.IsSetOutputChanges() {
		return FlowResultPayload_OutputChanges_DEFAULT
	}
	return p.OutputChanges
}

func (p *FlowResultPayload) IsSetEvidence() bool {
	return p.Evidence != nil
}

func (p *FlowResultPayload) IsSetTransition() bool {
	return p.Transition != nil
}

func (p *FlowResultPayload) IsSetOutputChanges() bool {
	return p.OutputChanges != nil
}

func (p *FlowResultPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowResultPayload(%+v)", *p)
}

func (p *FlowResultPayload) DeepEqual(ano *FlowResultPayload) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.ConditionResults) {
		return false
	}
	if !p.Field2DeepEqual(ano.Evidence) {
		return false
	}
	if !p.Field3DeepEqual(ano.Summary) {
		return false
	}
	if !p.Field4DeepEqual(ano.Effect) {
		return false
	}
	if !p.Field5DeepEqual(ano.Transition) {
		return false
	}
	if !p.Field6DeepEqual(ano.OutputChanges) {
		return false
	}
	return true
}

func (p *FlowResultPayload) Field1DeepEqual(src []*ConditionResult) bool {

	if len(p.ConditionResults) != len(src) {
		return false
	}
	for i, v := range p.ConditionResults {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FlowResultPayload) Field2DeepEqual(src []*Evidence) bool {

	if len(p.Evidence) != len(src) {
		return false
	}
	for i, v := range p.Evidence {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FlowResultPayload) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Summary, src) != 0 {
		return false
	}
	return true
}
func (p *FlowResultPayload) Field4DeepEqual(src ResultEffect) bool {

	if p.Effect != src {
		return false
	}
	return true
}
func (p *FlowResultPayload) Field5DeepEqual(src *Transition) bool {

	if !p.Transition.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowResultPayload) Field6DeepEqual(src *OutputChanges) bool {

	if !p.OutputChanges.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowResultPayload = map[int16]string{
	1: "condition_results",
	2: "evidence",
	3: "summary",
	4: "effect",
	5: "transition",
	6: "output_changes",
}

type TraceDocumentBoundPayload struct {
	PreviousDocumentUrl       *string          `thrift:"previous_document_url,1,optional" json:"previous_document_url,omitempty"`
	DocumentUrl               string           `thrift:"document_url,2,required" json:"document_url"`
	PreviousRegistry          *RegistryProfile `thrift:"previous_registry,3,optional,RegistryProfile" json:"previous_registry,omitempty"`
	Registry                  RegistryProfile  `thrift:"registry,4,required,RegistryProfile" json:"registry"`
	PreviousCliLogDocumentUrl *string          `thrift:"previous_cli_log_document_url,5,optional" json:"previous_cli_log_document_url,omitempty"`
	CliLogDocumentUrl         *string          `thrift:"cli_log_document_url,6,optional" json:"cli_log_document_url,omitempty"`
}

func NewTraceDocumentBoundPayload() *TraceDocumentBoundPayload {
	return &TraceDocumentBoundPayload{}
}

func (p *TraceDocumentBoundPayload) InitDefault() {
}

var TraceDocumentBoundPayload_PreviousDocumentUrl_DEFAULT string

func (p *TraceDocumentBoundPayload) GetPreviousDocumentUrl() (v string) {
	if !p.IsSetPreviousDocumentUrl() {
		return TraceDocumentBoundPayload_PreviousDocumentUrl_DEFAULT
	}
	return *p.PreviousDocumentUrl
}

func (p *TraceDocumentBoundPayload) GetDocumentUrl() (v string) {
	return p.DocumentUrl
}

var TraceDocumentBoundPayload_PreviousRegistry_DEFAULT RegistryProfile

func (p *TraceDocumentBoundPayload) GetPreviousRegistry() (v RegistryProfile) {
	if !p.IsSetPreviousRegistry() {
		return TraceDocumentBoundPayload_PreviousRegistry_DEFAULT
	}
	return *p.PreviousRegistry
}

func (p *TraceDocumentBoundPayload) GetRegistry() (v RegistryProfile) {
	return p.Registry
}

var TraceDocumentBoundPayload_PreviousCliLogDocumentUrl_DEFAULT string

func (p *TraceDocumentBoundPayload) GetPreviousCliLogDocumentUrl() (v string) {
	if !p.IsSetPreviousCliLogDocumentUrl() {
		return TraceDocumentBoundPayload_PreviousCliLogDocumentUrl_DEFAULT
	}
	return *p.PreviousCliLogDocumentUrl
}

var TraceDocumentBoundPayload_CliLogDocumentUrl_DEFAULT string

func (p *TraceDocumentBoundPayload) GetCliLogDocumentUrl() (v string) {
	if !p.IsSetCliLogDocumentUrl() {
		return TraceDocumentBoundPayload_CliLogDocumentUrl_DEFAULT
	}
	return *p.CliLogDocumentUrl
}

func (p *TraceDocumentBoundPayload) IsSetPreviousDocumentUrl() bool {
	return p.PreviousDocumentUrl != nil
}

func (p *TraceDocumentBoundPayload) IsSetPreviousRegistry() bool {
	return p.PreviousRegistry != nil
}

func (p *TraceDocumentBoundPayload) IsSetPreviousCliLogDocumentUrl() bool {
	return p.PreviousCliLogDocumentUrl != nil
}

func (p *TraceDocumentBoundPayload) IsSetCliLogDocumentUrl() bool {
	return p.CliLogDocumentUrl != nil
}

func (p *TraceDocumentBoundPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceDocumentBoundPayload(%+v)", *p)
}

func (p *TraceDocumentBoundPayload) DeepEqual(ano *TraceDocumentBoundPayload) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.PreviousDocumentUrl) {
		return false
	}
	if !p.Field2DeepEqual(ano.DocumentUrl) {
		return false
	}
	if !p.Field3DeepEqual(ano.PreviousRegistry) {
		return false
	}
	if !p.Field4DeepEqual(ano.Registry) {
		return false
	}
	if !p.Field5DeepEqual(ano.PreviousCliLogDocumentUrl) {
		return false
	}
	if !p.Field6DeepEqual(ano.CliLogDocumentUrl) {
		return false
	}
	return true
}

func (p *TraceDocumentBoundPayload) Field1DeepEqual(src *string) bool {

	if p.PreviousDocumentUrl == src {
		return true
	} else if p.PreviousDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.PreviousDocumentUrl, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceDocumentBoundPayload) Field2DeepEqual(src string) bool {

	if strings.Compare(p.DocumentUrl, src) != 0 {
		return false
	}
	return true
}
func (p *TraceDocumentBoundPayload) Field3DeepEqual(src *RegistryProfile) bool {

	if p.PreviousRegistry == src {
		return true
	} else if p.PreviousRegistry == nil || src == nil {
		return false
	}
	if *p.PreviousRegistry != *src {
		return false
	}
	return true
}
func (p *TraceDocumentBoundPayload) Field4DeepEqual(src RegistryProfile) bool {

	if p.Registry != src {
		return false
	}
	return true
}
func (p *TraceDocumentBoundPayload) Field5DeepEqual(src *string) bool {

	if p.PreviousCliLogDocumentUrl == src {
		return true
	} else if p.PreviousCliLogDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.PreviousCliLogDocumentUrl, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceDocumentBoundPayload) Field6DeepEqual(src *string) bool {

	if p.CliLogDocumentUrl == src {
		return true
	} else if p.CliLogDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CliLogDocumentUrl, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_TraceDocumentBoundPayload = map[int16]string{
	1: "previous_document_url",
	2: "document_url",
	3: "previous_registry",
	4: "registry",
	5: "previous_cli_log_document_url",
	6: "cli_log_document_url",
}

type TraceSyncStartedPayload struct {
	Targets []TraceTarget `thrift:"targets,1,required,list<TraceTarget>" json:"targets"`
}

func NewTraceSyncStartedPayload() *TraceSyncStartedPayload {
	return &TraceSyncStartedPayload{}
}

func (p *TraceSyncStartedPayload) InitDefault() {
}

func (p *TraceSyncStartedPayload) GetTargets() (v []TraceTarget) {
	return p.Targets
}

func (p *TraceSyncStartedPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceSyncStartedPayload(%+v)", *p)
}

func (p *TraceSyncStartedPayload) DeepEqual(ano *TraceSyncStartedPayload) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Targets) {
		return false
	}
	return true
}

func (p *TraceSyncStartedPayload) Field1DeepEqual(src []TraceTarget) bool {

	if len(p.Targets) != len(src) {
		return false
	}
	for i, v := range p.Targets {
		_src := src[i]
		if v != _src {
			return false
		}
	}
	return true
}

var fieldIDToName_TraceSyncStartedPayload = map[int16]string{
	1: "targets",
}

type TraceTargetError struct {
	Code      TraceTargetErrorCode `thrift:"code,1,required,TraceTargetErrorCode" json:"code"`
	Message   string               `thrift:"message,2,required" json:"message"`
	Retryable bool                 `thrift:"retryable,3,required" json:"retryable"`
}

func NewTraceTargetError() *TraceTargetError {
	return &TraceTargetError{}
}

func (p *TraceTargetError) InitDefault() {
}

func (p *TraceTargetError) GetCode() (v TraceTargetErrorCode) {
	return p.Code
}

func (p *TraceTargetError) GetMessage() (v string) {
	return p.Message
}

func (p *TraceTargetError) GetRetryable() (v bool) {
	return p.Retryable
}

func (p *TraceTargetError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceTargetError(%+v)", *p)
}

func (p *TraceTargetError) DeepEqual(ano *TraceTargetError) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Code) {
		return false
	}
	if !p.Field2DeepEqual(ano.Message) {
		return false
	}
	if !p.Field3DeepEqual(ano.Retryable) {
		return false
	}
	return true
}

func (p *TraceTargetError) Field1DeepEqual(src TraceTargetErrorCode) bool {

	if p.Code != src {
		return false
	}
	return true
}
func (p *TraceTargetError) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Message, src) != 0 {
		return false
	}
	return true
}
func (p *TraceTargetError) Field3DeepEqual(src bool) bool {

	if p.Retryable != src {
		return false
	}
	return true
}

var fieldIDToName_TraceTargetError = map[int16]string{
	1: "code",
	2: "message",
	3: "retryable",
}

type TraceTargetResult struct {
	Target TraceTarget       `thrift:"target,1,required,TraceTarget" json:"target"`
	Status TraceTargetStatus `thrift:"status,2,required,TraceTargetStatus" json:"status"`
	Reason *string           `thrift:"reason,3,optional" json:"reason,omitempty"`
	Error  *TraceTargetError `thrift:"error,4,optional" json:"error,omitempty"`
}

func NewTraceTargetResult() *TraceTargetResult {
	return &TraceTargetResult{}
}

func (p *TraceTargetResult) InitDefault() {
}

func (p *TraceTargetResult) GetTarget() (v TraceTarget) {
	return p.Target
}

func (p *TraceTargetResult) GetStatus() (v TraceTargetStatus) {
	return p.Status
}

var TraceTargetResult_Reason_DEFAULT string

func (p *TraceTargetResult) GetReason() (v string) {
	if !p.IsSetReason() {
		return TraceTargetResult_Reason_DEFAULT
	}
	return *p.Reason
}

var TraceTargetResult_Error_DEFAULT *TraceTargetError

func (p *TraceTargetResult) GetError() (v *TraceTargetError) {
	if !p.IsSetError() {
		return TraceTargetResult_Error_DEFAULT
	}
	return p.Error
}

func (p *TraceTargetResult) IsSetReason() bool {
	return p.Reason != nil
}

func (p *TraceTargetResult) IsSetError() bool {
	return p.Error != nil
}

func (p *TraceTargetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceTargetResult(%+v)", *p)
}

func (p *TraceTargetResult) DeepEqual(ano *TraceTargetResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Target) {
		return false
	}
	if !p.Field2DeepEqual(ano.Status) {
		return false
	}
	if !p.Field3DeepEqual(ano.Reason) {
		return false
	}
	if !p.Field4DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *TraceTargetResult) Field1DeepEqual(src TraceTarget) bool {

	if p.Target != src {
		return false
	}
	return true
}
func (p *TraceTargetResult) Field2DeepEqual(src TraceTargetStatus) bool {

	if p.Status != src {
		return false
	}
	return true
}
func (p *TraceTargetResult) Field3DeepEqual(src *string) bool {

	if p.Reason == src {
		return true
	} else if p.Reason == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Reason, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceTargetResult) Field4DeepEqual(src *TraceTargetError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_TraceTargetResult = map[int16]string{
	1: "target",
	2: "status",
	3: "reason",
	4: "error",
}

type TraceSyncedPayload struct {
	Outcome TraceSyncOutcome     `thrift:"outcome,1,required,TraceSyncOutcome" json:"outcome"`
	Targets []*TraceTargetResult `thrift:"targets,2,required,list<TraceTargetResult>" json:"targets"`
}

func NewTraceSyncedPayload() *TraceSyncedPayload {
	return &TraceSyncedPayload{}
}

func (p *TraceSyncedPayload) InitDefault() {
}

func (p *TraceSyncedPayload) GetOutcome() (v TraceSyncOutcome) {
	return p.Outcome
}

func (p *TraceSyncedPayload) GetTargets() (v []*TraceTargetResult) {
	return p.Targets
}

func (p *TraceSyncedPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceSyncedPayload(%+v)", *p)
}

func (p *TraceSyncedPayload) DeepEqual(ano *TraceSyncedPayload) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Outcome) {
		return false
	}
	if !p.Field2DeepEqual(ano.Targets) {
		return false
	}
	return true
}

func (p *TraceSyncedPayload) Field1DeepEqual(src TraceSyncOutcome) bool {

	if p.Outcome != src {
		return false
	}
	return true
}
func (p *TraceSyncedPayload) Field2DeepEqual(src []*TraceTargetResult) bool {

	if len(p.Targets) != len(src) {
		return false
	}
	for i, v := range p.Targets {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_TraceSyncedPayload = map[int16]string{
	1: "outcome",
	2: "targets",
}

type Event struct {
	SchemaVersion   int32                  `thrift:"schema_version,1,required" json:"schema_version"`
	EventId         string                 `thrift:"event_id,2,required" json:"event_id"`
	OccurredAt      string                 `thrift:"occurred_at,3,required" json:"occurred_at"`
	Kind            EventKind              `thrift:"kind,4,required,EventKind" json:"kind"`
	Command         string                 `thrift:"command,5,required" json:"command"`
	Workflow        *commonidl.WorkflowRef `thrift:"workflow,6,required" json:"workflow"`
	CausedByEventId *string                `thrift:"caused_by_event_id,7,optional" json:"caused_by_event_id,omitempty"`
	Payload         *EventPayload          `thrift:"payload,8,required" json:"payload"`
}

func NewEvent() *Event {
	return &Event{}
}

func (p *Event) InitDefault() {
}

func (p *Event) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

func (p *Event) GetEventId() (v string) {
	return p.EventId
}

func (p *Event) GetOccurredAt() (v string) {
	return p.OccurredAt
}

func (p *Event) GetKind() (v EventKind) {
	return p.Kind
}

func (p *Event) GetCommand() (v string) {
	return p.Command
}

var Event_Workflow_DEFAULT *commonidl.WorkflowRef

func (p *Event) GetWorkflow() (v *commonidl.WorkflowRef) {
	if !p.IsSetWorkflow() {
		return Event_Workflow_DEFAULT
	}
	return p.Workflow
}

var Event_CausedByEventId_DEFAULT string

func (p *Event) GetCausedByEventId() (v string) {
	if !p.IsSetCausedByEventId() {
		return Event_CausedByEventId_DEFAULT
	}
	return *p.CausedByEventId
}

var Event_Payload_DEFAULT *EventPayload

func (p *Event) GetPayload() (v *EventPayload) {
	if !p.IsSetPayload() {
		return Event_Payload_DEFAULT
	}
	return p.Payload
}

func (p *Event) IsSetWorkflow() bool {
	return p.Workflow != nil
}

func (p *Event) IsSetCausedByEventId() bool {
	return p.CausedByEventId != nil
}

func (p *Event) IsSetPayload() bool {
	return p.Payload != nil
}

func (p *Event) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Event(%+v)", *p)
}

func (p *Event) DeepEqual(ano *Event) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.EventId) {
		return false
	}
	if !p.Field3DeepEqual(ano.OccurredAt) {
		return false
	}
	if !p.Field4DeepEqual(ano.Kind) {
		return false
	}
	if !p.Field5DeepEqual(ano.Command) {
		return false
	}
	if !p.Field6DeepEqual(ano.Workflow) {
		return false
	}
	if !p.Field7DeepEqual(ano.CausedByEventId) {
		return false
	}
	if !p.Field8DeepEqual(ano.Payload) {
		return false
	}
	return true
}

func (p *Event) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *Event) Field2DeepEqual(src string) bool {

	if strings.Compare(p.EventId, src) != 0 {
		return false
	}
	return true
}
func (p *Event) Field3DeepEqual(src string) bool {

	if strings.Compare(p.OccurredAt, src) != 0 {
		return false
	}
	return true
}
func (p *Event) Field4DeepEqual(src EventKind) bool {

	if p.Kind != src {
		return false
	}
	return true
}
func (p *Event) Field5DeepEqual(src string) bool {

	if strings.Compare(p.Command, src) != 0 {
		return false
	}
	return true
}
func (p *Event) Field6DeepEqual(src *commonidl.WorkflowRef) bool {

	if !p.Workflow.DeepEqual(src) {
		return false
	}
	return true
}
func (p *Event) Field7DeepEqual(src *string) bool {

	if p.CausedByEventId == src {
		return true
	} else if p.CausedByEventId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CausedByEventId, *src) != 0 {
		return false
	}
	return true
}
func (p *Event) Field8DeepEqual(src *EventPayload) bool {

	if !p.Payload.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_Event = map[int16]string{
	1: "schema_version",
	2: "event_id",
	3: "occurred_at",
	4: "kind",
	5: "command",
	6: "workflow",
	7: "caused_by_event_id",
	8: "payload",
}

type CardProjection struct {
	SchemaVersion      int32                        `thrift:"schema_version,1,required" json:"schema_version"`
	Requirement        *Requirement                 `thrift:"requirement,2,required" json:"requirement"`
	Release            *Release                     `thrift:"release,3,required" json:"release"`
	CurrentStepId      *string                      `thrift:"current_step_id,4,optional" json:"current_step_id,omitempty"`
	CurrentStepStatus  *StepStatus                  `thrift:"current_step_status,5,optional,StepStatus" json:"current_step_status,omitempty"`
	CurrentStepSummary *string                      `thrift:"current_step_summary,6,optional" json:"current_step_summary,omitempty"`
	CurrentEvidence    []*Evidence                  `thrift:"current_evidence,7,optional,list<Evidence>" json:"current_evidence,omitempty"`
	Outputs            map[string]*RegisteredOutput `thrift:"outputs,8,required" json:"outputs"`
	TraceDocumentUrl   *string                      `thrift:"trace_document_url,9,optional" json:"trace_document_url,omitempty"`
	SourceEventId      string                       `thrift:"source_event_id,10,required" json:"source_event_id"`
	UpdatedAt          string                       `thrift:"updated_at,11,required" json:"updated_at"`
	CliLogDocumentUrl  *string                      `thrift:"cli_log_document_url,12,optional" json:"cli_log_document_url,omitempty"`
}

func NewCardProjection() *CardProjection {
	return &CardProjection{}
}

func (p *CardProjection) InitDefault() {
}

func (p *CardProjection) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

var CardProjection_Requirement_DEFAULT *Requirement

func (p *CardProjection) GetRequirement() (v *Requirement) {
	if !p.IsSetRequirement() {
		return CardProjection_Requirement_DEFAULT
	}
	return p.Requirement
}

var CardProjection_Release_DEFAULT *Release

func (p *CardProjection) GetRelease() (v *Release) {
	if !p.IsSetRelease() {
		return CardProjection_Release_DEFAULT
	}
	return p.Release
}

var CardProjection_CurrentStepId_DEFAULT string

func (p *CardProjection) GetCurrentStepId() (v string) {
	if !p.IsSetCurrentStepId() {
		return CardProjection_CurrentStepId_DEFAULT
	}
	return *p.CurrentStepId
}

var CardProjection_CurrentStepStatus_DEFAULT StepStatus

func (p *CardProjection) GetCurrentStepStatus() (v StepStatus) {
	if !p.IsSetCurrentStepStatus() {
		return CardProjection_CurrentStepStatus_DEFAULT
	}
	return *p.CurrentStepStatus
}

var CardProjection_CurrentStepSummary_DEFAULT string

func (p *CardProjection) GetCurrentStepSummary() (v string) {
	if !p.IsSetCurrentStepSummary() {
		return CardProjection_CurrentStepSummary_DEFAULT
	}
	return *p.CurrentStepSummary
}

var CardProjection_CurrentEvidence_DEFAULT []*Evidence

func (p *CardProjection) GetCurrentEvidence() (v []*Evidence) {
	if !p.IsSetCurrentEvidence() {
		return CardProjection_CurrentEvidence_DEFAULT
	}
	return p.CurrentEvidence
}

func (p *CardProjection) GetOutputs() (v map[string]*RegisteredOutput) {
	return p.Outputs
}

var CardProjection_TraceDocumentUrl_DEFAULT string

func (p *CardProjection) GetTraceDocumentUrl() (v string) {
	if !p.IsSetTraceDocumentUrl() {
		return CardProjection_TraceDocumentUrl_DEFAULT
	}
	return *p.TraceDocumentUrl
}

func (p *CardProjection) GetSourceEventId() (v string) {
	return p.SourceEventId
}

func (p *CardProjection) GetUpdatedAt() (v string) {
	return p.UpdatedAt
}

var CardProjection_CliLogDocumentUrl_DEFAULT string

func (p *CardProjection) GetCliLogDocumentUrl() (v string) {
	if !p.IsSetCliLogDocumentUrl() {
		return CardProjection_CliLogDocumentUrl_DEFAULT
	}
	return *p.CliLogDocumentUrl
}

func (p *CardProjection) IsSetRequirement() bool {
	return p.Requirement != nil
}

func (p *CardProjection) IsSetRelease() bool {
	return p.Release != nil
}

func (p *CardProjection) IsSetCurrentStepId() bool {
	return p.CurrentStepId != nil
}

func (p *CardProjection) IsSetCurrentStepStatus() bool {
	return p.CurrentStepStatus != nil
}

func (p *CardProjection) IsSetCurrentStepSummary() bool {
	return p.CurrentStepSummary != nil
}

func (p *CardProjection) IsSetCurrentEvidence() bool {
	return p.CurrentEvidence != nil
}

func (p *CardProjection) IsSetTraceDocumentUrl() bool {
	return p.TraceDocumentUrl != nil
}

func (p *CardProjection) IsSetCliLogDocumentUrl() bool {
	return p.CliLogDocumentUrl != nil
}

func (p *CardProjection) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CardProjection(%+v)", *p)
}

func (p *CardProjection) DeepEqual(ano *CardProjection) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.Requirement) {
		return false
	}
	if !p.Field3DeepEqual(ano.Release) {
		return false
	}
	if !p.Field4DeepEqual(ano.CurrentStepId) {
		return false
	}
	if !p.Field5DeepEqual(ano.CurrentStepStatus) {
		return false
	}
	if !p.Field6DeepEqual(ano.CurrentStepSummary) {
		return false
	}
	if !p.Field7DeepEqual(ano.CurrentEvidence) {
		return false
	}
	if !p.Field8DeepEqual(ano.Outputs) {
		return false
	}
	if !p.Field9DeepEqual(ano.TraceDocumentUrl) {
		return false
	}
	if !p.Field10DeepEqual(ano.SourceEventId) {
		return false
	}
	if !p.Field11DeepEqual(ano.UpdatedAt) {
		return false
	}
	if !p.Field12DeepEqual(ano.CliLogDocumentUrl) {
		return false
	}
	return true
}

func (p *CardProjection) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *CardProjection) Field2DeepEqual(src *Requirement) bool {

	if !p.Requirement.DeepEqual(src) {
		return false
	}
	return true
}
func (p *CardProjection) Field3DeepEqual(src *Release) bool {

	if !p.Release.DeepEqual(src) {
		return false
	}
	return true
}
func (p *CardProjection) Field4DeepEqual(src *string) bool {

	if p.CurrentStepId == src {
		return true
	} else if p.CurrentStepId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CurrentStepId, *src) != 0 {
		return false
	}
	return true
}
func (p *CardProjection) Field5DeepEqual(src *StepStatus) bool {

	if p.CurrentStepStatus == src {
		return true
	} else if p.CurrentStepStatus == nil || src == nil {
		return false
	}
	if *p.CurrentStepStatus != *src {
		return false
	}
	return true
}
func (p *CardProjection) Field6DeepEqual(src *string) bool {

	if p.CurrentStepSummary == src {
		return true
	} else if p.CurrentStepSummary == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CurrentStepSummary, *src) != 0 {
		return false
	}
	return true
}
func (p *CardProjection) Field7DeepEqual(src []*Evidence) bool {

	if len(p.CurrentEvidence) != len(src) {
		return false
	}
	for i, v := range p.CurrentEvidence {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *CardProjection) Field8DeepEqual(src map[string]*RegisteredOutput) bool {

	if len(p.Outputs) != len(src) {
		return false
	}
	for k, v := range p.Outputs {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *CardProjection) Field9DeepEqual(src *string) bool {

	if p.TraceDocumentUrl == src {
		return true
	} else if p.TraceDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.TraceDocumentUrl, *src) != 0 {
		return false
	}
	return true
}
func (p *CardProjection) Field10DeepEqual(src string) bool {

	if strings.Compare(p.SourceEventId, src) != 0 {
		return false
	}
	return true
}
func (p *CardProjection) Field11DeepEqual(src string) bool {

	if strings.Compare(p.UpdatedAt, src) != 0 {
		return false
	}
	return true
}
func (p *CardProjection) Field12DeepEqual(src *string) bool {

	if p.CliLogDocumentUrl == src {
		return true
	} else if p.CliLogDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CliLogDocumentUrl, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_CardProjection = map[int16]string{
	1:  "schema_version",
	2:  "requirement",
	3:  "release",
	4:  "current_step_id",
	5:  "current_step_status",
	6:  "current_step_summary",
	7:  "current_evidence",
	8:  "outputs",
	9:  "trace_document_url",
	10: "source_event_id",
	11: "updated_at",
	12: "cli_log_document_url",
}

type CardBinding struct {
	SchemaVersion int32  `thrift:"schema_version,1,required" json:"schema_version"`
	ChatId        string `thrift:"chat_id,2,required" json:"chat_id"`
	SessionId     string `thrift:"session_id,3,required" json:"session_id"`
}

func NewCardBinding() *CardBinding {
	return &CardBinding{}
}

func (p *CardBinding) InitDefault() {
}

func (p *CardBinding) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

func (p *CardBinding) GetChatId() (v string) {
	return p.ChatId
}

func (p *CardBinding) GetSessionId() (v string) {
	return p.SessionId
}

func (p *CardBinding) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CardBinding(%+v)", *p)
}

func (p *CardBinding) DeepEqual(ano *CardBinding) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.ChatId) {
		return false
	}
	if !p.Field3DeepEqual(ano.SessionId) {
		return false
	}
	return true
}

func (p *CardBinding) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *CardBinding) Field2DeepEqual(src string) bool {

	if strings.Compare(p.ChatId, src) != 0 {
		return false
	}
	return true
}
func (p *CardBinding) Field3DeepEqual(src string) bool {

	if strings.Compare(p.SessionId, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_CardBinding = map[int16]string{
	1: "schema_version",
	2: "chat_id",
	3: "session_id",
}

type TraceConfig struct {
	SchemaVersion               int32            `thrift:"schema_version,1,required" json:"schema_version"`
	TraceDocumentUrl            *string          `thrift:"trace_document_url,2,optional" json:"trace_document_url,omitempty"`
	RegistryProfile             *RegistryProfile `thrift:"registry_profile,3,optional,RegistryProfile" json:"registry_profile,omitempty"`
	RegistryUrl                 *string          `thrift:"registry_url,4,optional" json:"registry_url,omitempty"`
	RegistryBaseToken           *string          `thrift:"registry_base_token,5,optional" json:"registry_base_token,omitempty"`
	RegistryTableId             *string          `thrift:"registry_table_id,6,optional" json:"registry_table_id,omitempty"`
	RegistryViewId              *string          `thrift:"registry_view_id,7,optional" json:"registry_view_id,omitempty"`
	LastSyncAt                  string           `thrift:"last_sync_at,8,required" json:"last_sync_at"`
	LastSyncError               string           `thrift:"last_sync_error,9,required" json:"last_sync_error"`
	TraceDocumentLastSyncAt     string           `thrift:"trace_document_last_sync_at,10,required" json:"trace_document_last_sync_at"`
	TraceDocumentLastSyncError  string           `thrift:"trace_document_last_sync_error,11,required" json:"trace_document_last_sync_error"`
	RegistryLastSyncAt          string           `thrift:"registry_last_sync_at,12,required" json:"registry_last_sync_at"`
	RegistryLastSyncError       string           `thrift:"registry_last_sync_error,13,required" json:"registry_last_sync_error"`
	CliLogDocumentUrl           *string          `thrift:"cli_log_document_url,14,optional" json:"cli_log_document_url,omitempty"`
	CliLogDocumentLastSyncAt    string           `thrift:"cli_log_document_last_sync_at,15,required" json:"cli_log_document_last_sync_at"`
	CliLogDocumentLastSyncError string           `thrift:"cli_log_document_last_sync_error,16,required" json:"cli_log_document_last_sync_error"`
}

func NewTraceConfig() *TraceConfig {
	return &TraceConfig{}
}

func (p *TraceConfig) InitDefault() {
}

func (p *TraceConfig) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

var TraceConfig_TraceDocumentUrl_DEFAULT string

func (p *TraceConfig) GetTraceDocumentUrl() (v string) {
	if !p.IsSetTraceDocumentUrl() {
		return TraceConfig_TraceDocumentUrl_DEFAULT
	}
	return *p.TraceDocumentUrl
}

var TraceConfig_RegistryProfile_DEFAULT RegistryProfile

func (p *TraceConfig) GetRegistryProfile() (v RegistryProfile) {
	if !p.IsSetRegistryProfile() {
		return TraceConfig_RegistryProfile_DEFAULT
	}
	return *p.RegistryProfile
}

var TraceConfig_RegistryUrl_DEFAULT string

func (p *TraceConfig) GetRegistryUrl() (v string) {
	if !p.IsSetRegistryUrl() {
		return TraceConfig_RegistryUrl_DEFAULT
	}
	return *p.RegistryUrl
}

var TraceConfig_RegistryBaseToken_DEFAULT string

func (p *TraceConfig) GetRegistryBaseToken() (v string) {
	if !p.IsSetRegistryBaseToken() {
		return TraceConfig_RegistryBaseToken_DEFAULT
	}
	return *p.RegistryBaseToken
}

var TraceConfig_RegistryTableId_DEFAULT string

func (p *TraceConfig) GetRegistryTableId() (v string) {
	if !p.IsSetRegistryTableId() {
		return TraceConfig_RegistryTableId_DEFAULT
	}
	return *p.RegistryTableId
}

var TraceConfig_RegistryViewId_DEFAULT string

func (p *TraceConfig) GetRegistryViewId() (v string) {
	if !p.IsSetRegistryViewId() {
		return TraceConfig_RegistryViewId_DEFAULT
	}
	return *p.RegistryViewId
}

func (p *TraceConfig) GetLastSyncAt() (v string) {
	return p.LastSyncAt
}

func (p *TraceConfig) GetLastSyncError() (v string) {
	return p.LastSyncError
}

func (p *TraceConfig) GetTraceDocumentLastSyncAt() (v string) {
	return p.TraceDocumentLastSyncAt
}

func (p *TraceConfig) GetTraceDocumentLastSyncError() (v string) {
	return p.TraceDocumentLastSyncError
}

func (p *TraceConfig) GetRegistryLastSyncAt() (v string) {
	return p.RegistryLastSyncAt
}

func (p *TraceConfig) GetRegistryLastSyncError() (v string) {
	return p.RegistryLastSyncError
}

var TraceConfig_CliLogDocumentUrl_DEFAULT string

func (p *TraceConfig) GetCliLogDocumentUrl() (v string) {
	if !p.IsSetCliLogDocumentUrl() {
		return TraceConfig_CliLogDocumentUrl_DEFAULT
	}
	return *p.CliLogDocumentUrl
}

func (p *TraceConfig) GetCliLogDocumentLastSyncAt() (v string) {
	return p.CliLogDocumentLastSyncAt
}

func (p *TraceConfig) GetCliLogDocumentLastSyncError() (v string) {
	return p.CliLogDocumentLastSyncError
}

func (p *TraceConfig) IsSetTraceDocumentUrl() bool {
	return p.TraceDocumentUrl != nil
}

func (p *TraceConfig) IsSetRegistryProfile() bool {
	return p.RegistryProfile != nil
}

func (p *TraceConfig) IsSetRegistryUrl() bool {
	return p.RegistryUrl != nil
}

func (p *TraceConfig) IsSetRegistryBaseToken() bool {
	return p.RegistryBaseToken != nil
}

func (p *TraceConfig) IsSetRegistryTableId() bool {
	return p.RegistryTableId != nil
}

func (p *TraceConfig) IsSetRegistryViewId() bool {
	return p.RegistryViewId != nil
}

func (p *TraceConfig) IsSetCliLogDocumentUrl() bool {
	return p.CliLogDocumentUrl != nil
}

func (p *TraceConfig) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceConfig(%+v)", *p)
}

func (p *TraceConfig) DeepEqual(ano *TraceConfig) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.TraceDocumentUrl) {
		return false
	}
	if !p.Field3DeepEqual(ano.RegistryProfile) {
		return false
	}
	if !p.Field4DeepEqual(ano.RegistryUrl) {
		return false
	}
	if !p.Field5DeepEqual(ano.RegistryBaseToken) {
		return false
	}
	if !p.Field6DeepEqual(ano.RegistryTableId) {
		return false
	}
	if !p.Field7DeepEqual(ano.RegistryViewId) {
		return false
	}
	if !p.Field8DeepEqual(ano.LastSyncAt) {
		return false
	}
	if !p.Field9DeepEqual(ano.LastSyncError) {
		return false
	}
	if !p.Field10DeepEqual(ano.TraceDocumentLastSyncAt) {
		return false
	}
	if !p.Field11DeepEqual(ano.TraceDocumentLastSyncError) {
		return false
	}
	if !p.Field12DeepEqual(ano.RegistryLastSyncAt) {
		return false
	}
	if !p.Field13DeepEqual(ano.RegistryLastSyncError) {
		return false
	}
	if !p.Field14DeepEqual(ano.CliLogDocumentUrl) {
		return false
	}
	if !p.Field15DeepEqual(ano.CliLogDocumentLastSyncAt) {
		return false
	}
	if !p.Field16DeepEqual(ano.CliLogDocumentLastSyncError) {
		return false
	}
	return true
}

func (p *TraceConfig) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *TraceConfig) Field2DeepEqual(src *string) bool {

	if p.TraceDocumentUrl == src {
		return true
	} else if p.TraceDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.TraceDocumentUrl, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field3DeepEqual(src *RegistryProfile) bool {

	if p.RegistryProfile == src {
		return true
	} else if p.RegistryProfile == nil || src == nil {
		return false
	}
	if *p.RegistryProfile != *src {
		return false
	}
	return true
}
func (p *TraceConfig) Field4DeepEqual(src *string) bool {

	if p.RegistryUrl == src {
		return true
	} else if p.RegistryUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.RegistryUrl, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field5DeepEqual(src *string) bool {

	if p.RegistryBaseToken == src {
		return true
	} else if p.RegistryBaseToken == nil || src == nil {
		return false
	}
	if strings.Compare(*p.RegistryBaseToken, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field6DeepEqual(src *string) bool {

	if p.RegistryTableId == src {
		return true
	} else if p.RegistryTableId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.RegistryTableId, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field7DeepEqual(src *string) bool {

	if p.RegistryViewId == src {
		return true
	} else if p.RegistryViewId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.RegistryViewId, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field8DeepEqual(src string) bool {

	if strings.Compare(p.LastSyncAt, src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field9DeepEqual(src string) bool {

	if strings.Compare(p.LastSyncError, src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field10DeepEqual(src string) bool {

	if strings.Compare(p.TraceDocumentLastSyncAt, src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field11DeepEqual(src string) bool {

	if strings.Compare(p.TraceDocumentLastSyncError, src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field12DeepEqual(src string) bool {

	if strings.Compare(p.RegistryLastSyncAt, src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field13DeepEqual(src string) bool {

	if strings.Compare(p.RegistryLastSyncError, src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field14DeepEqual(src *string) bool {

	if p.CliLogDocumentUrl == src {
		return true
	} else if p.CliLogDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CliLogDocumentUrl, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field15DeepEqual(src string) bool {

	if strings.Compare(p.CliLogDocumentLastSyncAt, src) != 0 {
		return false
	}
	return true
}
func (p *TraceConfig) Field16DeepEqual(src string) bool {

	if strings.Compare(p.CliLogDocumentLastSyncError, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_TraceConfig = map[int16]string{
	1:  "schema_version",
	2:  "trace_document_url",
	3:  "registry_profile",
	4:  "registry_url",
	5:  "registry_base_token",
	6:  "registry_table_id",
	7:  "registry_view_id",
	8:  "last_sync_at",
	9:  "last_sync_error",
	10: "trace_document_last_sync_at",
	11: "trace_document_last_sync_error",
	12: "registry_last_sync_at",
	13: "registry_last_sync_error",
	14: "cli_log_document_url",
	15: "cli_log_document_last_sync_at",
	16: "cli_log_document_last_sync_error",
}

type EventPayload struct {
	FlowInitialized    *FlowInitializedPayload    `thrift:"flow_initialized,1,optional" json:"flow_initialized,omitempty"`
	FlowProgressed     *FlowProgressedPayload     `thrift:"flow_progressed,2,optional" json:"flow_progressed,omitempty"`
	FlowResult         *FlowResultPayload         `thrift:"flow_result,3,optional" json:"flow_result,omitempty"`
	TraceDocumentBound *TraceDocumentBoundPayload `thrift:"trace_document_bound,4,optional" json:"trace_document_bound,omitempty"`
	TraceSyncStarted   *TraceSyncStartedPayload   `thrift:"trace_sync_started,5,optional" json:"trace_sync_started,omitempty"`
	TraceSynced        *TraceSyncedPayload        `thrift:"trace_synced,6,optional" json:"trace_synced,omitempty"`
}

func NewEventPayload() *EventPayload {
	return &EventPayload{}
}

func (p *EventPayload) InitDefault() {
}

var EventPayload_FlowInitialized_DEFAULT *FlowInitializedPayload

func (p *EventPayload) GetFlowInitialized() (v *FlowInitializedPayload) {
	if !p.IsSetFlowInitialized() {
		return EventPayload_FlowInitialized_DEFAULT
	}
	return p.FlowInitialized
}

var EventPayload_FlowProgressed_DEFAULT *FlowProgressedPayload

func (p *EventPayload) GetFlowProgressed() (v *FlowProgressedPayload) {
	if !p.IsSetFlowProgressed() {
		return EventPayload_FlowProgressed_DEFAULT
	}
	return p.FlowProgressed
}

var EventPayload_FlowResult_DEFAULT *FlowResultPayload

func (p *EventPayload) GetFlowResult() (v *FlowResultPayload) {
	if !p.IsSetFlowResult() {
		return EventPayload_FlowResult_DEFAULT
	}
	return p.FlowResult
}

var EventPayload_TraceDocumentBound_DEFAULT *TraceDocumentBoundPayload

func (p *EventPayload) GetTraceDocumentBound() (v *TraceDocumentBoundPayload) {
	if !p.IsSetTraceDocumentBound() {
		return EventPayload_TraceDocumentBound_DEFAULT
	}
	return p.TraceDocumentBound
}

var EventPayload_TraceSyncStarted_DEFAULT *TraceSyncStartedPayload

func (p *EventPayload) GetTraceSyncStarted() (v *TraceSyncStartedPayload) {
	if !p.IsSetTraceSyncStarted() {
		return EventPayload_TraceSyncStarted_DEFAULT
	}
	return p.TraceSyncStarted
}

var EventPayload_TraceSynced_DEFAULT *TraceSyncedPayload

func (p *EventPayload) GetTraceSynced() (v *TraceSyncedPayload) {
	if !p.IsSetTraceSynced() {
		return EventPayload_TraceSynced_DEFAULT
	}
	return p.TraceSynced
}

func (p *EventPayload) CountSetFieldsEventPayload() int {
	count := 0
	if p.IsSetFlowInitialized() {
		count++
	}
	if p.IsSetFlowProgressed() {
		count++
	}
	if p.IsSetFlowResult() {
		count++
	}
	if p.IsSetTraceDocumentBound() {
		count++
	}
	if p.IsSetTraceSyncStarted() {
		count++
	}
	if p.IsSetTraceSynced() {
		count++
	}
	return count
}

func (p *EventPayload) IsSetFlowInitialized() bool {
	return p.FlowInitialized != nil
}

func (p *EventPayload) IsSetFlowProgressed() bool {
	return p.FlowProgressed != nil
}

func (p *EventPayload) IsSetFlowResult() bool {
	return p.FlowResult != nil
}

func (p *EventPayload) IsSetTraceDocumentBound() bool {
	return p.TraceDocumentBound != nil
}

func (p *EventPayload) IsSetTraceSyncStarted() bool {
	return p.TraceSyncStarted != nil
}

func (p *EventPayload) IsSetTraceSynced() bool {
	return p.TraceSynced != nil
}

func (p *EventPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("EventPayload(%+v)", *p)
}

func (p *EventPayload) DeepEqual(ano *EventPayload) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.FlowInitialized) {
		return false
	}
	if !p.Field2DeepEqual(ano.FlowProgressed) {
		return false
	}
	if !p.Field3DeepEqual(ano.FlowResult) {
		return false
	}
	if !p.Field4DeepEqual(ano.TraceDocumentBound) {
		return false
	}
	if !p.Field5DeepEqual(ano.TraceSyncStarted) {
		return false
	}
	if !p.Field6DeepEqual(ano.TraceSynced) {
		return false
	}
	return true
}

func (p *EventPayload) Field1DeepEqual(src *FlowInitializedPayload) bool {

	if !p.FlowInitialized.DeepEqual(src) {
		return false
	}
	return true
}
func (p *EventPayload) Field2DeepEqual(src *FlowProgressedPayload) bool {

	if !p.FlowProgressed.DeepEqual(src) {
		return false
	}
	return true
}
func (p *EventPayload) Field3DeepEqual(src *FlowResultPayload) bool {

	if !p.FlowResult.DeepEqual(src) {
		return false
	}
	return true
}
func (p *EventPayload) Field4DeepEqual(src *TraceDocumentBoundPayload) bool {

	if !p.TraceDocumentBound.DeepEqual(src) {
		return false
	}
	return true
}
func (p *EventPayload) Field5DeepEqual(src *TraceSyncStartedPayload) bool {

	if !p.TraceSyncStarted.DeepEqual(src) {
		return false
	}
	return true
}
func (p *EventPayload) Field6DeepEqual(src *TraceSyncedPayload) bool {

	if !p.TraceSynced.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_EventPayload = map[int16]string{
	1: "flow_initialized",
	2: "flow_progressed",
	3: "flow_result",
	4: "trace_document_bound",
	5: "trace_sync_started",
	6: "trace_synced",
}
