// Code generated by Validator v0.2.5. DO NOT EDIT.

package storageidl

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *CLIExecutionLogEntry) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	if len(p.InvocationId) < int(1) {
		return fmt.Errorf("field InvocationId min_len rule failed, current value: %d", len(p.InvocationId))
	}
	if len(p.StartedAt) < int(1) {
		return fmt.Errorf("field StartedAt min_len rule failed, current value: %d", len(p.StartedAt))
	}
	if p.DurationMs < int64(0) {
		return fmt.Errorf("field DurationMs ge rule failed, current value: %v", p.DurationMs)
	}
	if len(p.CommandId) < int(1) {
		return fmt.Errorf("field CommandId min_len rule failed, current value: %d", len(p.CommandId))
	}
	if len(p.CliVersion) < int(1) {
		return fmt.Errorf("field CliVersion min_len rule failed, current value: %d", len(p.CliVersion))
	}
	if len(p.ReleaseVersion) < int(1) {
		return fmt.Errorf("field ReleaseVersion min_len rule failed, current value: %d", len(p.ReleaseVersion))
	}
	if len(p.CommitSha) < int(1) {
		return fmt.Errorf("field CommitSha min_len rule failed, current value: %d", len(p.CommitSha))
	}
	if p.ExitCode < int32(0) {
		return fmt.Errorf("field ExitCode ge rule failed, current value: %v", p.ExitCode)
	}
	return nil
}
func (p *Requirement) IsValid() error {
	if len(p.Title) < int(1) {
		return fmt.Errorf("field Title min_len rule failed, current value: %d", len(p.Title))
	}
	return nil
}
func (p *Release) IsValid() error {
	if len(p.Version) < int(1) {
		return fmt.Errorf("field Version min_len rule failed, current value: %d", len(p.Version))
	}
	if p.Workflow == nil {
		return fmt.Errorf("field Workflow not_nil rule failed")
	}
	if err := p.Workflow.IsValid(); err != nil {
		return fmt.Errorf("field Workflow not valid, %w", err)
	}
	return nil
}
func (p *Evidence) IsValid() error {
	if p.Source.String() == "<UNSET>" {
		return fmt.Errorf("field Source defined_only rule failed")
	}
	_src := []EvidenceSource{EvidenceSource_unspecified}
	for _, src := range _src {
		if p.Source == src {
			return fmt.Errorf("field Source not_in rule failed, current value: %v", p.Source)
		}
	}
	if len(p.Content) < int(1) {
		return fmt.Errorf("field Content min_len rule failed, current value: %d", len(p.Content))
	}
	return nil
}
func (p *OutputValue) IsValid() error {
	if p.Type.String() == "<UNSET>" {
		return fmt.Errorf("field Type defined_only rule failed")
	}
	_src := []OutputType{OutputType_unspecified}
	for _, src := range _src {
		if p.Type == src {
			return fmt.Errorf("field Type not_in rule failed, current value: %v", p.Type)
		}
	}
	if p.Value == nil {
		return fmt.Errorf("field Value not_nil rule failed")
	}
	if err := p.Value.IsValid(); err != nil {
		return fmt.Errorf("field Value not valid, %w", err)
	}
	return nil
}
func (p *ConditionResult) IsValid() error {
	if len(p.ConditionId) < int(1) {
		return fmt.Errorf("field ConditionId min_len rule failed, current value: %d", len(p.ConditionId))
	}
	if p.Output == nil {
		return fmt.Errorf("field Output not_nil rule failed")
	}
	if err := p.Output.IsValid(); err != nil {
		return fmt.Errorf("field Output not valid, %w", err)
	}
	return nil
}
func (p *RegisteredOutput) IsValid() error {
	if p.Type.String() == "<UNSET>" {
		return fmt.Errorf("field Type defined_only rule failed")
	}
	_src := []OutputType{OutputType_unspecified}
	for _, src := range _src {
		if p.Type == src {
			return fmt.Errorf("field Type not_in rule failed, current value: %v", p.Type)
		}
	}
	if p.Value == nil {
		return fmt.Errorf("field Value not_nil rule failed")
	}
	if err := p.Value.IsValid(); err != nil {
		return fmt.Errorf("field Value not valid, %w", err)
	}
	if len(p.ProducerStepId) < int(1) {
		return fmt.Errorf("field ProducerStepId min_len rule failed, current value: %d", len(p.ProducerStepId))
	}
	return nil
}
func (p *TraceBinding) IsValid() error {
	if len(p.DocumentUrl) < int(1) {
		return fmt.Errorf("field DocumentUrl min_len rule failed, current value: %d", len(p.DocumentUrl))
	}
	if p.Registry.String() == "<UNSET>" {
		return fmt.Errorf("field Registry defined_only rule failed")
	}
	_src := []RegistryProfile{RegistryProfile_unspecified}
	for _, src := range _src {
		if p.Registry == src {
			return fmt.Errorf("field Registry not_in rule failed, current value: %v", p.Registry)
		}
	}
	return nil
}
func (p *Integrations) IsValid() error {
	if p.Trace != nil {
		if err := p.Trace.IsValid(); err != nil {
			return fmt.Errorf("field Trace not valid, %w", err)
		}
	}
	return nil
}
func (p *FlowState) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	if p.Requirement == nil {
		return fmt.Errorf("field Requirement not_nil rule failed")
	}
	if err := p.Requirement.IsValid(); err != nil {
		return fmt.Errorf("field Requirement not valid, %w", err)
	}
	if p.Release == nil {
		return fmt.Errorf("field Release not_nil rule failed")
	}
	if err := p.Release.IsValid(); err != nil {
		return fmt.Errorf("field Release not valid, %w", err)
	}
	if p.CurrentStepStatus != nil {
		if p.CurrentStepStatus.String() == "<UNSET>" {
			return fmt.Errorf("field CurrentStepStatus defined_only rule failed")
		}
		_src := []StepStatus{StepStatus_unspecified}
		for _, src := range _src {
			if *p.CurrentStepStatus == src {
				return fmt.Errorf("field CurrentStepStatus not_in rule failed, current value: %v", *p.CurrentStepStatus)
			}
		}
	}
	if p.Integrations == nil {
		return fmt.Errorf("field Integrations not_nil rule failed")
	}
	if err := p.Integrations.IsValid(); err != nil {
		return fmt.Errorf("field Integrations not valid, %w", err)
	}
	if len(p.LastEventId) < int(1) {
		return fmt.Errorf("field LastEventId min_len rule failed, current value: %d", len(p.LastEventId))
	}
	if len(p.CreatedAt) < int(1) {
		return fmt.Errorf("field CreatedAt min_len rule failed, current value: %d", len(p.CreatedAt))
	}
	if len(p.UpdatedAt) < int(1) {
		return fmt.Errorf("field UpdatedAt min_len rule failed, current value: %d", len(p.UpdatedAt))
	}
	return nil
}
func (p *OutputRegistry) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	if p.Workflow == nil {
		return fmt.Errorf("field Workflow not_nil rule failed")
	}
	if err := p.Workflow.IsValid(); err != nil {
		return fmt.Errorf("field Workflow not valid, %w", err)
	}
	return nil
}
func (p *OutputChanges) IsValid() error {
	return nil
}
func (p *Transition) IsValid() error {
	if p.Direction.String() == "<UNSET>" {
		return fmt.Errorf("field Direction defined_only rule failed")
	}
	_src := []TransitionDirection{TransitionDirection_unspecified}
	for _, src := range _src {
		if p.Direction == src {
			return fmt.Errorf("field Direction not_in rule failed, current value: %v", p.Direction)
		}
	}
	if len(p.FromStepId) < int(1) {
		return fmt.Errorf("field FromStepId min_len rule failed, current value: %d", len(p.FromStepId))
	}
	return nil
}
func (p *FlowInitializedPayload) IsValid() error {
	if len(p.StepId) < int(1) {
		return fmt.Errorf("field StepId min_len rule failed, current value: %d", len(p.StepId))
	}
	if p.StepStatus.String() == "<UNSET>" {
		return fmt.Errorf("field StepStatus defined_only rule failed")
	}
	_src := []StepStatus{StepStatus_unspecified}
	for _, src := range _src {
		if p.StepStatus == src {
			return fmt.Errorf("field StepStatus not_in rule failed, current value: %v", p.StepStatus)
		}
	}
	return nil
}
func (p *FlowProgressedPayload) IsValid() error {
	if len(p.FromStepId) < int(1) {
		return fmt.Errorf("field FromStepId min_len rule failed, current value: %d", len(p.FromStepId))
	}
	if p.FromStepStatus.String() == "<UNSET>" {
		return fmt.Errorf("field FromStepStatus defined_only rule failed")
	}
	_src := []StepStatus{StepStatus_unspecified}
	for _, src := range _src {
		if p.FromStepStatus == src {
			return fmt.Errorf("field FromStepStatus not_in rule failed, current value: %v", p.FromStepStatus)
		}
	}
	if p.ToStepStatus.String() == "<UNSET>" {
		return fmt.Errorf("field ToStepStatus defined_only rule failed")
	}
	_src1 := []StepStatus{StepStatus_unspecified}
	for _, src := range _src1 {
		if p.ToStepStatus == src {
			return fmt.Errorf("field ToStepStatus not_in rule failed, current value: %v", p.ToStepStatus)
		}
	}
	if len(p.Summary) < int(1) {
		return fmt.Errorf("field Summary min_len rule failed, current value: %d", len(p.Summary))
	}
	return nil
}
func (p *FlowResultPayload) IsValid() error {
	if len(p.ConditionResults) < int(1) {
		return fmt.Errorf("field ConditionResults MinLen rule failed, current value: %v", p.ConditionResults)
	}
	if len(p.Summary) < int(1) {
		return fmt.Errorf("field Summary min_len rule failed, current value: %d", len(p.Summary))
	}
	if p.Effect.String() == "<UNSET>" {
		return fmt.Errorf("field Effect defined_only rule failed")
	}
	_src := []ResultEffect{ResultEffect_unspecified}
	for _, src := range _src {
		if p.Effect == src {
			return fmt.Errorf("field Effect not_in rule failed, current value: %v", p.Effect)
		}
	}
	if p.Transition == nil {
		return fmt.Errorf("field Transition not_nil rule failed")
	}
	if err := p.Transition.IsValid(); err != nil {
		return fmt.Errorf("field Transition not valid, %w", err)
	}
	if p.OutputChanges == nil {
		return fmt.Errorf("field OutputChanges not_nil rule failed")
	}
	if err := p.OutputChanges.IsValid(); err != nil {
		return fmt.Errorf("field OutputChanges not valid, %w", err)
	}
	return nil
}
func (p *TraceDocumentBoundPayload) IsValid() error {
	if len(p.DocumentUrl) < int(1) {
		return fmt.Errorf("field DocumentUrl min_len rule failed, current value: %d", len(p.DocumentUrl))
	}
	if p.PreviousRegistry != nil {
		if p.PreviousRegistry.String() == "<UNSET>" {
			return fmt.Errorf("field PreviousRegistry defined_only rule failed")
		}
		_src := []RegistryProfile{RegistryProfile_unspecified}
		for _, src := range _src {
			if *p.PreviousRegistry == src {
				return fmt.Errorf("field PreviousRegistry not_in rule failed, current value: %v", *p.PreviousRegistry)
			}
		}
	}
	if p.Registry.String() == "<UNSET>" {
		return fmt.Errorf("field Registry defined_only rule failed")
	}
	_src1 := []RegistryProfile{RegistryProfile_unspecified}
	for _, src := range _src1 {
		if p.Registry == src {
			return fmt.Errorf("field Registry not_in rule failed, current value: %v", p.Registry)
		}
	}
	return nil
}
func (p *TraceSyncStartedPayload) IsValid() error {
	if len(p.Targets) < int(1) {
		return fmt.Errorf("field Targets MinLen rule failed, current value: %v", p.Targets)
	}
	return nil
}
func (p *TraceTargetError) IsValid() error {
	if p.Code.String() == "<UNSET>" {
		return fmt.Errorf("field Code defined_only rule failed")
	}
	_src := []TraceTargetErrorCode{TraceTargetErrorCode_unspecified}
	for _, src := range _src {
		if p.Code == src {
			return fmt.Errorf("field Code not_in rule failed, current value: %v", p.Code)
		}
	}
	if len(p.Message) < int(1) {
		return fmt.Errorf("field Message min_len rule failed, current value: %d", len(p.Message))
	}
	return nil
}
func (p *TraceTargetResult) IsValid() error {
	if p.Target.String() == "<UNSET>" {
		return fmt.Errorf("field Target defined_only rule failed")
	}
	_src := []TraceTarget{TraceTarget_unspecified}
	for _, src := range _src {
		if p.Target == src {
			return fmt.Errorf("field Target not_in rule failed, current value: %v", p.Target)
		}
	}
	if p.Status.String() == "<UNSET>" {
		return fmt.Errorf("field Status defined_only rule failed")
	}
	_src1 := []TraceTargetStatus{TraceTargetStatus_unspecified}
	for _, src := range _src1 {
		if p.Status == src {
			return fmt.Errorf("field Status not_in rule failed, current value: %v", p.Status)
		}
	}
	if p.Error != nil {
		if err := p.Error.IsValid(); err != nil {
			return fmt.Errorf("field Error not valid, %w", err)
		}
	}
	return nil
}
func (p *TraceSyncedPayload) IsValid() error {
	if p.Outcome.String() == "<UNSET>" {
		return fmt.Errorf("field Outcome defined_only rule failed")
	}
	_src := []TraceSyncOutcome{TraceSyncOutcome_unspecified}
	for _, src := range _src {
		if p.Outcome == src {
			return fmt.Errorf("field Outcome not_in rule failed, current value: %v", p.Outcome)
		}
	}
	if len(p.Targets) < int(1) {
		return fmt.Errorf("field Targets MinLen rule failed, current value: %v", p.Targets)
	}
	return nil
}
func (p *Event) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	if len(p.EventId) < int(1) {
		return fmt.Errorf("field EventId min_len rule failed, current value: %d", len(p.EventId))
	}
	if len(p.OccurredAt) < int(1) {
		return fmt.Errorf("field OccurredAt min_len rule failed, current value: %d", len(p.OccurredAt))
	}
	if p.Kind.String() == "<UNSET>" {
		return fmt.Errorf("field Kind defined_only rule failed")
	}
	_src := []EventKind{EventKind_unspecified}
	for _, src := range _src {
		if p.Kind == src {
			return fmt.Errorf("field Kind not_in rule failed, current value: %v", p.Kind)
		}
	}
	if len(p.Command) < int(1) {
		return fmt.Errorf("field Command min_len rule failed, current value: %d", len(p.Command))
	}
	if p.Workflow == nil {
		return fmt.Errorf("field Workflow not_nil rule failed")
	}
	if err := p.Workflow.IsValid(); err != nil {
		return fmt.Errorf("field Workflow not valid, %w", err)
	}
	if p.Payload == nil {
		return fmt.Errorf("field Payload not_nil rule failed")
	}
	if err := p.Payload.IsValid(); err != nil {
		return fmt.Errorf("field Payload not valid, %w", err)
	}
	return nil
}
func (p *CardProjection) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	if p.Requirement == nil {
		return fmt.Errorf("field Requirement not_nil rule failed")
	}
	if err := p.Requirement.IsValid(); err != nil {
		return fmt.Errorf("field Requirement not valid, %w", err)
	}
	if p.Release == nil {
		return fmt.Errorf("field Release not_nil rule failed")
	}
	if err := p.Release.IsValid(); err != nil {
		return fmt.Errorf("field Release not valid, %w", err)
	}
	if p.CurrentStepStatus != nil {
		if p.CurrentStepStatus.String() == "<UNSET>" {
			return fmt.Errorf("field CurrentStepStatus defined_only rule failed")
		}
		_src := []StepStatus{StepStatus_unspecified}
		for _, src := range _src {
			if *p.CurrentStepStatus == src {
				return fmt.Errorf("field CurrentStepStatus not_in rule failed, current value: %v", *p.CurrentStepStatus)
			}
		}
	}
	if len(p.SourceEventId) < int(1) {
		return fmt.Errorf("field SourceEventId min_len rule failed, current value: %d", len(p.SourceEventId))
	}
	if len(p.UpdatedAt) < int(1) {
		return fmt.Errorf("field UpdatedAt min_len rule failed, current value: %d", len(p.UpdatedAt))
	}
	return nil
}
func (p *CardBinding) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	if len(p.ChatId) < int(1) {
		return fmt.Errorf("field ChatId min_len rule failed, current value: %d", len(p.ChatId))
	}
	if len(p.SessionId) < int(1) {
		return fmt.Errorf("field SessionId min_len rule failed, current value: %d", len(p.SessionId))
	}
	return nil
}
func (p *TraceConfig) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	if p.RegistryProfile != nil {
		if p.RegistryProfile.String() == "<UNSET>" {
			return fmt.Errorf("field RegistryProfile defined_only rule failed")
		}
		_src := []RegistryProfile{RegistryProfile_unspecified}
		for _, src := range _src {
			if *p.RegistryProfile == src {
				return fmt.Errorf("field RegistryProfile not_in rule failed, current value: %v", *p.RegistryProfile)
			}
		}
	}
	return nil
}
func (p *EventPayload) IsValid() error {
	if p.FlowInitialized != nil {
		if err := p.FlowInitialized.IsValid(); err != nil {
			return fmt.Errorf("field FlowInitialized not valid, %w", err)
		}
	}
	if p.FlowProgressed != nil {
		if err := p.FlowProgressed.IsValid(); err != nil {
			return fmt.Errorf("field FlowProgressed not valid, %w", err)
		}
	}
	if p.FlowResult != nil {
		if err := p.FlowResult.IsValid(); err != nil {
			return fmt.Errorf("field FlowResult not valid, %w", err)
		}
	}
	if p.TraceDocumentBound != nil {
		if err := p.TraceDocumentBound.IsValid(); err != nil {
			return fmt.Errorf("field TraceDocumentBound not valid, %w", err)
		}
	}
	if p.TraceSyncStarted != nil {
		if err := p.TraceSyncStarted.IsValid(); err != nil {
			return fmt.Errorf("field TraceSyncStarted not valid, %w", err)
		}
	}
	if p.TraceSynced != nil {
		if err := p.TraceSynced.IsValid(); err != nil {
			return fmt.Errorf("field TraceSynced not valid, %w", err)
		}
	}
	return nil
}
