// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package verifyidl

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/zeefan1555/fanloop/internal/idl/erroridl"
	"strings"
)

type VerificationOutcome int64

const (
	VerificationOutcome_unspecified VerificationOutcome = 0
	VerificationOutcome_passed      VerificationOutcome = 1
	VerificationOutcome_failed      VerificationOutcome = 2
	VerificationOutcome_blocked     VerificationOutcome = 3
)

func (p VerificationOutcome) String() string {
	switch p {
	case VerificationOutcome_unspecified:
		return "unspecified"
	case VerificationOutcome_passed:
		return "passed"
	case VerificationOutcome_failed:
		return "failed"
	case VerificationOutcome_blocked:
		return "blocked"
	}
	return "<UNSET>"
}

func VerificationOutcomeFromString(s string) (VerificationOutcome, error) {
	switch s {
	case "unspecified":
		return VerificationOutcome_unspecified, nil
	case "passed":
		return VerificationOutcome_passed, nil
	case "failed":
		return VerificationOutcome_failed, nil
	case "blocked":
		return VerificationOutcome_blocked, nil
	}
	return VerificationOutcome(0), fmt.Errorf("not a valid VerificationOutcome string")
}

func VerificationOutcomePtr(v VerificationOutcome) *VerificationOutcome { return &v }

func (p VerificationOutcome) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *VerificationOutcome) UnmarshalText(text []byte) error {
	q, err := VerificationOutcomeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *VerificationOutcome) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = VerificationOutcome(result.Int64)
	return
}

func (p *VerificationOutcome) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type VerificationCheckStatus int64

const (
	VerificationCheckStatus_unspecified VerificationCheckStatus = 0
	VerificationCheckStatus_passed      VerificationCheckStatus = 1
	VerificationCheckStatus_failed      VerificationCheckStatus = 2
	VerificationCheckStatus_skipped     VerificationCheckStatus = 3
)

func (p VerificationCheckStatus) String() string {
	switch p {
	case VerificationCheckStatus_unspecified:
		return "unspecified"
	case VerificationCheckStatus_passed:
		return "passed"
	case VerificationCheckStatus_failed:
		return "failed"
	case VerificationCheckStatus_skipped:
		return "skipped"
	}
	return "<UNSET>"
}

func VerificationCheckStatusFromString(s string) (VerificationCheckStatus, error) {
	switch s {
	case "unspecified":
		return VerificationCheckStatus_unspecified, nil
	case "passed":
		return VerificationCheckStatus_passed, nil
	case "failed":
		return VerificationCheckStatus_failed, nil
	case "skipped":
		return VerificationCheckStatus_skipped, nil
	}
	return VerificationCheckStatus(0), fmt.Errorf("not a valid VerificationCheckStatus string")
}

func VerificationCheckStatusPtr(v VerificationCheckStatus) *VerificationCheckStatus { return &v }

func (p VerificationCheckStatus) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *VerificationCheckStatus) UnmarshalText(text []byte) error {
	q, err := VerificationCheckStatusFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *VerificationCheckStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = VerificationCheckStatus(result.Int64)
	return
}

func (p *VerificationCheckStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type VerificationCheck struct {
	Id          string                  `thrift:"id,1,required" json:"id"`
	Status      VerificationCheckStatus `thrift:"status,2,required,VerificationCheckStatus" json:"status"`
	Summary     string                  `thrift:"summary,3,required" json:"summary"`
	EvidenceRef *string                 `thrift:"evidence_ref,4,optional" json:"evidence_ref,omitempty"`
	Hint        *string                 `thrift:"hint,5,optional" json:"hint,omitempty"`
}

func NewVerificationCheck() *VerificationCheck {
	return &VerificationCheck{}
}

func (p *VerificationCheck) InitDefault() {
}

func (p *VerificationCheck) GetId() (v string) {
	return p.Id
}

func (p *VerificationCheck) GetStatus() (v VerificationCheckStatus) {
	return p.Status
}

func (p *VerificationCheck) GetSummary() (v string) {
	return p.Summary
}

var VerificationCheck_EvidenceRef_DEFAULT string

func (p *VerificationCheck) GetEvidenceRef() (v string) {
	if !p.IsSetEvidenceRef() {
		return VerificationCheck_EvidenceRef_DEFAULT
	}
	return *p.EvidenceRef
}

var VerificationCheck_Hint_DEFAULT string

func (p *VerificationCheck) GetHint() (v string) {
	if !p.IsSetHint() {
		return VerificationCheck_Hint_DEFAULT
	}
	return *p.Hint
}

func (p *VerificationCheck) IsSetEvidenceRef() bool {
	return p.EvidenceRef != nil
}

func (p *VerificationCheck) IsSetHint() bool {
	return p.Hint != nil
}

func (p *VerificationCheck) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerificationCheck(%+v)", *p)
}

func (p *VerificationCheck) DeepEqual(ano *VerificationCheck) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.Status) {
		return false
	}
	if !p.Field3DeepEqual(ano.Summary) {
		return false
	}
	if !p.Field4DeepEqual(ano.EvidenceRef) {
		return false
	}
	if !p.Field5DeepEqual(ano.Hint) {
		return false
	}
	return true
}

func (p *VerificationCheck) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *VerificationCheck) Field2DeepEqual(src VerificationCheckStatus) bool {

	if p.Status != src {
		return false
	}
	return true
}
func (p *VerificationCheck) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Summary, src) != 0 {
		return false
	}
	return true
}
func (p *VerificationCheck) Field4DeepEqual(src *string) bool {

	if p.EvidenceRef == src {
		return true
	} else if p.EvidenceRef == nil || src == nil {
		return false
	}
	if strings.Compare(*p.EvidenceRef, *src) != 0 {
		return false
	}
	return true
}
func (p *VerificationCheck) Field5DeepEqual(src *string) bool {

	if p.Hint == src {
		return true
	} else if p.Hint == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Hint, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_VerificationCheck = map[int16]string{
	1: "id",
	2: "status",
	3: "summary",
	4: "evidence_ref",
	5: "hint",
}

type VerifyDoctorRequest struct {
}

func NewVerifyDoctorRequest() *VerifyDoctorRequest {
	return &VerifyDoctorRequest{}
}

func (p *VerifyDoctorRequest) InitDefault() {
}

func (p *VerifyDoctorRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyDoctorRequest(%+v)", *p)
}

func (p *VerifyDoctorRequest) DeepEqual(ano *VerifyDoctorRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

var fieldIDToName_VerifyDoctorRequest = map[int16]string{}

type VerifyDoctorResponse struct {
	Outcome VerificationOutcome  `thrift:"outcome,1,required,VerificationOutcome" json:"outcome"`
	Checks  []*VerificationCheck `thrift:"checks,2,required,list<VerificationCheck>" json:"checks"`
}

func NewVerifyDoctorResponse() *VerifyDoctorResponse {
	return &VerifyDoctorResponse{}
}

func (p *VerifyDoctorResponse) InitDefault() {
}

func (p *VerifyDoctorResponse) GetOutcome() (v VerificationOutcome) {
	return p.Outcome
}

func (p *VerifyDoctorResponse) GetChecks() (v []*VerificationCheck) {
	return p.Checks
}

func (p *VerifyDoctorResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyDoctorResponse(%+v)", *p)
}

func (p *VerifyDoctorResponse) DeepEqual(ano *VerifyDoctorResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Outcome) {
		return false
	}
	if !p.Field2DeepEqual(ano.Checks) {
		return false
	}
	return true
}

func (p *VerifyDoctorResponse) Field1DeepEqual(src VerificationOutcome) bool {

	if p.Outcome != src {
		return false
	}
	return true
}
func (p *VerifyDoctorResponse) Field2DeepEqual(src []*VerificationCheck) bool {

	if len(p.Checks) != len(src) {
		return false
	}
	for i, v := range p.Checks {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_VerifyDoctorResponse = map[int16]string{
	1: "outcome",
	2: "checks",
}

type VerifySmokeRequest struct {
	EvidenceDir *string `thrift:"evidence_dir,1,optional" json:"evidence_dir,omitempty"`
}

func NewVerifySmokeRequest() *VerifySmokeRequest {
	return &VerifySmokeRequest{}
}

func (p *VerifySmokeRequest) InitDefault() {
}

var VerifySmokeRequest_EvidenceDir_DEFAULT string

func (p *VerifySmokeRequest) GetEvidenceDir() (v string) {
	if !p.IsSetEvidenceDir() {
		return VerifySmokeRequest_EvidenceDir_DEFAULT
	}
	return *p.EvidenceDir
}

func (p *VerifySmokeRequest) IsSetEvidenceDir() bool {
	return p.EvidenceDir != nil
}

func (p *VerifySmokeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifySmokeRequest(%+v)", *p)
}

func (p *VerifySmokeRequest) DeepEqual(ano *VerifySmokeRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.EvidenceDir) {
		return false
	}
	return true
}

func (p *VerifySmokeRequest) Field1DeepEqual(src *string) bool {

	if p.EvidenceDir == src {
		return true
	} else if p.EvidenceDir == nil || src == nil {
		return false
	}
	if strings.Compare(*p.EvidenceDir, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_VerifySmokeRequest = map[int16]string{
	1: "evidence_dir",
}

type VerifySmokeResponse struct {
	Outcome         VerificationOutcome  `thrift:"outcome,1,required,VerificationOutcome" json:"outcome"`
	RunId           string               `thrift:"run_id,2,required" json:"run_id"`
	EvidenceDir     string               `thrift:"evidence_dir,3,required" json:"evidence_dir"`
	ReleaseVersion  string               `thrift:"release_version,4,required" json:"release_version"`
	CommitSha       string               `thrift:"commit_sha,5,required" json:"commit_sha"`
	BinarySha256    string               `thrift:"binary_sha256,6,required" json:"binary_sha256"`
	Checks          []*VerificationCheck `thrift:"checks,7,required,list<VerificationCheck>" json:"checks"`
	CleanupComplete bool                 `thrift:"cleanup_complete,8,required" json:"cleanup_complete"`
}

func NewVerifySmokeResponse() *VerifySmokeResponse {
	return &VerifySmokeResponse{}
}

func (p *VerifySmokeResponse) InitDefault() {
}

func (p *VerifySmokeResponse) GetOutcome() (v VerificationOutcome) {
	return p.Outcome
}

func (p *VerifySmokeResponse) GetRunId() (v string) {
	return p.RunId
}

func (p *VerifySmokeResponse) GetEvidenceDir() (v string) {
	return p.EvidenceDir
}

func (p *VerifySmokeResponse) GetReleaseVersion() (v string) {
	return p.ReleaseVersion
}

func (p *VerifySmokeResponse) GetCommitSha() (v string) {
	return p.CommitSha
}

func (p *VerifySmokeResponse) GetBinarySha256() (v string) {
	return p.BinarySha256
}

func (p *VerifySmokeResponse) GetChecks() (v []*VerificationCheck) {
	return p.Checks
}

func (p *VerifySmokeResponse) GetCleanupComplete() (v bool) {
	return p.CleanupComplete
}

func (p *VerifySmokeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifySmokeResponse(%+v)", *p)
}

func (p *VerifySmokeResponse) DeepEqual(ano *VerifySmokeResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Outcome) {
		return false
	}
	if !p.Field2DeepEqual(ano.RunId) {
		return false
	}
	if !p.Field3DeepEqual(ano.EvidenceDir) {
		return false
	}
	if !p.Field4DeepEqual(ano.ReleaseVersion) {
		return false
	}
	if !p.Field5DeepEqual(ano.CommitSha) {
		return false
	}
	if !p.Field6DeepEqual(ano.BinarySha256) {
		return false
	}
	if !p.Field7DeepEqual(ano.Checks) {
		return false
	}
	if !p.Field8DeepEqual(ano.CleanupComplete) {
		return false
	}
	return true
}

func (p *VerifySmokeResponse) Field1DeepEqual(src VerificationOutcome) bool {

	if p.Outcome != src {
		return false
	}
	return true
}
func (p *VerifySmokeResponse) Field2DeepEqual(src string) bool {

	if strings.Compare(p.RunId, src) != 0 {
		return false
	}
	return true
}
func (p *VerifySmokeResponse) Field3DeepEqual(src string) bool {

	if strings.Compare(p.EvidenceDir, src) != 0 {
		return false
	}
	return true
}
func (p *VerifySmokeResponse) Field4DeepEqual(src string) bool {

	if strings.Compare(p.ReleaseVersion, src) != 0 {
		return false
	}
	return true
}
func (p *VerifySmokeResponse) Field5DeepEqual(src string) bool {

	if strings.Compare(p.CommitSha, src) != 0 {
		return false
	}
	return true
}
func (p *VerifySmokeResponse) Field6DeepEqual(src string) bool {

	if strings.Compare(p.BinarySha256, src) != 0 {
		return false
	}
	return true
}
func (p *VerifySmokeResponse) Field7DeepEqual(src []*VerificationCheck) bool {

	if len(p.Checks) != len(src) {
		return false
	}
	for i, v := range p.Checks {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *VerifySmokeResponse) Field8DeepEqual(src bool) bool {

	if p.CleanupComplete != src {
		return false
	}
	return true
}

var fieldIDToName_VerifySmokeResponse = map[int16]string{
	1: "outcome",
	2: "run_id",
	3: "evidence_dir",
	4: "release_version",
	5: "commit_sha",
	6: "binary_sha256",
	7: "checks",
	8: "cleanup_complete",
}

type VerifySnapshotRequest struct {
	EvidenceDir *string `thrift:"evidence_dir,1,optional" json:"evidence_dir,omitempty"`
}

func NewVerifySnapshotRequest() *VerifySnapshotRequest {
	return &VerifySnapshotRequest{}
}

func (p *VerifySnapshotRequest) InitDefault() {
}

var VerifySnapshotRequest_EvidenceDir_DEFAULT string

func (p *VerifySnapshotRequest) GetEvidenceDir() (v string) {
	if !p.IsSetEvidenceDir() {
		return VerifySnapshotRequest_EvidenceDir_DEFAULT
	}
	return *p.EvidenceDir
}

func (p *VerifySnapshotRequest) IsSetEvidenceDir() bool {
	return p.EvidenceDir != nil
}

func (p *VerifySnapshotRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifySnapshotRequest(%+v)", *p)
}

func (p *VerifySnapshotRequest) DeepEqual(ano *VerifySnapshotRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.EvidenceDir) {
		return false
	}
	return true
}

func (p *VerifySnapshotRequest) Field1DeepEqual(src *string) bool {

	if p.EvidenceDir == src {
		return true
	} else if p.EvidenceDir == nil || src == nil {
		return false
	}
	if strings.Compare(*p.EvidenceDir, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_VerifySnapshotRequest = map[int16]string{
	1: "evidence_dir",
}

type VerifySnapshotResponse struct {
	SnapshotDir string   `thrift:"snapshot_dir,1,required" json:"snapshot_dir"`
	Files       []string `thrift:"files,2,required,list<string>" json:"files"`
}

func NewVerifySnapshotResponse() *VerifySnapshotResponse {
	return &VerifySnapshotResponse{}
}

func (p *VerifySnapshotResponse) InitDefault() {
}

func (p *VerifySnapshotResponse) GetSnapshotDir() (v string) {
	return p.SnapshotDir
}

func (p *VerifySnapshotResponse) GetFiles() (v []string) {
	return p.Files
}

func (p *VerifySnapshotResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifySnapshotResponse(%+v)", *p)
}

func (p *VerifySnapshotResponse) DeepEqual(ano *VerifySnapshotResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SnapshotDir) {
		return false
	}
	if !p.Field2DeepEqual(ano.Files) {
		return false
	}
	return true
}

func (p *VerifySnapshotResponse) Field1DeepEqual(src string) bool {

	if strings.Compare(p.SnapshotDir, src) != 0 {
		return false
	}
	return true
}
func (p *VerifySnapshotResponse) Field2DeepEqual(src []string) bool {

	if len(p.Files) != len(src) {
		return false
	}
	for i, v := range p.Files {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}

var fieldIDToName_VerifySnapshotResponse = map[int16]string{
	1: "snapshot_dir",
	2: "files",
}

type VerifyCleanupRequest struct {
	RunId string `thrift:"run_id,1,required" json:"run_id"`
}

func NewVerifyCleanupRequest() *VerifyCleanupRequest {
	return &VerifyCleanupRequest{}
}

func (p *VerifyCleanupRequest) InitDefault() {
}

func (p *VerifyCleanupRequest) GetRunId() (v string) {
	return p.RunId
}

func (p *VerifyCleanupRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyCleanupRequest(%+v)", *p)
}

func (p *VerifyCleanupRequest) DeepEqual(ano *VerifyCleanupRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RunId) {
		return false
	}
	return true
}

func (p *VerifyCleanupRequest) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RunId, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_VerifyCleanupRequest = map[int16]string{
	1: "run_id",
}

type VerifyCleanupResponse struct {
	RunId   string   `thrift:"run_id,1,required" json:"run_id"`
	Paths   []string `thrift:"paths,2,required,list<string>" json:"paths"`
	Removed bool     `thrift:"removed,3,required" json:"removed"`
}

func NewVerifyCleanupResponse() *VerifyCleanupResponse {
	return &VerifyCleanupResponse{}
}

func (p *VerifyCleanupResponse) InitDefault() {
}

func (p *VerifyCleanupResponse) GetRunId() (v string) {
	return p.RunId
}

func (p *VerifyCleanupResponse) GetPaths() (v []string) {
	return p.Paths
}

func (p *VerifyCleanupResponse) GetRemoved() (v bool) {
	return p.Removed
}

func (p *VerifyCleanupResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyCleanupResponse(%+v)", *p)
}

func (p *VerifyCleanupResponse) DeepEqual(ano *VerifyCleanupResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RunId) {
		return false
	}
	if !p.Field2DeepEqual(ano.Paths) {
		return false
	}
	if !p.Field3DeepEqual(ano.Removed) {
		return false
	}
	return true
}

func (p *VerifyCleanupResponse) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RunId, src) != 0 {
		return false
	}
	return true
}
func (p *VerifyCleanupResponse) Field2DeepEqual(src []string) bool {

	if len(p.Paths) != len(src) {
		return false
	}
	for i, v := range p.Paths {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *VerifyCleanupResponse) Field3DeepEqual(src bool) bool {

	if p.Removed != src {
		return false
	}
	return true
}

var fieldIDToName_VerifyCleanupResponse = map[int16]string{
	1: "run_id",
	2: "paths",
	3: "removed",
}

type VerifyService interface {
	Doctor(ctx context.Context, request *VerifyDoctorRequest) (r *VerifyDoctorResponse, err error)

	Smoke(ctx context.Context, request *VerifySmokeRequest) (r *VerifySmokeResponse, err error)

	Snapshot(ctx context.Context, requirementRoot string, request *VerifySnapshotRequest) (r *VerifySnapshotResponse, err error)

	Cleanup(ctx context.Context, dryRun bool, request *VerifyCleanupRequest) (r *VerifyCleanupResponse, err error)
}

type VerifyServiceDoctorArgs struct {
	Request *VerifyDoctorRequest `thrift:"request,1,required" json:"request"`
}

func NewVerifyServiceDoctorArgs() *VerifyServiceDoctorArgs {
	return &VerifyServiceDoctorArgs{}
}

func (p *VerifyServiceDoctorArgs) InitDefault() {
}

var VerifyServiceDoctorArgs_Request_DEFAULT *VerifyDoctorRequest

func (p *VerifyServiceDoctorArgs) GetRequest() (v *VerifyDoctorRequest) {
	if !p.IsSetRequest() {
		return VerifyServiceDoctorArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *VerifyServiceDoctorArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VerifyServiceDoctorArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyServiceDoctorArgs(%+v)", *p)
}

func (p *VerifyServiceDoctorArgs) DeepEqual(ano *VerifyServiceDoctorArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Request) {
		return false
	}
	return true
}

func (p *VerifyServiceDoctorArgs) Field1DeepEqual(src *VerifyDoctorRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_VerifyServiceDoctorArgs = map[int16]string{
	1: "request",
}

type VerifyServiceDoctorResult struct {
	Success *VerifyDoctorResponse `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewVerifyServiceDoctorResult() *VerifyServiceDoctorResult {
	return &VerifyServiceDoctorResult{}
}

func (p *VerifyServiceDoctorResult) InitDefault() {
}

var VerifyServiceDoctorResult_Success_DEFAULT *VerifyDoctorResponse

func (p *VerifyServiceDoctorResult) GetSuccess() (v *VerifyDoctorResponse) {
	if !p.IsSetSuccess() {
		return VerifyServiceDoctorResult_Success_DEFAULT
	}
	return p.Success
}

var VerifyServiceDoctorResult_Error_DEFAULT *erroridl.PublicError

func (p *VerifyServiceDoctorResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return VerifyServiceDoctorResult_Error_DEFAULT
	}
	return p.Error
}

func (p *VerifyServiceDoctorResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerifyServiceDoctorResult) IsSetError() bool {
	return p.Error != nil
}

func (p *VerifyServiceDoctorResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyServiceDoctorResult(%+v)", *p)
}

func (p *VerifyServiceDoctorResult) DeepEqual(ano *VerifyServiceDoctorResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *VerifyServiceDoctorResult) Field0DeepEqual(src *VerifyDoctorResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *VerifyServiceDoctorResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_VerifyServiceDoctorResult = map[int16]string{
	0: "success",
	1: "error",
}

type VerifyServiceSmokeArgs struct {
	Request *VerifySmokeRequest `thrift:"request,1,required" json:"request"`
}

func NewVerifyServiceSmokeArgs() *VerifyServiceSmokeArgs {
	return &VerifyServiceSmokeArgs{}
}

func (p *VerifyServiceSmokeArgs) InitDefault() {
}

var VerifyServiceSmokeArgs_Request_DEFAULT *VerifySmokeRequest

func (p *VerifyServiceSmokeArgs) GetRequest() (v *VerifySmokeRequest) {
	if !p.IsSetRequest() {
		return VerifyServiceSmokeArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *VerifyServiceSmokeArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VerifyServiceSmokeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyServiceSmokeArgs(%+v)", *p)
}

func (p *VerifyServiceSmokeArgs) DeepEqual(ano *VerifyServiceSmokeArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Request) {
		return false
	}
	return true
}

func (p *VerifyServiceSmokeArgs) Field1DeepEqual(src *VerifySmokeRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_VerifyServiceSmokeArgs = map[int16]string{
	1: "request",
}

type VerifyServiceSmokeResult struct {
	Success *VerifySmokeResponse  `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewVerifyServiceSmokeResult() *VerifyServiceSmokeResult {
	return &VerifyServiceSmokeResult{}
}

func (p *VerifyServiceSmokeResult) InitDefault() {
}

var VerifyServiceSmokeResult_Success_DEFAULT *VerifySmokeResponse

func (p *VerifyServiceSmokeResult) GetSuccess() (v *VerifySmokeResponse) {
	if !p.IsSetSuccess() {
		return VerifyServiceSmokeResult_Success_DEFAULT
	}
	return p.Success
}

var VerifyServiceSmokeResult_Error_DEFAULT *erroridl.PublicError

func (p *VerifyServiceSmokeResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return VerifyServiceSmokeResult_Error_DEFAULT
	}
	return p.Error
}

func (p *VerifyServiceSmokeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerifyServiceSmokeResult) IsSetError() bool {
	return p.Error != nil
}

func (p *VerifyServiceSmokeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyServiceSmokeResult(%+v)", *p)
}

func (p *VerifyServiceSmokeResult) DeepEqual(ano *VerifyServiceSmokeResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *VerifyServiceSmokeResult) Field0DeepEqual(src *VerifySmokeResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *VerifyServiceSmokeResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_VerifyServiceSmokeResult = map[int16]string{
	0: "success",
	1: "error",
}

type VerifyServiceSnapshotArgs struct {
	RequirementRoot string                 `thrift:"requirement_root,1" json:"requirement_root"`
	Request         *VerifySnapshotRequest `thrift:"request,2,required" json:"request"`
}

func NewVerifyServiceSnapshotArgs() *VerifyServiceSnapshotArgs {
	return &VerifyServiceSnapshotArgs{}
}

func (p *VerifyServiceSnapshotArgs) InitDefault() {
}

func (p *VerifyServiceSnapshotArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var VerifyServiceSnapshotArgs_Request_DEFAULT *VerifySnapshotRequest

func (p *VerifyServiceSnapshotArgs) GetRequest() (v *VerifySnapshotRequest) {
	if !p.IsSetRequest() {
		return VerifyServiceSnapshotArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *VerifyServiceSnapshotArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VerifyServiceSnapshotArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyServiceSnapshotArgs(%+v)", *p)
}

func (p *VerifyServiceSnapshotArgs) DeepEqual(ano *VerifyServiceSnapshotArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	return true
}

func (p *VerifyServiceSnapshotArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *VerifyServiceSnapshotArgs) Field2DeepEqual(src *VerifySnapshotRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_VerifyServiceSnapshotArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
}

type VerifyServiceSnapshotResult struct {
	Success *VerifySnapshotResponse `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError   `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewVerifyServiceSnapshotResult() *VerifyServiceSnapshotResult {
	return &VerifyServiceSnapshotResult{}
}

func (p *VerifyServiceSnapshotResult) InitDefault() {
}

var VerifyServiceSnapshotResult_Success_DEFAULT *VerifySnapshotResponse

func (p *VerifyServiceSnapshotResult) GetSuccess() (v *VerifySnapshotResponse) {
	if !p.IsSetSuccess() {
		return VerifyServiceSnapshotResult_Success_DEFAULT
	}
	return p.Success
}

var VerifyServiceSnapshotResult_Error_DEFAULT *erroridl.PublicError

func (p *VerifyServiceSnapshotResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return VerifyServiceSnapshotResult_Error_DEFAULT
	}
	return p.Error
}

func (p *VerifyServiceSnapshotResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerifyServiceSnapshotResult) IsSetError() bool {
	return p.Error != nil
}

func (p *VerifyServiceSnapshotResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyServiceSnapshotResult(%+v)", *p)
}

func (p *VerifyServiceSnapshotResult) DeepEqual(ano *VerifyServiceSnapshotResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *VerifyServiceSnapshotResult) Field0DeepEqual(src *VerifySnapshotResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *VerifyServiceSnapshotResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_VerifyServiceSnapshotResult = map[int16]string{
	0: "success",
	1: "error",
}

type VerifyServiceCleanupArgs struct {
	DryRun  bool                  `thrift:"dry_run,1" json:"dry_run"`
	Request *VerifyCleanupRequest `thrift:"request,2,required" json:"request"`
}

func NewVerifyServiceCleanupArgs() *VerifyServiceCleanupArgs {
	return &VerifyServiceCleanupArgs{}
}

func (p *VerifyServiceCleanupArgs) InitDefault() {
}

func (p *VerifyServiceCleanupArgs) GetDryRun() (v bool) {
	return p.DryRun
}

var VerifyServiceCleanupArgs_Request_DEFAULT *VerifyCleanupRequest

func (p *VerifyServiceCleanupArgs) GetRequest() (v *VerifyCleanupRequest) {
	if !p.IsSetRequest() {
		return VerifyServiceCleanupArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *VerifyServiceCleanupArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *VerifyServiceCleanupArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyServiceCleanupArgs(%+v)", *p)
}

func (p *VerifyServiceCleanupArgs) DeepEqual(ano *VerifyServiceCleanupArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.DryRun) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	return true
}

func (p *VerifyServiceCleanupArgs) Field1DeepEqual(src bool) bool {

	if p.DryRun != src {
		return false
	}
	return true
}
func (p *VerifyServiceCleanupArgs) Field2DeepEqual(src *VerifyCleanupRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_VerifyServiceCleanupArgs = map[int16]string{
	1: "dry_run",
	2: "request",
}

type VerifyServiceCleanupResult struct {
	Success *VerifyCleanupResponse `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError  `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewVerifyServiceCleanupResult() *VerifyServiceCleanupResult {
	return &VerifyServiceCleanupResult{}
}

func (p *VerifyServiceCleanupResult) InitDefault() {
}

var VerifyServiceCleanupResult_Success_DEFAULT *VerifyCleanupResponse

func (p *VerifyServiceCleanupResult) GetSuccess() (v *VerifyCleanupResponse) {
	if !p.IsSetSuccess() {
		return VerifyServiceCleanupResult_Success_DEFAULT
	}
	return p.Success
}

var VerifyServiceCleanupResult_Error_DEFAULT *erroridl.PublicError

func (p *VerifyServiceCleanupResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return VerifyServiceCleanupResult_Error_DEFAULT
	}
	return p.Error
}

func (p *VerifyServiceCleanupResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VerifyServiceCleanupResult) IsSetError() bool {
	return p.Error != nil
}

func (p *VerifyServiceCleanupResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyServiceCleanupResult(%+v)", *p)
}

func (p *VerifyServiceCleanupResult) DeepEqual(ano *VerifyServiceCleanupResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *VerifyServiceCleanupResult) Field0DeepEqual(src *VerifyCleanupResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *VerifyServiceCleanupResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_VerifyServiceCleanupResult = map[int16]string{
	0: "success",
	1: "error",
}

// exceptions of methods in VerifyService.
var (
	_ error = (*erroridl.PublicError)(nil)
)
