// Code generated by Validator v0.2.5. DO NOT EDIT.

package verifyidl

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *VerificationCheck) IsValid() error {
	return nil
}
func (p *VerifyDoctorRequest) IsValid() error {
	return nil
}
func (p *VerifyDoctorResponse) IsValid() error {
	return nil
}
func (p *VerifySmokeRequest) IsValid() error {
	return nil
}
func (p *VerifySmokeResponse) IsValid() error {
	return nil
}
func (p *VerifySnapshotRequest) IsValid() error {
	return nil
}
func (p *VerifySnapshotResponse) IsValid() error {
	return nil
}
func (p *VerifyCleanupRequest) IsValid() error {
	return nil
}
func (p *VerifyCleanupResponse) IsValid() error {
	return nil
}
