// Code generated by Validator v0.2.5. DO NOT EDIT.

package releaseidl

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *CLIRelease) IsValid() error {
	_src := "^[0-9A-Za-z][0-9A-Za-z._+-]*$"
	if ok, _ := regexp.MatchString(_src, p.Version); !ok {
		return fmt.Errorf("field Version pattern rule failed, current value: %v", p.Version)
	}
	return nil
}
func (p *SkillArtifact) IsValid() error {
	_src := "^[a-z][a-z0-9-]*$"
	if ok, _ := regexp.MatchString(_src, p.Name); !ok {
		return fmt.Errorf("field Name pattern rule failed, current value: %v", p.Name)
	}
	_src1 := "^[0-9A-Za-z][0-9A-Za-z._+-]*$"
	if ok, _ := regexp.MatchString(_src1, p.Version); !ok {
		return fmt.Errorf("field Version pattern rule failed, current value: %v", p.Version)
	}
	if len(p.Path) < int(1) {
		return fmt.Errorf("field Path min_len rule failed, current value: %d", len(p.Path))
	}
	_src2 := "^sha256:[0-9a-f]{64}$"
	if ok, _ := regexp.MatchString(_src2, p.Sha256); !ok {
		return fmt.Errorf("field Sha256 pattern rule failed, current value: %v", p.Sha256)
	}
	return nil
}
func (p *WorkflowArtifact) IsValid() error {
	_src := "^[a-z][a-z0-9-]*$"
	if ok, _ := regexp.MatchString(_src, p.Id); !ok {
		return fmt.Errorf("field Id pattern rule failed, current value: %v", p.Id)
	}
	if len(p.Path) < int(1) {
		return fmt.Errorf("field Path min_len rule failed, current value: %d", len(p.Path))
	}
	_src1 := "^sha256:[0-9a-f]{64}$"
	if ok, _ := regexp.MatchString(_src1, p.Sha256); !ok {
		return fmt.Errorf("field Sha256 pattern rule failed, current value: %v", p.Sha256)
	}
	return nil
}
func (p *PlatformAsset) IsValid() error {
	_src := "^(darwin|linux)$"
	if ok, _ := regexp.MatchString(_src, p.Os); !ok {
		return fmt.Errorf("field Os pattern rule failed, current value: %v", p.Os)
	}
	_src1 := "^(amd64|arm64)$"
	if ok, _ := regexp.MatchString(_src1, p.Arch); !ok {
		return fmt.Errorf("field Arch pattern rule failed, current value: %v", p.Arch)
	}
	if len(p.File) < int(1) {
		return fmt.Errorf("field File min_len rule failed, current value: %d", len(p.File))
	}
	_src2 := "^sha256:[0-9a-f]{64}$"
	if ok, _ := regexp.MatchString(_src2, p.Sha256); !ok {
		return fmt.Errorf("field Sha256 pattern rule failed, current value: %v", p.Sha256)
	}
	_src3 := "^sha256:[0-9a-f]{64}$"
	if ok, _ := regexp.MatchString(_src3, p.BinarySha256); !ok {
		return fmt.Errorf("field BinarySha256 pattern rule failed, current value: %v", p.BinarySha256)
	}
	return nil
}
func (p *ReleaseManifest) IsValid() error {
	if p.SchemaVersion != int32(2) {
		return fmt.Errorf("field SchemaVersion not match const value, current value: %v", p.SchemaVersion)
	}
	_src := "^[0-9A-Za-z][0-9A-Za-z._+-]*$"
	if ok, _ := regexp.MatchString(_src, p.ReleaseVersion); !ok {
		return fmt.Errorf("field ReleaseVersion pattern rule failed, current value: %v", p.ReleaseVersion)
	}
	if p.Cli == nil {
		return fmt.Errorf("field Cli not_nil rule failed")
	}
	if err := p.Cli.IsValid(); err != nil {
		return fmt.Errorf("field Cli not valid, %w", err)
	}
	if p.StateSchema == nil {
		return fmt.Errorf("field StateSchema not_nil rule failed")
	}
	if err := p.StateSchema.IsValid(); err != nil {
		return fmt.Errorf("field StateSchema not valid, %w", err)
	}
	if len(p.Skills) < int(1) {
		return fmt.Errorf("field Skills MinLen rule failed, current value: %v", p.Skills)
	}
	if len(p.Workflows) < int(1) {
		return fmt.Errorf("field Workflows MinLen rule failed, current value: %v", p.Workflows)
	}
	if len(p.Assets) < int(4) {
		return fmt.Errorf("field Assets MinLen rule failed, current value: %v", p.Assets)
	}
	if len(p.Assets) > int(4) {
		return fmt.Errorf("field Assets MaxLen rule failed, current value: %v", p.Assets)
	}
	return nil
}
