// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package releaseidl

import (
	"fmt"
	"github.com/zeefan1555/commonloop/internal/idl/opsidl"
	"strings"
)

const (
	RELEASE_MANIFEST_SCHEMA_VERSION = 2
)

type CLIRelease struct {
	Version string `thrift:"version,1,required" json:"version"`
}

func NewCLIRelease() *CLIRelease {
	return &CLIRelease{}
}

func (p *CLIRelease) InitDefault() {
}

func (p *CLIRelease) GetVersion() (v string) {
	return p.Version
}

func (p *CLIRelease) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CLIRelease(%+v)", *p)
}

func (p *CLIRelease) DeepEqual(ano *CLIRelease) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Version) {
		return false
	}
	return true
}

func (p *CLIRelease) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Version, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_CLIRelease = map[int16]string{
	1: "version",
}

type SkillArtifact struct {
	Name    string `thrift:"name,1,required" json:"name"`
	Version string `thrift:"version,2,required" json:"version"`
	Path    string `thrift:"path,3,required" json:"path"`
	Sha256  string `thrift:"sha256,4,required" json:"sha256"`
}

func NewSkillArtifact() *SkillArtifact {
	return &SkillArtifact{}
}

func (p *SkillArtifact) InitDefault() {
}

func (p *SkillArtifact) GetName() (v string) {
	return p.Name
}

func (p *SkillArtifact) GetVersion() (v string) {
	return p.Version
}

func (p *SkillArtifact) GetPath() (v string) {
	return p.Path
}

func (p *SkillArtifact) GetSha256() (v string) {
	return p.Sha256
}

func (p *SkillArtifact) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SkillArtifact(%+v)", *p)
}

func (p *SkillArtifact) DeepEqual(ano *SkillArtifact) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Name) {
		return false
	}
	if !p.Field2DeepEqual(ano.Version) {
		return false
	}
	if !p.Field3DeepEqual(ano.Path) {
		return false
	}
	if !p.Field4DeepEqual(ano.Sha256) {
		return false
	}
	return true
}

func (p *SkillArtifact) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Name, src) != 0 {
		return false
	}
	return true
}
func (p *SkillArtifact) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Version, src) != 0 {
		return false
	}
	return true
}
func (p *SkillArtifact) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Path, src) != 0 {
		return false
	}
	return true
}
func (p *SkillArtifact) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Sha256, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_SkillArtifact = map[int16]string{
	1: "name",
	2: "version",
	3: "path",
	4: "sha256",
}

type WorkflowArtifact struct {
	Id string `thrift:"id,1,required" json:"id"`
	// fields 2 and 3 retired: Workflow has no business version or default.
	Path   string `thrift:"path,4,required" json:"path"`
	Sha256 string `thrift:"sha256,5,required" json:"sha256"`
}

func NewWorkflowArtifact() *WorkflowArtifact {
	return &WorkflowArtifact{}
}

func (p *WorkflowArtifact) InitDefault() {
}

func (p *WorkflowArtifact) GetId() (v string) {
	return p.Id
}

func (p *WorkflowArtifact) GetPath() (v string) {
	return p.Path
}

func (p *WorkflowArtifact) GetSha256() (v string) {
	return p.Sha256
}

func (p *WorkflowArtifact) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WorkflowArtifact(%+v)", *p)
}

func (p *WorkflowArtifact) DeepEqual(ano *WorkflowArtifact) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field4DeepEqual(ano.Path) {
		return false
	}
	if !p.Field5DeepEqual(ano.Sha256) {
		return false
	}
	return true
}

func (p *WorkflowArtifact) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *WorkflowArtifact) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Path, src) != 0 {
		return false
	}
	return true
}
func (p *WorkflowArtifact) Field5DeepEqual(src string) bool {

	if strings.Compare(p.Sha256, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_WorkflowArtifact = map[int16]string{
	1: "id",
	4: "path",
	5: "sha256",
}

type PlatformAsset struct {
	Os           string `thrift:"os,1,required" json:"os"`
	Arch         string `thrift:"arch,2,required" json:"arch"`
	File         string `thrift:"file,3,required" json:"file"`
	Sha256       string `thrift:"sha256,4,required" json:"sha256"`
	BinarySha256 string `thrift:"binary_sha256,5,required" json:"binary_sha256"`
}

func NewPlatformAsset() *PlatformAsset {
	return &PlatformAsset{}
}

func (p *PlatformAsset) InitDefault() {
}

func (p *PlatformAsset) GetOs() (v string) {
	return p.Os
}

func (p *PlatformAsset) GetArch() (v string) {
	return p.Arch
}

func (p *PlatformAsset) GetFile() (v string) {
	return p.File
}

func (p *PlatformAsset) GetSha256() (v string) {
	return p.Sha256
}

func (p *PlatformAsset) GetBinarySha256() (v string) {
	return p.BinarySha256
}

func (p *PlatformAsset) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PlatformAsset(%+v)", *p)
}

func (p *PlatformAsset) DeepEqual(ano *PlatformAsset) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Os) {
		return false
	}
	if !p.Field2DeepEqual(ano.Arch) {
		return false
	}
	if !p.Field3DeepEqual(ano.File) {
		return false
	}
	if !p.Field4DeepEqual(ano.Sha256) {
		return false
	}
	if !p.Field5DeepEqual(ano.BinarySha256) {
		return false
	}
	return true
}

func (p *PlatformAsset) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Os, src) != 0 {
		return false
	}
	return true
}
func (p *PlatformAsset) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Arch, src) != 0 {
		return false
	}
	return true
}
func (p *PlatformAsset) Field3DeepEqual(src string) bool {

	if strings.Compare(p.File, src) != 0 {
		return false
	}
	return true
}
func (p *PlatformAsset) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Sha256, src) != 0 {
		return false
	}
	return true
}
func (p *PlatformAsset) Field5DeepEqual(src string) bool {

	if strings.Compare(p.BinarySha256, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_PlatformAsset = map[int16]string{
	1: "os",
	2: "arch",
	3: "file",
	4: "sha256",
	5: "binary_sha256",
}

type ReleaseManifest struct {
	SchemaVersion  int32                      `thrift:"schema_version,1,required" json:"schema_version"`
	ReleaseVersion string                     `thrift:"release_version,2,required" json:"release_version"`
	Cli            *CLIRelease                `thrift:"cli,3,required" json:"cli"`
	StateSchema    *opsidl.StateSchemaSupport `thrift:"state_schema,4,required" json:"state_schema"`
	Skills         []*SkillArtifact           `thrift:"skills,5,required,list<SkillArtifact>" json:"skills"`
	Workflows      []*WorkflowArtifact        `thrift:"workflows,6,required,list<WorkflowArtifact>" json:"workflows"`
	Assets         []*PlatformAsset           `thrift:"assets,7,required,list<PlatformAsset>" json:"assets"`
}

func NewReleaseManifest() *ReleaseManifest {
	return &ReleaseManifest{}
}

func (p *ReleaseManifest) InitDefault() {
}

func (p *ReleaseManifest) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

func (p *ReleaseManifest) GetReleaseVersion() (v string) {
	return p.ReleaseVersion
}

var ReleaseManifest_Cli_DEFAULT *CLIRelease

func (p *ReleaseManifest) GetCli() (v *CLIRelease) {
	if !p.IsSetCli() {
		return ReleaseManifest_Cli_DEFAULT
	}
	return p.Cli
}

var ReleaseManifest_StateSchema_DEFAULT *opsidl.StateSchemaSupport

func (p *ReleaseManifest) GetStateSchema() (v *opsidl.StateSchemaSupport) {
	if !p.IsSetStateSchema() {
		return ReleaseManifest_StateSchema_DEFAULT
	}
	return p.StateSchema
}

func (p *ReleaseManifest) GetSkills() (v []*SkillArtifact) {
	return p.Skills
}

func (p *ReleaseManifest) GetWorkflows() (v []*WorkflowArtifact) {
	return p.Workflows
}

func (p *ReleaseManifest) GetAssets() (v []*PlatformAsset) {
	return p.Assets
}

func (p *ReleaseManifest) IsSetCli() bool {
	return p.Cli != nil
}

func (p *ReleaseManifest) IsSetStateSchema() bool {
	return p.StateSchema != nil
}

func (p *ReleaseManifest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseManifest(%+v)", *p)
}

func (p *ReleaseManifest) DeepEqual(ano *ReleaseManifest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.ReleaseVersion) {
		return false
	}
	if !p.Field3DeepEqual(ano.Cli) {
		return false
	}
	if !p.Field4DeepEqual(ano.StateSchema) {
		return false
	}
	if !p.Field5DeepEqual(ano.Skills) {
		return false
	}
	if !p.Field6DeepEqual(ano.Workflows) {
		return false
	}
	if !p.Field7DeepEqual(ano.Assets) {
		return false
	}
	return true
}

func (p *ReleaseManifest) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *ReleaseManifest) Field2DeepEqual(src string) bool {

	if strings.Compare(p.ReleaseVersion, src) != 0 {
		return false
	}
	return true
}
func (p *ReleaseManifest) Field3DeepEqual(src *CLIRelease) bool {

	if !p.Cli.DeepEqual(src) {
		return false
	}
	return true
}
func (p *ReleaseManifest) Field4DeepEqual(src *opsidl.StateSchemaSupport) bool {

	if !p.StateSchema.DeepEqual(src) {
		return false
	}
	return true
}
func (p *ReleaseManifest) Field5DeepEqual(src []*SkillArtifact) bool {

	if len(p.Skills) != len(src) {
		return false
	}
	for i, v := range p.Skills {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *ReleaseManifest) Field6DeepEqual(src []*WorkflowArtifact) bool {

	if len(p.Workflows) != len(src) {
		return false
	}
	for i, v := range p.Workflows {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *ReleaseManifest) Field7DeepEqual(src []*PlatformAsset) bool {

	if len(p.Assets) != len(src) {
		return false
	}
	for i, v := range p.Assets {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_ReleaseManifest = map[int16]string{
	1: "schema_version",
	2: "release_version",
	3: "cli",
	4: "state_schema",
	5: "skills",
	6: "workflows",
	7: "assets",
}
