// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package traceidl

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/zeefan1555/commonloop/internal/idl/erroridl"
	"strings"
)

type TraceBindEffect int64

const (
	TraceBindEffect_unspecified TraceBindEffect = 0
	TraceBindEffect_bound       TraceBindEffect = 1
	TraceBindEffect_unchanged   TraceBindEffect = 2
)

func (p TraceBindEffect) String() string {
	switch p {
	case TraceBindEffect_unspecified:
		return "unspecified"
	case TraceBindEffect_bound:
		return "bound"
	case TraceBindEffect_unchanged:
		return "unchanged"
	}
	return "<UNSET>"
}

func TraceBindEffectFromString(s string) (TraceBindEffect, error) {
	switch s {
	case "unspecified":
		return TraceBindEffect_unspecified, nil
	case "bound":
		return TraceBindEffect_bound, nil
	case "unchanged":
		return TraceBindEffect_unchanged, nil
	}
	return TraceBindEffect(0), fmt.Errorf("not a valid TraceBindEffect string")
}

func TraceBindEffectPtr(v TraceBindEffect) *TraceBindEffect { return &v }

func (p TraceBindEffect) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TraceBindEffect) UnmarshalText(text []byte) error {
	q, err := TraceBindEffectFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TraceBindEffect) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TraceBindEffect(result.Int64)
	return
}

func (p *TraceBindEffect) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TraceSyncOutcome int64

const (
	TraceSyncOutcome_unspecified TraceSyncOutcome = 0
	TraceSyncOutcome_succeeded   TraceSyncOutcome = 1
	TraceSyncOutcome_partial     TraceSyncOutcome = 2
	TraceSyncOutcome_skipped     TraceSyncOutcome = 3
)

func (p TraceSyncOutcome) String() string {
	switch p {
	case TraceSyncOutcome_unspecified:
		return "unspecified"
	case TraceSyncOutcome_succeeded:
		return "succeeded"
	case TraceSyncOutcome_partial:
		return "partial"
	case TraceSyncOutcome_skipped:
		return "skipped"
	}
	return "<UNSET>"
}

func TraceSyncOutcomeFromString(s string) (TraceSyncOutcome, error) {
	switch s {
	case "unspecified":
		return TraceSyncOutcome_unspecified, nil
	case "succeeded":
		return TraceSyncOutcome_succeeded, nil
	case "partial":
		return TraceSyncOutcome_partial, nil
	case "skipped":
		return TraceSyncOutcome_skipped, nil
	}
	return TraceSyncOutcome(0), fmt.Errorf("not a valid TraceSyncOutcome string")
}

func TraceSyncOutcomePtr(v TraceSyncOutcome) *TraceSyncOutcome { return &v }

func (p TraceSyncOutcome) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TraceSyncOutcome) UnmarshalText(text []byte) error {
	q, err := TraceSyncOutcomeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TraceSyncOutcome) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TraceSyncOutcome(result.Int64)
	return
}

func (p *TraceSyncOutcome) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TraceTarget int64

const (
	TraceTarget_unspecified      TraceTarget = 0
	TraceTarget_trace_document   TraceTarget = 1
	TraceTarget_registry         TraceTarget = 2
	TraceTarget_cli_log_document TraceTarget = 3
)

func (p TraceTarget) String() string {
	switch p {
	case TraceTarget_unspecified:
		return "unspecified"
	case TraceTarget_trace_document:
		return "trace_document"
	case TraceTarget_registry:
		return "registry"
	case TraceTarget_cli_log_document:
		return "cli_log_document"
	}
	return "<UNSET>"
}

func TraceTargetFromString(s string) (TraceTarget, error) {
	switch s {
	case "unspecified":
		return TraceTarget_unspecified, nil
	case "trace_document":
		return TraceTarget_trace_document, nil
	case "registry":
		return TraceTarget_registry, nil
	case "cli_log_document":
		return TraceTarget_cli_log_document, nil
	}
	return TraceTarget(0), fmt.Errorf("not a valid TraceTarget string")
}

func TraceTargetPtr(v TraceTarget) *TraceTarget { return &v }

func (p TraceTarget) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TraceTarget) UnmarshalText(text []byte) error {
	q, err := TraceTargetFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TraceTarget) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TraceTarget(result.Int64)
	return
}

func (p *TraceTarget) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TraceTargetStatus int64

const (
	TraceTargetStatus_unspecified TraceTargetStatus = 0
	TraceTargetStatus_succeeded   TraceTargetStatus = 1
	TraceTargetStatus_failed      TraceTargetStatus = 2
	TraceTargetStatus_skipped     TraceTargetStatus = 3
)

func (p TraceTargetStatus) String() string {
	switch p {
	case TraceTargetStatus_unspecified:
		return "unspecified"
	case TraceTargetStatus_succeeded:
		return "succeeded"
	case TraceTargetStatus_failed:
		return "failed"
	case TraceTargetStatus_skipped:
		return "skipped"
	}
	return "<UNSET>"
}

func TraceTargetStatusFromString(s string) (TraceTargetStatus, error) {
	switch s {
	case "unspecified":
		return TraceTargetStatus_unspecified, nil
	case "succeeded":
		return TraceTargetStatus_succeeded, nil
	case "failed":
		return TraceTargetStatus_failed, nil
	case "skipped":
		return TraceTargetStatus_skipped, nil
	}
	return TraceTargetStatus(0), fmt.Errorf("not a valid TraceTargetStatus string")
}

func TraceTargetStatusPtr(v TraceTargetStatus) *TraceTargetStatus { return &v }

func (p TraceTargetStatus) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TraceTargetStatus) UnmarshalText(text []byte) error {
	q, err := TraceTargetStatusFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TraceTargetStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TraceTargetStatus(result.Int64)
	return
}

func (p *TraceTargetStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TraceTargetErrorCode = erroridl.ErrorCode

type TraceTargetError struct {
	Code      TraceTargetErrorCode `thrift:"code,1,required,ErrorCode" json:"code"`
	Message   string               `thrift:"message,2,required" json:"message"`
	Retryable bool                 `thrift:"retryable,3,required" json:"retryable"`
}

func NewTraceTargetError() *TraceTargetError {
	return &TraceTargetError{}
}

func (p *TraceTargetError) InitDefault() {
}

func (p *TraceTargetError) GetCode() (v TraceTargetErrorCode) {
	return p.Code
}

func (p *TraceTargetError) GetMessage() (v string) {
	return p.Message
}

func (p *TraceTargetError) GetRetryable() (v bool) {
	return p.Retryable
}

func (p *TraceTargetError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceTargetError(%+v)", *p)
}

func (p *TraceTargetError) DeepEqual(ano *TraceTargetError) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Code) {
		return false
	}
	if !p.Field2DeepEqual(ano.Message) {
		return false
	}
	if !p.Field3DeepEqual(ano.Retryable) {
		return false
	}
	return true
}

func (p *TraceTargetError) Field1DeepEqual(src TraceTargetErrorCode) bool {

	if p.Code != src {
		return false
	}
	return true
}
func (p *TraceTargetError) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Message, src) != 0 {
		return false
	}
	return true
}
func (p *TraceTargetError) Field3DeepEqual(src bool) bool {

	if p.Retryable != src {
		return false
	}
	return true
}

var fieldIDToName_TraceTargetError = map[int16]string{
	1: "code",
	2: "message",
	3: "retryable",
}

type TraceTargetResult struct {
	Target TraceTarget       `thrift:"target,1,required,TraceTarget" json:"target"`
	Status TraceTargetStatus `thrift:"status,2,required,TraceTargetStatus" json:"status"`
	Reason *string           `thrift:"reason,3,optional" json:"reason,omitempty"`
	Error  *TraceTargetError `thrift:"error,4,optional" json:"error,omitempty"`
}

func NewTraceTargetResult() *TraceTargetResult {
	return &TraceTargetResult{}
}

func (p *TraceTargetResult) InitDefault() {
}

func (p *TraceTargetResult) GetTarget() (v TraceTarget) {
	return p.Target
}

func (p *TraceTargetResult) GetStatus() (v TraceTargetStatus) {
	return p.Status
}

var TraceTargetResult_Reason_DEFAULT string

func (p *TraceTargetResult) GetReason() (v string) {
	if !p.IsSetReason() {
		return TraceTargetResult_Reason_DEFAULT
	}
	return *p.Reason
}

var TraceTargetResult_Error_DEFAULT *TraceTargetError

func (p *TraceTargetResult) GetError() (v *TraceTargetError) {
	if !p.IsSetError() {
		return TraceTargetResult_Error_DEFAULT
	}
	return p.Error
}

func (p *TraceTargetResult) IsSetReason() bool {
	return p.Reason != nil
}

func (p *TraceTargetResult) IsSetError() bool {
	return p.Error != nil
}

func (p *TraceTargetResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceTargetResult(%+v)", *p)
}

func (p *TraceTargetResult) DeepEqual(ano *TraceTargetResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Target) {
		return false
	}
	if !p.Field2DeepEqual(ano.Status) {
		return false
	}
	if !p.Field3DeepEqual(ano.Reason) {
		return false
	}
	if !p.Field4DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *TraceTargetResult) Field1DeepEqual(src TraceTarget) bool {

	if p.Target != src {
		return false
	}
	return true
}
func (p *TraceTargetResult) Field2DeepEqual(src TraceTargetStatus) bool {

	if p.Status != src {
		return false
	}
	return true
}
func (p *TraceTargetResult) Field3DeepEqual(src *string) bool {

	if p.Reason == src {
		return true
	} else if p.Reason == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Reason, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceTargetResult) Field4DeepEqual(src *TraceTargetError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_TraceTargetResult = map[int16]string{
	1: "target",
	2: "status",
	3: "reason",
	4: "error",
}

type TraceRegistry struct {
	Profile   string `thrift:"profile,1,required" json:"profile"`
	Url       string `thrift:"url,2,required" json:"url"`
	BaseToken string `thrift:"base_token,3,required" json:"base_token"`
	TableId   string `thrift:"table_id,4,required" json:"table_id"`
	ViewId    string `thrift:"view_id,5,required" json:"view_id"`
}

func NewTraceRegistry() *TraceRegistry {
	return &TraceRegistry{}
}

func (p *TraceRegistry) InitDefault() {
}

func (p *TraceRegistry) GetProfile() (v string) {
	return p.Profile
}

func (p *TraceRegistry) GetUrl() (v string) {
	return p.Url
}

func (p *TraceRegistry) GetBaseToken() (v string) {
	return p.BaseToken
}

func (p *TraceRegistry) GetTableId() (v string) {
	return p.TableId
}

func (p *TraceRegistry) GetViewId() (v string) {
	return p.ViewId
}

func (p *TraceRegistry) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceRegistry(%+v)", *p)
}

func (p *TraceRegistry) DeepEqual(ano *TraceRegistry) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Profile) {
		return false
	}
	if !p.Field2DeepEqual(ano.Url) {
		return false
	}
	if !p.Field3DeepEqual(ano.BaseToken) {
		return false
	}
	if !p.Field4DeepEqual(ano.TableId) {
		return false
	}
	if !p.Field5DeepEqual(ano.ViewId) {
		return false
	}
	return true
}

func (p *TraceRegistry) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Profile, src) != 0 {
		return false
	}
	return true
}
func (p *TraceRegistry) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Url, src) != 0 {
		return false
	}
	return true
}
func (p *TraceRegistry) Field3DeepEqual(src string) bool {

	if strings.Compare(p.BaseToken, src) != 0 {
		return false
	}
	return true
}
func (p *TraceRegistry) Field4DeepEqual(src string) bool {

	if strings.Compare(p.TableId, src) != 0 {
		return false
	}
	return true
}
func (p *TraceRegistry) Field5DeepEqual(src string) bool {

	if strings.Compare(p.ViewId, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_TraceRegistry = map[int16]string{
	1: "profile",
	2: "url",
	3: "base_token",
	4: "table_id",
	5: "view_id",
}

type TraceLastSync struct {
	OccurredAt string               `thrift:"occurred_at,1,required" json:"occurred_at"`
	Outcome    TraceSyncOutcome     `thrift:"outcome,2,required,TraceSyncOutcome" json:"outcome"`
	Targets    []*TraceTargetResult `thrift:"targets,3,required,list<TraceTargetResult>" json:"targets"`
}

func NewTraceLastSync() *TraceLastSync {
	return &TraceLastSync{}
}

func (p *TraceLastSync) InitDefault() {
}

func (p *TraceLastSync) GetOccurredAt() (v string) {
	return p.OccurredAt
}

func (p *TraceLastSync) GetOutcome() (v TraceSyncOutcome) {
	return p.Outcome
}

func (p *TraceLastSync) GetTargets() (v []*TraceTargetResult) {
	return p.Targets
}

func (p *TraceLastSync) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceLastSync(%+v)", *p)
}

func (p *TraceLastSync) DeepEqual(ano *TraceLastSync) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.OccurredAt) {
		return false
	}
	if !p.Field2DeepEqual(ano.Outcome) {
		return false
	}
	if !p.Field3DeepEqual(ano.Targets) {
		return false
	}
	return true
}

func (p *TraceLastSync) Field1DeepEqual(src string) bool {

	if strings.Compare(p.OccurredAt, src) != 0 {
		return false
	}
	return true
}
func (p *TraceLastSync) Field2DeepEqual(src TraceSyncOutcome) bool {

	if p.Outcome != src {
		return false
	}
	return true
}
func (p *TraceLastSync) Field3DeepEqual(src []*TraceTargetResult) bool {

	if len(p.Targets) != len(src) {
		return false
	}
	for i, v := range p.Targets {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_TraceLastSync = map[int16]string{
	1: "occurred_at",
	2: "outcome",
	3: "targets",
}

type TraceBindRequest struct {
	DocumentUrl       string  `thrift:"document_url,1,required" json:"document_url"`
	Registry          *string `thrift:"registry,2,optional" json:"registry,omitempty"`
	CliLogDocumentUrl *string `thrift:"cli_log_document_url,3,optional" json:"cli_log_document_url,omitempty"`
}

func NewTraceBindRequest() *TraceBindRequest {
	return &TraceBindRequest{}
}

func (p *TraceBindRequest) InitDefault() {
}

func (p *TraceBindRequest) GetDocumentUrl() (v string) {
	return p.DocumentUrl
}

var TraceBindRequest_Registry_DEFAULT string

func (p *TraceBindRequest) GetRegistry() (v string) {
	if !p.IsSetRegistry() {
		return TraceBindRequest_Registry_DEFAULT
	}
	return *p.Registry
}

var TraceBindRequest_CliLogDocumentUrl_DEFAULT string

func (p *TraceBindRequest) GetCliLogDocumentUrl() (v string) {
	if !p.IsSetCliLogDocumentUrl() {
		return TraceBindRequest_CliLogDocumentUrl_DEFAULT
	}
	return *p.CliLogDocumentUrl
}

func (p *TraceBindRequest) IsSetRegistry() bool {
	return p.Registry != nil
}

func (p *TraceBindRequest) IsSetCliLogDocumentUrl() bool {
	return p.CliLogDocumentUrl != nil
}

func (p *TraceBindRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceBindRequest(%+v)", *p)
}

func (p *TraceBindRequest) DeepEqual(ano *TraceBindRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.DocumentUrl) {
		return false
	}
	if !p.Field2DeepEqual(ano.Registry) {
		return false
	}
	if !p.Field3DeepEqual(ano.CliLogDocumentUrl) {
		return false
	}
	return true
}

func (p *TraceBindRequest) Field1DeepEqual(src string) bool {

	if strings.Compare(p.DocumentUrl, src) != 0 {
		return false
	}
	return true
}
func (p *TraceBindRequest) Field2DeepEqual(src *string) bool {

	if p.Registry == src {
		return true
	} else if p.Registry == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Registry, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceBindRequest) Field3DeepEqual(src *string) bool {

	if p.CliLogDocumentUrl == src {
		return true
	} else if p.CliLogDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CliLogDocumentUrl, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_TraceBindRequest = map[int16]string{
	1: "document_url",
	2: "registry",
	3: "cli_log_document_url",
}

type TraceBindResponse struct {
	Effect TraceBindEffect `thrift:"effect,1,required,TraceBindEffect" json:"effect"`
}

func NewTraceBindResponse() *TraceBindResponse {
	return &TraceBindResponse{}
}

func (p *TraceBindResponse) InitDefault() {
}

func (p *TraceBindResponse) GetEffect() (v TraceBindEffect) {
	return p.Effect
}

func (p *TraceBindResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceBindResponse(%+v)", *p)
}

func (p *TraceBindResponse) DeepEqual(ano *TraceBindResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Effect) {
		return false
	}
	return true
}

func (p *TraceBindResponse) Field1DeepEqual(src TraceBindEffect) bool {

	if p.Effect != src {
		return false
	}
	return true
}

var fieldIDToName_TraceBindResponse = map[int16]string{
	1: "effect",
}

type TraceStatusRequest struct {
}

func NewTraceStatusRequest() *TraceStatusRequest {
	return &TraceStatusRequest{}
}

func (p *TraceStatusRequest) InitDefault() {
}

func (p *TraceStatusRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceStatusRequest(%+v)", *p)
}

func (p *TraceStatusRequest) DeepEqual(ano *TraceStatusRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

var fieldIDToName_TraceStatusRequest = map[int16]string{}

type TraceStatusResponse struct {
	DocumentUrl       *string        `thrift:"document_url,1,optional" json:"document_url,omitempty"`
	Registry          *TraceRegistry `thrift:"registry,2,optional" json:"registry,omitempty"`
	EventCount        int32          `thrift:"event_count,3,required" json:"event_count"`
	LastSync          *TraceLastSync `thrift:"last_sync,4,optional" json:"last_sync,omitempty"`
	CliLogDocumentUrl *string        `thrift:"cli_log_document_url,5,optional" json:"cli_log_document_url,omitempty"`
}

func NewTraceStatusResponse() *TraceStatusResponse {
	return &TraceStatusResponse{}
}

func (p *TraceStatusResponse) InitDefault() {
}

var TraceStatusResponse_DocumentUrl_DEFAULT string

func (p *TraceStatusResponse) GetDocumentUrl() (v string) {
	if !p.IsSetDocumentUrl() {
		return TraceStatusResponse_DocumentUrl_DEFAULT
	}
	return *p.DocumentUrl
}

var TraceStatusResponse_Registry_DEFAULT *TraceRegistry

func (p *TraceStatusResponse) GetRegistry() (v *TraceRegistry) {
	if !p.IsSetRegistry() {
		return TraceStatusResponse_Registry_DEFAULT
	}
	return p.Registry
}

func (p *TraceStatusResponse) GetEventCount() (v int32) {
	return p.EventCount
}

var TraceStatusResponse_LastSync_DEFAULT *TraceLastSync

func (p *TraceStatusResponse) GetLastSync() (v *TraceLastSync) {
	if !p.IsSetLastSync() {
		return TraceStatusResponse_LastSync_DEFAULT
	}
	return p.LastSync
}

var TraceStatusResponse_CliLogDocumentUrl_DEFAULT string

func (p *TraceStatusResponse) GetCliLogDocumentUrl() (v string) {
	if !p.IsSetCliLogDocumentUrl() {
		return TraceStatusResponse_CliLogDocumentUrl_DEFAULT
	}
	return *p.CliLogDocumentUrl
}

func (p *TraceStatusResponse) IsSetDocumentUrl() bool {
	return p.DocumentUrl != nil
}

func (p *TraceStatusResponse) IsSetRegistry() bool {
	return p.Registry != nil
}

func (p *TraceStatusResponse) IsSetLastSync() bool {
	return p.LastSync != nil
}

func (p *TraceStatusResponse) IsSetCliLogDocumentUrl() bool {
	return p.CliLogDocumentUrl != nil
}

func (p *TraceStatusResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceStatusResponse(%+v)", *p)
}

func (p *TraceStatusResponse) DeepEqual(ano *TraceStatusResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.DocumentUrl) {
		return false
	}
	if !p.Field2DeepEqual(ano.Registry) {
		return false
	}
	if !p.Field3DeepEqual(ano.EventCount) {
		return false
	}
	if !p.Field4DeepEqual(ano.LastSync) {
		return false
	}
	if !p.Field5DeepEqual(ano.CliLogDocumentUrl) {
		return false
	}
	return true
}

func (p *TraceStatusResponse) Field1DeepEqual(src *string) bool {

	if p.DocumentUrl == src {
		return true
	} else if p.DocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.DocumentUrl, *src) != 0 {
		return false
	}
	return true
}
func (p *TraceStatusResponse) Field2DeepEqual(src *TraceRegistry) bool {

	if !p.Registry.DeepEqual(src) {
		return false
	}
	return true
}
func (p *TraceStatusResponse) Field3DeepEqual(src int32) bool {

	if p.EventCount != src {
		return false
	}
	return true
}
func (p *TraceStatusResponse) Field4DeepEqual(src *TraceLastSync) bool {

	if !p.LastSync.DeepEqual(src) {
		return false
	}
	return true
}
func (p *TraceStatusResponse) Field5DeepEqual(src *string) bool {

	if p.CliLogDocumentUrl == src {
		return true
	} else if p.CliLogDocumentUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.CliLogDocumentUrl, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_TraceStatusResponse = map[int16]string{
	1: "document_url",
	2: "registry",
	3: "event_count",
	4: "last_sync",
	5: "cli_log_document_url",
}

type TraceRenderRequest struct {
}

func NewTraceRenderRequest() *TraceRenderRequest {
	return &TraceRenderRequest{}
}

func (p *TraceRenderRequest) InitDefault() {
}

func (p *TraceRenderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceRenderRequest(%+v)", *p)
}

func (p *TraceRenderRequest) DeepEqual(ano *TraceRenderRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

var fieldIDToName_TraceRenderRequest = map[int16]string{}

type TraceRenderResponse struct {
	EventCount     int32  `thrift:"event_count,1,required" json:"event_count"`
	ProjectionPath string `thrift:"projection_path,2,required" json:"projection_path"`
}

func NewTraceRenderResponse() *TraceRenderResponse {
	return &TraceRenderResponse{}
}

func (p *TraceRenderResponse) InitDefault() {
}

func (p *TraceRenderResponse) GetEventCount() (v int32) {
	return p.EventCount
}

func (p *TraceRenderResponse) GetProjectionPath() (v string) {
	return p.ProjectionPath
}

func (p *TraceRenderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceRenderResponse(%+v)", *p)
}

func (p *TraceRenderResponse) DeepEqual(ano *TraceRenderResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.EventCount) {
		return false
	}
	if !p.Field2DeepEqual(ano.ProjectionPath) {
		return false
	}
	return true
}

func (p *TraceRenderResponse) Field1DeepEqual(src int32) bool {

	if p.EventCount != src {
		return false
	}
	return true
}
func (p *TraceRenderResponse) Field2DeepEqual(src string) bool {

	if strings.Compare(p.ProjectionPath, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_TraceRenderResponse = map[int16]string{
	1: "event_count",
	2: "projection_path",
}

type TraceSyncRequest struct {
}

func NewTraceSyncRequest() *TraceSyncRequest {
	return &TraceSyncRequest{}
}

func (p *TraceSyncRequest) InitDefault() {
}

func (p *TraceSyncRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceSyncRequest(%+v)", *p)
}

func (p *TraceSyncRequest) DeepEqual(ano *TraceSyncRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

var fieldIDToName_TraceSyncRequest = map[int16]string{}

type TraceSyncResponse struct {
	Outcome TraceSyncOutcome     `thrift:"outcome,1,required,TraceSyncOutcome" json:"outcome"`
	Targets []*TraceTargetResult `thrift:"targets,2,required,list<TraceTargetResult>" json:"targets"`
}

func NewTraceSyncResponse() *TraceSyncResponse {
	return &TraceSyncResponse{}
}

func (p *TraceSyncResponse) InitDefault() {
}

func (p *TraceSyncResponse) GetOutcome() (v TraceSyncOutcome) {
	return p.Outcome
}

func (p *TraceSyncResponse) GetTargets() (v []*TraceTargetResult) {
	return p.Targets
}

func (p *TraceSyncResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceSyncResponse(%+v)", *p)
}

func (p *TraceSyncResponse) DeepEqual(ano *TraceSyncResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Outcome) {
		return false
	}
	if !p.Field2DeepEqual(ano.Targets) {
		return false
	}
	return true
}

func (p *TraceSyncResponse) Field1DeepEqual(src TraceSyncOutcome) bool {

	if p.Outcome != src {
		return false
	}
	return true
}
func (p *TraceSyncResponse) Field2DeepEqual(src []*TraceTargetResult) bool {

	if len(p.Targets) != len(src) {
		return false
	}
	for i, v := range p.Targets {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_TraceSyncResponse = map[int16]string{
	1: "outcome",
	2: "targets",
}

type TraceService interface {
	Bind(ctx context.Context, requirementRoot string, request *TraceBindRequest, dryRun bool) (r *TraceBindResponse, err error)

	Status(ctx context.Context, requirementRoot string, request *TraceStatusRequest) (r *TraceStatusResponse, err error)

	Render(ctx context.Context, requirementRoot string, request *TraceRenderRequest, dryRun bool) (r *TraceRenderResponse, err error)

	Sync(ctx context.Context, requirementRoot string, request *TraceSyncRequest, dryRun bool) (r *TraceSyncResponse, err error)
}

type TraceServiceBindArgs struct {
	RequirementRoot string            `thrift:"requirement_root,1,required" json:"requirement_root"`
	Request         *TraceBindRequest `thrift:"request,2,required" json:"request"`
	DryRun          bool              `thrift:"dry_run,3,required" json:"dry_run"`
}

func NewTraceServiceBindArgs() *TraceServiceBindArgs {
	return &TraceServiceBindArgs{}
}

func (p *TraceServiceBindArgs) InitDefault() {
}

func (p *TraceServiceBindArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var TraceServiceBindArgs_Request_DEFAULT *TraceBindRequest

func (p *TraceServiceBindArgs) GetRequest() (v *TraceBindRequest) {
	if !p.IsSetRequest() {
		return TraceServiceBindArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *TraceServiceBindArgs) GetDryRun() (v bool) {
	return p.DryRun
}

func (p *TraceServiceBindArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TraceServiceBindArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceServiceBindArgs(%+v)", *p)
}

func (p *TraceServiceBindArgs) DeepEqual(ano *TraceServiceBindArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	if !p.Field3DeepEqual(ano.DryRun) {
		return false
	}
	return true
}

func (p *TraceServiceBindArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *TraceServiceBindArgs) Field2DeepEqual(src *TraceBindRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}
func (p *TraceServiceBindArgs) Field3DeepEqual(src bool) bool {

	if p.DryRun != src {
		return false
	}
	return true
}

var fieldIDToName_TraceServiceBindArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
	3: "dry_run",
}

type TraceServiceBindResult struct {
	Success *TraceBindResponse    `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewTraceServiceBindResult() *TraceServiceBindResult {
	return &TraceServiceBindResult{}
}

func (p *TraceServiceBindResult) InitDefault() {
}

var TraceServiceBindResult_Success_DEFAULT *TraceBindResponse

func (p *TraceServiceBindResult) GetSuccess() (v *TraceBindResponse) {
	if !p.IsSetSuccess() {
		return TraceServiceBindResult_Success_DEFAULT
	}
	return p.Success
}

var TraceServiceBindResult_Error_DEFAULT *erroridl.PublicError

func (p *TraceServiceBindResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return TraceServiceBindResult_Error_DEFAULT
	}
	return p.Error
}

func (p *TraceServiceBindResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TraceServiceBindResult) IsSetError() bool {
	return p.Error != nil
}

func (p *TraceServiceBindResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceServiceBindResult(%+v)", *p)
}

func (p *TraceServiceBindResult) DeepEqual(ano *TraceServiceBindResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *TraceServiceBindResult) Field0DeepEqual(src *TraceBindResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *TraceServiceBindResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_TraceServiceBindResult = map[int16]string{
	0: "success",
	1: "error",
}

type TraceServiceStatusArgs struct {
	RequirementRoot string              `thrift:"requirement_root,1,required" json:"requirement_root"`
	Request         *TraceStatusRequest `thrift:"request,2,required" json:"request"`
}

func NewTraceServiceStatusArgs() *TraceServiceStatusArgs {
	return &TraceServiceStatusArgs{}
}

func (p *TraceServiceStatusArgs) InitDefault() {
}

func (p *TraceServiceStatusArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var TraceServiceStatusArgs_Request_DEFAULT *TraceStatusRequest

func (p *TraceServiceStatusArgs) GetRequest() (v *TraceStatusRequest) {
	if !p.IsSetRequest() {
		return TraceServiceStatusArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *TraceServiceStatusArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TraceServiceStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceServiceStatusArgs(%+v)", *p)
}

func (p *TraceServiceStatusArgs) DeepEqual(ano *TraceServiceStatusArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	return true
}

func (p *TraceServiceStatusArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *TraceServiceStatusArgs) Field2DeepEqual(src *TraceStatusRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_TraceServiceStatusArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
}

type TraceServiceStatusResult struct {
	Success *TraceStatusResponse  `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewTraceServiceStatusResult() *TraceServiceStatusResult {
	return &TraceServiceStatusResult{}
}

func (p *TraceServiceStatusResult) InitDefault() {
}

var TraceServiceStatusResult_Success_DEFAULT *TraceStatusResponse

func (p *TraceServiceStatusResult) GetSuccess() (v *TraceStatusResponse) {
	if !p.IsSetSuccess() {
		return TraceServiceStatusResult_Success_DEFAULT
	}
	return p.Success
}

var TraceServiceStatusResult_Error_DEFAULT *erroridl.PublicError

func (p *TraceServiceStatusResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return TraceServiceStatusResult_Error_DEFAULT
	}
	return p.Error
}

func (p *TraceServiceStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TraceServiceStatusResult) IsSetError() bool {
	return p.Error != nil
}

func (p *TraceServiceStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceServiceStatusResult(%+v)", *p)
}

func (p *TraceServiceStatusResult) DeepEqual(ano *TraceServiceStatusResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *TraceServiceStatusResult) Field0DeepEqual(src *TraceStatusResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *TraceServiceStatusResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_TraceServiceStatusResult = map[int16]string{
	0: "success",
	1: "error",
}

type TraceServiceRenderArgs struct {
	RequirementRoot string              `thrift:"requirement_root,1,required" json:"requirement_root"`
	Request         *TraceRenderRequest `thrift:"request,2,required" json:"request"`
	DryRun          bool                `thrift:"dry_run,3,required" json:"dry_run"`
}

func NewTraceServiceRenderArgs() *TraceServiceRenderArgs {
	return &TraceServiceRenderArgs{}
}

func (p *TraceServiceRenderArgs) InitDefault() {
}

func (p *TraceServiceRenderArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var TraceServiceRenderArgs_Request_DEFAULT *TraceRenderRequest

func (p *TraceServiceRenderArgs) GetRequest() (v *TraceRenderRequest) {
	if !p.IsSetRequest() {
		return TraceServiceRenderArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *TraceServiceRenderArgs) GetDryRun() (v bool) {
	return p.DryRun
}

func (p *TraceServiceRenderArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TraceServiceRenderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceServiceRenderArgs(%+v)", *p)
}

func (p *TraceServiceRenderArgs) DeepEqual(ano *TraceServiceRenderArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	if !p.Field3DeepEqual(ano.DryRun) {
		return false
	}
	return true
}

func (p *TraceServiceRenderArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *TraceServiceRenderArgs) Field2DeepEqual(src *TraceRenderRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}
func (p *TraceServiceRenderArgs) Field3DeepEqual(src bool) bool {

	if p.DryRun != src {
		return false
	}
	return true
}

var fieldIDToName_TraceServiceRenderArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
	3: "dry_run",
}

type TraceServiceRenderResult struct {
	Success *TraceRenderResponse  `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewTraceServiceRenderResult() *TraceServiceRenderResult {
	return &TraceServiceRenderResult{}
}

func (p *TraceServiceRenderResult) InitDefault() {
}

var TraceServiceRenderResult_Success_DEFAULT *TraceRenderResponse

func (p *TraceServiceRenderResult) GetSuccess() (v *TraceRenderResponse) {
	if !p.IsSetSuccess() {
		return TraceServiceRenderResult_Success_DEFAULT
	}
	return p.Success
}

var TraceServiceRenderResult_Error_DEFAULT *erroridl.PublicError

func (p *TraceServiceRenderResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return TraceServiceRenderResult_Error_DEFAULT
	}
	return p.Error
}

func (p *TraceServiceRenderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TraceServiceRenderResult) IsSetError() bool {
	return p.Error != nil
}

func (p *TraceServiceRenderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceServiceRenderResult(%+v)", *p)
}

func (p *TraceServiceRenderResult) DeepEqual(ano *TraceServiceRenderResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *TraceServiceRenderResult) Field0DeepEqual(src *TraceRenderResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *TraceServiceRenderResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_TraceServiceRenderResult = map[int16]string{
	0: "success",
	1: "error",
}

type TraceServiceSyncArgs struct {
	RequirementRoot string            `thrift:"requirement_root,1,required" json:"requirement_root"`
	Request         *TraceSyncRequest `thrift:"request,2,required" json:"request"`
	DryRun          bool              `thrift:"dry_run,3,required" json:"dry_run"`
}

func NewTraceServiceSyncArgs() *TraceServiceSyncArgs {
	return &TraceServiceSyncArgs{}
}

func (p *TraceServiceSyncArgs) InitDefault() {
}

func (p *TraceServiceSyncArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var TraceServiceSyncArgs_Request_DEFAULT *TraceSyncRequest

func (p *TraceServiceSyncArgs) GetRequest() (v *TraceSyncRequest) {
	if !p.IsSetRequest() {
		return TraceServiceSyncArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *TraceServiceSyncArgs) GetDryRun() (v bool) {
	return p.DryRun
}

func (p *TraceServiceSyncArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TraceServiceSyncArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceServiceSyncArgs(%+v)", *p)
}

func (p *TraceServiceSyncArgs) DeepEqual(ano *TraceServiceSyncArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	if !p.Field3DeepEqual(ano.DryRun) {
		return false
	}
	return true
}

func (p *TraceServiceSyncArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *TraceServiceSyncArgs) Field2DeepEqual(src *TraceSyncRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}
func (p *TraceServiceSyncArgs) Field3DeepEqual(src bool) bool {

	if p.DryRun != src {
		return false
	}
	return true
}

var fieldIDToName_TraceServiceSyncArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
	3: "dry_run",
}

type TraceServiceSyncResult struct {
	Success *TraceSyncResponse    `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewTraceServiceSyncResult() *TraceServiceSyncResult {
	return &TraceServiceSyncResult{}
}

func (p *TraceServiceSyncResult) InitDefault() {
}

var TraceServiceSyncResult_Success_DEFAULT *TraceSyncResponse

func (p *TraceServiceSyncResult) GetSuccess() (v *TraceSyncResponse) {
	if !p.IsSetSuccess() {
		return TraceServiceSyncResult_Success_DEFAULT
	}
	return p.Success
}

var TraceServiceSyncResult_Error_DEFAULT *erroridl.PublicError

func (p *TraceServiceSyncResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return TraceServiceSyncResult_Error_DEFAULT
	}
	return p.Error
}

func (p *TraceServiceSyncResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TraceServiceSyncResult) IsSetError() bool {
	return p.Error != nil
}

func (p *TraceServiceSyncResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceServiceSyncResult(%+v)", *p)
}

func (p *TraceServiceSyncResult) DeepEqual(ano *TraceServiceSyncResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *TraceServiceSyncResult) Field0DeepEqual(src *TraceSyncResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *TraceServiceSyncResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_TraceServiceSyncResult = map[int16]string{
	0: "success",
	1: "error",
}

// exceptions of methods in TraceService.
var (
	_ error = (*erroridl.PublicError)(nil)
)
