// Code generated by Validator v0.2.5. DO NOT EDIT.

package traceidl

import (
	"bytes"
	"fmt"
	erroridl "github.com/zeefan1555/commonloop/internal/idl/erroridl"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *TraceTargetError) IsValid() error {
	if p.Code.String() == "<UNSET>" {
		return fmt.Errorf("field Code defined_only rule failed")
	}
	_src := []TraceTargetErrorCode{erroridl.ErrorCode_unspecified}
	for _, src := range _src {
		if p.Code == src {
			return fmt.Errorf("field Code not_in rule failed, current value: %v", p.Code)
		}
	}
	if len(p.Message) < int(1) {
		return fmt.Errorf("field Message min_len rule failed, current value: %d", len(p.Message))
	}
	return nil
}
func (p *TraceTargetResult) IsValid() error {
	if p.Target.String() == "<UNSET>" {
		return fmt.Errorf("field Target defined_only rule failed")
	}
	_src := []TraceTarget{TraceTarget_unspecified}
	for _, src := range _src {
		if p.Target == src {
			return fmt.Errorf("field Target not_in rule failed, current value: %v", p.Target)
		}
	}
	if p.Status.String() == "<UNSET>" {
		return fmt.Errorf("field Status defined_only rule failed")
	}
	_src1 := []TraceTargetStatus{TraceTargetStatus_unspecified}
	for _, src := range _src1 {
		if p.Status == src {
			return fmt.Errorf("field Status not_in rule failed, current value: %v", p.Status)
		}
	}
	if p.Error != nil {
		if err := p.Error.IsValid(); err != nil {
			return fmt.Errorf("field Error not valid, %w", err)
		}
	}
	return nil
}
func (p *TraceRegistry) IsValid() error {
	if len(p.Profile) < int(1) {
		return fmt.Errorf("field Profile min_len rule failed, current value: %d", len(p.Profile))
	}
	if len(p.Url) < int(1) {
		return fmt.Errorf("field Url min_len rule failed, current value: %d", len(p.Url))
	}
	if len(p.BaseToken) < int(1) {
		return fmt.Errorf("field BaseToken min_len rule failed, current value: %d", len(p.BaseToken))
	}
	if len(p.TableId) < int(1) {
		return fmt.Errorf("field TableId min_len rule failed, current value: %d", len(p.TableId))
	}
	if len(p.ViewId) < int(1) {
		return fmt.Errorf("field ViewId min_len rule failed, current value: %d", len(p.ViewId))
	}
	return nil
}
func (p *TraceLastSync) IsValid() error {
	if len(p.OccurredAt) < int(1) {
		return fmt.Errorf("field OccurredAt min_len rule failed, current value: %d", len(p.OccurredAt))
	}
	if p.Outcome.String() == "<UNSET>" {
		return fmt.Errorf("field Outcome defined_only rule failed")
	}
	_src := []TraceSyncOutcome{TraceSyncOutcome_unspecified}
	for _, src := range _src {
		if p.Outcome == src {
			return fmt.Errorf("field Outcome not_in rule failed, current value: %v", p.Outcome)
		}
	}
	return nil
}
func (p *TraceBindRequest) IsValid() error {
	if len(p.DocumentUrl) < int(1) {
		return fmt.Errorf("field DocumentUrl min_len rule failed, current value: %d", len(p.DocumentUrl))
	}
	return nil
}
func (p *TraceBindResponse) IsValid() error {
	if p.Effect.String() == "<UNSET>" {
		return fmt.Errorf("field Effect defined_only rule failed")
	}
	_src := []TraceBindEffect{TraceBindEffect_unspecified}
	for _, src := range _src {
		if p.Effect == src {
			return fmt.Errorf("field Effect not_in rule failed, current value: %v", p.Effect)
		}
	}
	return nil
}
func (p *TraceStatusRequest) IsValid() error {
	return nil
}
func (p *TraceStatusResponse) IsValid() error {
	if p.Registry != nil {
		if err := p.Registry.IsValid(); err != nil {
			return fmt.Errorf("field Registry not valid, %w", err)
		}
	}
	if p.EventCount < int32(0) {
		return fmt.Errorf("field EventCount ge rule failed, current value: %v", p.EventCount)
	}
	if p.LastSync != nil {
		if err := p.LastSync.IsValid(); err != nil {
			return fmt.Errorf("field LastSync not valid, %w", err)
		}
	}
	return nil
}
func (p *TraceRenderRequest) IsValid() error {
	return nil
}
func (p *TraceRenderResponse) IsValid() error {
	if p.EventCount < int32(0) {
		return fmt.Errorf("field EventCount ge rule failed, current value: %v", p.EventCount)
	}
	if len(p.ProjectionPath) < int(1) {
		return fmt.Errorf("field ProjectionPath min_len rule failed, current value: %d", len(p.ProjectionPath))
	}
	return nil
}
func (p *TraceSyncRequest) IsValid() error {
	return nil
}
func (p *TraceSyncResponse) IsValid() error {
	if p.Outcome.String() == "<UNSET>" {
		return fmt.Errorf("field Outcome defined_only rule failed")
	}
	_src := []TraceSyncOutcome{TraceSyncOutcome_unspecified}
	for _, src := range _src {
		if p.Outcome == src {
			return fmt.Errorf("field Outcome not_in rule failed, current value: %v", p.Outcome)
		}
	}
	return nil
}
