// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package cardidl

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/zeefan1555/commonloop/internal/idl/commonidl"
	"github.com/zeefan1555/commonloop/internal/idl/erroridl"
	"strings"
)

type CardView int64

const (
	CardView_unspecified CardView = 0
	CardView_current     CardView = 1
	CardView_panorama    CardView = 2
)

func (p CardView) String() string {
	switch p {
	case CardView_unspecified:
		return "unspecified"
	case CardView_current:
		return "current"
	case CardView_panorama:
		return "panorama"
	}
	return "<UNSET>"
}

func CardViewFromString(s string) (CardView, error) {
	switch s {
	case "unspecified":
		return CardView_unspecified, nil
	case "current":
		return CardView_current, nil
	case "panorama":
		return CardView_panorama, nil
	}
	return CardView(0), fmt.Errorf("not a valid CardView string")
}

func CardViewPtr(v CardView) *CardView { return &v }

func (p CardView) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *CardView) UnmarshalText(text []byte) error {
	q, err := CardViewFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *CardView) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = CardView(result.Int64)
	return
}

func (p *CardView) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type CardFormat int64

const (
	CardFormat_unspecified CardFormat = 0
	CardFormat_markdown    CardFormat = 1
	CardFormat_lark_json   CardFormat = 2
)

func (p CardFormat) String() string {
	switch p {
	case CardFormat_unspecified:
		return "unspecified"
	case CardFormat_markdown:
		return "markdown"
	case CardFormat_lark_json:
		return "lark_json"
	}
	return "<UNSET>"
}

func CardFormatFromString(s string) (CardFormat, error) {
	switch s {
	case "unspecified":
		return CardFormat_unspecified, nil
	case "markdown":
		return CardFormat_markdown, nil
	case "lark_json":
		return CardFormat_lark_json, nil
	}
	return CardFormat(0), fmt.Errorf("not a valid CardFormat string")
}

func CardFormatPtr(v CardFormat) *CardFormat { return &v }

func (p CardFormat) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *CardFormat) UnmarshalText(text []byte) error {
	q, err := CardFormatFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *CardFormat) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = CardFormat(result.Int64)
	return
}

func (p *CardFormat) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type CardRenderRequest struct {
	View   CardView   `thrift:"view,1,required,CardView" json:"view"`
	Format CardFormat `thrift:"format,2,required,CardFormat" json:"format"`
}

func NewCardRenderRequest() *CardRenderRequest {
	return &CardRenderRequest{}
}

func (p *CardRenderRequest) InitDefault() {
}

func (p *CardRenderRequest) GetView() (v CardView) {
	return p.View
}

func (p *CardRenderRequest) GetFormat() (v CardFormat) {
	return p.Format
}

func (p *CardRenderRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CardRenderRequest(%+v)", *p)
}

func (p *CardRenderRequest) DeepEqual(ano *CardRenderRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.View) {
		return false
	}
	if !p.Field2DeepEqual(ano.Format) {
		return false
	}
	return true
}

func (p *CardRenderRequest) Field1DeepEqual(src CardView) bool {

	if p.View != src {
		return false
	}
	return true
}
func (p *CardRenderRequest) Field2DeepEqual(src CardFormat) bool {

	if p.Format != src {
		return false
	}
	return true
}

var fieldIDToName_CardRenderRequest = map[int16]string{
	1: "view",
	2: "format",
}

type CardRenderResponse struct {
	Format       CardFormat           `thrift:"format,1,required,CardFormat" json:"format"`
	Content      *commonidl.JsonValue `thrift:"content,2,required" json:"content"`
	SnapshotPath *string              `thrift:"snapshot_path,3,optional" json:"snapshot_path,omitempty"`
}

func NewCardRenderResponse() *CardRenderResponse {
	return &CardRenderResponse{}
}

func (p *CardRenderResponse) InitDefault() {
}

func (p *CardRenderResponse) GetFormat() (v CardFormat) {
	return p.Format
}

var CardRenderResponse_Content_DEFAULT *commonidl.JsonValue

func (p *CardRenderResponse) GetContent() (v *commonidl.JsonValue) {
	if !p.IsSetContent() {
		return CardRenderResponse_Content_DEFAULT
	}
	return p.Content
}

var CardRenderResponse_SnapshotPath_DEFAULT string

func (p *CardRenderResponse) GetSnapshotPath() (v string) {
	if !p.IsSetSnapshotPath() {
		return CardRenderResponse_SnapshotPath_DEFAULT
	}
	return *p.SnapshotPath
}

func (p *CardRenderResponse) IsSetContent() bool {
	return p.Content != nil
}

func (p *CardRenderResponse) IsSetSnapshotPath() bool {
	return p.SnapshotPath != nil
}

func (p *CardRenderResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CardRenderResponse(%+v)", *p)
}

func (p *CardRenderResponse) DeepEqual(ano *CardRenderResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Format) {
		return false
	}
	if !p.Field2DeepEqual(ano.Content) {
		return false
	}
	if !p.Field3DeepEqual(ano.SnapshotPath) {
		return false
	}
	return true
}

func (p *CardRenderResponse) Field1DeepEqual(src CardFormat) bool {

	if p.Format != src {
		return false
	}
	return true
}
func (p *CardRenderResponse) Field2DeepEqual(src *commonidl.JsonValue) bool {

	if !p.Content.DeepEqual(src) {
		return false
	}
	return true
}
func (p *CardRenderResponse) Field3DeepEqual(src *string) bool {

	if p.SnapshotPath == src {
		return true
	} else if p.SnapshotPath == nil || src == nil {
		return false
	}
	if strings.Compare(*p.SnapshotPath, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_CardRenderResponse = map[int16]string{
	1: "format",
	2: "content",
	3: "snapshot_path",
}

type CardService interface {
	Render(ctx context.Context, requirementRoot string, request *CardRenderRequest, dryRun bool) (r *CardRenderResponse, err error)
}

type CardServiceRenderArgs struct {
	RequirementRoot string             `thrift:"requirement_root,1,required" json:"requirement_root"`
	Request         *CardRenderRequest `thrift:"request,2,required" json:"request"`
	DryRun          bool               `thrift:"dry_run,3,required" json:"dry_run"`
}

func NewCardServiceRenderArgs() *CardServiceRenderArgs {
	return &CardServiceRenderArgs{}
}

func (p *CardServiceRenderArgs) InitDefault() {
}

func (p *CardServiceRenderArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var CardServiceRenderArgs_Request_DEFAULT *CardRenderRequest

func (p *CardServiceRenderArgs) GetRequest() (v *CardRenderRequest) {
	if !p.IsSetRequest() {
		return CardServiceRenderArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *CardServiceRenderArgs) GetDryRun() (v bool) {
	return p.DryRun
}

func (p *CardServiceRenderArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *CardServiceRenderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CardServiceRenderArgs(%+v)", *p)
}

func (p *CardServiceRenderArgs) DeepEqual(ano *CardServiceRenderArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	if !p.Field3DeepEqual(ano.DryRun) {
		return false
	}
	return true
}

func (p *CardServiceRenderArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *CardServiceRenderArgs) Field2DeepEqual(src *CardRenderRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}
func (p *CardServiceRenderArgs) Field3DeepEqual(src bool) bool {

	if p.DryRun != src {
		return false
	}
	return true
}

var fieldIDToName_CardServiceRenderArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
	3: "dry_run",
}

type CardServiceRenderResult struct {
	Success *CardRenderResponse   `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewCardServiceRenderResult() *CardServiceRenderResult {
	return &CardServiceRenderResult{}
}

func (p *CardServiceRenderResult) InitDefault() {
}

var CardServiceRenderResult_Success_DEFAULT *CardRenderResponse

func (p *CardServiceRenderResult) GetSuccess() (v *CardRenderResponse) {
	if !p.IsSetSuccess() {
		return CardServiceRenderResult_Success_DEFAULT
	}
	return p.Success
}

var CardServiceRenderResult_Error_DEFAULT *erroridl.PublicError

func (p *CardServiceRenderResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return CardServiceRenderResult_Error_DEFAULT
	}
	return p.Error
}

func (p *CardServiceRenderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CardServiceRenderResult) IsSetError() bool {
	return p.Error != nil
}

func (p *CardServiceRenderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CardServiceRenderResult(%+v)", *p)
}

func (p *CardServiceRenderResult) DeepEqual(ano *CardServiceRenderResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *CardServiceRenderResult) Field0DeepEqual(src *CardRenderResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *CardServiceRenderResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_CardServiceRenderResult = map[int16]string{
	0: "success",
	1: "error",
}

// exceptions of methods in CardService.
var (
	_ error = (*erroridl.PublicError)(nil)
)
