// Code generated by Validator v0.2.5. DO NOT EDIT.

package cardidl

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *CardRenderRequest) IsValid() error {
	if p.View.String() == "<UNSET>" {
		return fmt.Errorf("field View defined_only rule failed")
	}
	_src := []CardView{CardView_unspecified}
	for _, src := range _src {
		if p.View == src {
			return fmt.Errorf("field View not_in rule failed, current value: %v", p.View)
		}
	}
	if p.Format.String() == "<UNSET>" {
		return fmt.Errorf("field Format defined_only rule failed")
	}
	_src1 := []CardFormat{CardFormat_unspecified}
	for _, src := range _src1 {
		if p.Format == src {
			return fmt.Errorf("field Format not_in rule failed, current value: %v", p.Format)
		}
	}
	return nil
}
func (p *CardRenderResponse) IsValid() error {
	if p.Format.String() == "<UNSET>" {
		return fmt.Errorf("field Format defined_only rule failed")
	}
	_src := []CardFormat{CardFormat_unspecified}
	for _, src := range _src {
		if p.Format == src {
			return fmt.Errorf("field Format not_in rule failed, current value: %v", p.Format)
		}
	}
	if p.Content == nil {
		return fmt.Errorf("field Content not_nil rule failed")
	}
	if err := p.Content.IsValid(); err != nil {
		return fmt.Errorf("field Content not valid, %w", err)
	}
	return nil
}
