// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package erroridl

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"strings"
)

var (
	ERROR_SPECS = map[ErrorCode]*ErrorSpec{
		ErrorCode_INVALID_ARGUMENT: &ErrorSpec{
			Code:      ErrorCode_INVALID_ARGUMENT,
			Type:      ErrorType_validation,
			ExitCode:  2,
			Retryable: false,
			Hint:      "Check the command arguments and retry.",
		},
		ErrorCode_INVALID_INPUT_JSON: &ErrorSpec{
			Code:      ErrorCode_INVALID_INPUT_JSON,
			Type:      ErrorType_validation,
			ExitCode:  2,
			Retryable: false,
			Hint:      "Pass one JSON object matching the command Request.",
		},
		ErrorCode_ROOT_REQUIRED: &ErrorSpec{
			Code:      ErrorCode_ROOT_REQUIRED,
			Type:      ErrorType_validation,
			ExitCode:  2,
			Retryable: false,
			Hint:      "Pass the absolute requirement directory.",
		},
		ErrorCode_WORKFLOW_REQUIRED: &ErrorSpec{
			Code:      ErrorCode_WORKFLOW_REQUIRED,
			Type:      ErrorType_validation,
			ExitCode:  2,
			Retryable: false,
			Hint:      "Set workflow in the Init Request.",
		},
		ErrorCode_ALREADY_INITIALIZED: &ErrorSpec{
			Code:      ErrorCode_ALREADY_INITIALIZED,
			Type:      ErrorType_state,
			ExitCode:  1,
			Retryable: false,
			Hint:      "Use flow status or choose another root.",
		},
		ErrorCode_NOT_INITIALIZED: &ErrorSpec{
			Code:      ErrorCode_NOT_INITIALIZED,
			Type:      ErrorType_state,
			ExitCode:  1,
			Retryable: false,
			Hint:      "Run flow init for this requirement root.",
		},
		ErrorCode_STATE_CORRUPT: &ErrorSpec{
			Code:      ErrorCode_STATE_CORRUPT,
			Type:      ErrorType_state,
			ExitCode:  5,
			Retryable: false,
			Hint:      "Repair or restore .commonloop local state.",
		},
		ErrorCode_STATE_SCHEMA_UNSUPPORTED: &ErrorSpec{
			Code:      ErrorCode_STATE_SCHEMA_UNSUPPORTED,
			Type:      ErrorType_state,
			ExitCode:  5,
			Retryable: false,
			Hint:      "Use a CLI release that supports this State Schema.",
		},
		ErrorCode_STATE_CONFLICT: &ErrorSpec{
			Code:      ErrorCode_STATE_CONFLICT,
			Type:      ErrorType_state,
			ExitCode:  1,
			Retryable: true,
			Hint:      "Read flow status again and retry from the current Step.",
		},
		ErrorCode_STEP_NOT_CURRENT: &ErrorSpec{
			Code:      ErrorCode_STEP_NOT_CURRENT,
			Type:      ErrorType_state,
			ExitCode:  1,
			Retryable: false,
			Hint:      "Read flow status again and use its current Step ID.",
		},
		ErrorCode_REPORT_NOT_ALLOWED: &ErrorSpec{
			Code:      ErrorCode_REPORT_NOT_ALLOWED,
			Type:      ErrorType_state,
			ExitCode:  1,
			Retryable: false,
			Hint:      "Follow the latest flow status.",
		},
		ErrorCode_WORKFLOW_NOT_FOUND: &ErrorSpec{
			Code:      ErrorCode_WORKFLOW_NOT_FOUND,
			Type:      ErrorType_workflow,
			ExitCode:  1,
			Retryable: false,
			Hint:      "Choose a Workflow shipped with this release.",
		},
		ErrorCode_WORKFLOW_MISMATCH: &ErrorSpec{
			Code:      ErrorCode_WORKFLOW_MISMATCH,
			Type:      ErrorType_workflow,
			ExitCode:  1,
			Retryable: false,
			Hint:      "Use the release containing the bound Workflow.",
		},
		ErrorCode_WORKFLOW_INVALID: &ErrorSpec{
			Code:      ErrorCode_WORKFLOW_INVALID,
			Type:      ErrorType_workflow,
			ExitCode:  5,
			Retryable: false,
			Hint:      "Fix the bundled Workflow before release.",
		},
		ErrorCode_LOCAL_COMMIT_FAILED: &ErrorSpec{
			Code:      ErrorCode_LOCAL_COMMIT_FAILED,
			Type:      ErrorType_state,
			ExitCode:  5,
			Retryable: false,
			Hint:      "Fix the local filesystem failure and retry.",
		},
		ErrorCode_INTERNAL: &ErrorSpec{
			Code:      ErrorCode_INTERNAL,
			Type:      ErrorType_internal,
			ExitCode:  5,
			Retryable: false,
			Hint:      "Report this runtime error.",
		},
		ErrorCode_CONDITION_NOT_ALLOWED: &ErrorSpec{
			Code:      ErrorCode_CONDITION_NOT_ALLOWED,
			Type:      ErrorType_validation,
			ExitCode:  2,
			Retryable: false,
			Hint:      "Submit only Conditions listed by the latest flow status.",
		},
		ErrorCode_CONDITION_CONFLICT: &ErrorSpec{
			Code:      ErrorCode_CONDITION_CONFLICT,
			Type:      ErrorType_validation,
			ExitCode:  2,
			Retryable: false,
			Hint:      "Remove duplicate or mutually exclusive Condition results.",
		},
		ErrorCode_OUTPUT_INVALID: &ErrorSpec{
			Code:      ErrorCode_OUTPUT_INVALID,
			Type:      ErrorType_validation,
			ExitCode:  2,
			Retryable: false,
			Hint:      "Match the Condition OutputSpec returned by flow status.",
		},
		ErrorCode_ROUTE_NOT_MATCHED: &ErrorSpec{
			Code:      ErrorCode_ROUTE_NOT_MATCHED,
			Type:      ErrorType_state,
			ExitCode:  1,
			Retryable: false,
			Hint:      "Report a complete Condition combination from flow status.",
		},
		ErrorCode_ROUTE_AMBIGUOUS: &ErrorSpec{
			Code:      ErrorCode_ROUTE_AMBIGUOUS,
			Type:      ErrorType_workflow,
			ExitCode:  5,
			Retryable: false,
			Hint:      "Fix ambiguous Workflow Routes before retrying.",
		},
		ErrorCode_ROUTE_NOT_ALLOWED: &ErrorSpec{
			Code:      ErrorCode_ROUTE_NOT_ALLOWED,
			Type:      ErrorType_validation,
			ExitCode:  2,
			Retryable: false,
			Hint:      "Choose one Route returned by the latest flow status.",
		},
		ErrorCode_PROTECTED_DOCUMENT: &ErrorSpec{
			Code:      ErrorCode_PROTECTED_DOCUMENT,
			Type:      ErrorType_workflow,
			ExitCode:  1,
			Retryable: false,
			Hint:      "Bind a dedicated Trace document.",
		},
		ErrorCode_UPSTREAM_AUTH_FAILED: &ErrorSpec{
			Code:      ErrorCode_UPSTREAM_AUTH_FAILED,
			Type:      ErrorType_external,
			ExitCode:  1,
			Retryable: false,
			Hint:      "Authenticate lark-cli as a user.",
		},
		ErrorCode_NETWORK_FAILED: &ErrorSpec{
			Code:      ErrorCode_NETWORK_FAILED,
			Type:      ErrorType_external,
			ExitCode:  1,
			Retryable: true,
			Hint:      "Check network connectivity and retry.",
		},
		ErrorCode_TRACE_UPDATE_FAILED: &ErrorSpec{
			Code:      ErrorCode_TRACE_UPDATE_FAILED,
			Type:      ErrorType_external,
			ExitCode:  1,
			Retryable: true,
			Hint:      "Check Trace document access and retry.",
		},
		ErrorCode_REGISTRY_UPDATE_FAILED: &ErrorSpec{
			Code:      ErrorCode_REGISTRY_UPDATE_FAILED,
			Type:      ErrorType_external,
			ExitCode:  1,
			Retryable: true,
			Hint:      "Check Registry access and retry.",
		},
	}
)

type ErrorType int64

const (
	ErrorType_unspecified ErrorType = 0
	ErrorType_validation  ErrorType = 1
	ErrorType_state       ErrorType = 2
	ErrorType_workflow    ErrorType = 3
	ErrorType_external    ErrorType = 4
	ErrorType_internal    ErrorType = 5
)

func (p ErrorType) String() string {
	switch p {
	case ErrorType_unspecified:
		return "unspecified"
	case ErrorType_validation:
		return "validation"
	case ErrorType_state:
		return "state"
	case ErrorType_workflow:
		return "workflow"
	case ErrorType_external:
		return "external"
	case ErrorType_internal:
		return "internal"
	}
	return "<UNSET>"
}

func ErrorTypeFromString(s string) (ErrorType, error) {
	switch s {
	case "unspecified":
		return ErrorType_unspecified, nil
	case "validation":
		return ErrorType_validation, nil
	case "state":
		return ErrorType_state, nil
	case "workflow":
		return ErrorType_workflow, nil
	case "external":
		return ErrorType_external, nil
	case "internal":
		return ErrorType_internal, nil
	}
	return ErrorType(0), fmt.Errorf("not a valid ErrorType string")
}

func ErrorTypePtr(v ErrorType) *ErrorType { return &v }

func (p ErrorType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *ErrorType) UnmarshalText(text []byte) error {
	q, err := ErrorTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *ErrorType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ErrorType(result.Int64)
	return
}

func (p *ErrorType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Numeric values and retired field numbers must never be reused.
type ErrorCode int64

const (
	ErrorCode_unspecified              ErrorCode = 0
	ErrorCode_INVALID_ARGUMENT         ErrorCode = 1
	ErrorCode_INVALID_INPUT_JSON       ErrorCode = 2
	ErrorCode_ROOT_REQUIRED            ErrorCode = 3
	ErrorCode_WORKFLOW_REQUIRED        ErrorCode = 4
	ErrorCode_ALREADY_INITIALIZED      ErrorCode = 5
	ErrorCode_NOT_INITIALIZED          ErrorCode = 6
	ErrorCode_STATE_CORRUPT            ErrorCode = 7
	ErrorCode_STATE_SCHEMA_UNSUPPORTED ErrorCode = 8
	ErrorCode_STATE_CONFLICT           ErrorCode = 9
	ErrorCode_STEP_NOT_CURRENT         ErrorCode = 10
	ErrorCode_REPORT_NOT_ALLOWED       ErrorCode = 11
	ErrorCode_WORKFLOW_NOT_FOUND       ErrorCode = 12
	ErrorCode_WORKFLOW_MISMATCH        ErrorCode = 13
	ErrorCode_WORKFLOW_INVALID         ErrorCode = 14
	ErrorCode_LOCAL_COMMIT_FAILED      ErrorCode = 15
	ErrorCode_INTERNAL                 ErrorCode = 16
	ErrorCode_CONDITION_NOT_ALLOWED    ErrorCode = 17
	ErrorCode_CONDITION_CONFLICT       ErrorCode = 18
	ErrorCode_OUTPUT_INVALID           ErrorCode = 19
	ErrorCode_ROUTE_NOT_MATCHED        ErrorCode = 20
	ErrorCode_ROUTE_AMBIGUOUS          ErrorCode = 21
	ErrorCode_ROUTE_NOT_ALLOWED        ErrorCode = 22
	ErrorCode_PROTECTED_DOCUMENT       ErrorCode = 23
	ErrorCode_UPSTREAM_AUTH_FAILED     ErrorCode = 24
	ErrorCode_NETWORK_FAILED           ErrorCode = 25
	ErrorCode_TRACE_UPDATE_FAILED      ErrorCode = 26
	ErrorCode_REGISTRY_UPDATE_FAILED   ErrorCode = 27
)

func (p ErrorCode) String() string {
	switch p {
	case ErrorCode_unspecified:
		return "unspecified"
	case ErrorCode_INVALID_ARGUMENT:
		return "INVALID_ARGUMENT"
	case ErrorCode_INVALID_INPUT_JSON:
		return "INVALID_INPUT_JSON"
	case ErrorCode_ROOT_REQUIRED:
		return "ROOT_REQUIRED"
	case ErrorCode_WORKFLOW_REQUIRED:
		return "WORKFLOW_REQUIRED"
	case ErrorCode_ALREADY_INITIALIZED:
		return "ALREADY_INITIALIZED"
	case ErrorCode_NOT_INITIALIZED:
		return "NOT_INITIALIZED"
	case ErrorCode_STATE_CORRUPT:
		return "STATE_CORRUPT"
	case ErrorCode_STATE_SCHEMA_UNSUPPORTED:
		return "STATE_SCHEMA_UNSUPPORTED"
	case ErrorCode_STATE_CONFLICT:
		return "STATE_CONFLICT"
	case ErrorCode_STEP_NOT_CURRENT:
		return "STEP_NOT_CURRENT"
	case ErrorCode_REPORT_NOT_ALLOWED:
		return "REPORT_NOT_ALLOWED"
	case ErrorCode_WORKFLOW_NOT_FOUND:
		return "WORKFLOW_NOT_FOUND"
	case ErrorCode_WORKFLOW_MISMATCH:
		return "WORKFLOW_MISMATCH"
	case ErrorCode_WORKFLOW_INVALID:
		return "WORKFLOW_INVALID"
	case ErrorCode_LOCAL_COMMIT_FAILED:
		return "LOCAL_COMMIT_FAILED"
	case ErrorCode_INTERNAL:
		return "INTERNAL"
	case ErrorCode_CONDITION_NOT_ALLOWED:
		return "CONDITION_NOT_ALLOWED"
	case ErrorCode_CONDITION_CONFLICT:
		return "CONDITION_CONFLICT"
	case ErrorCode_OUTPUT_INVALID:
		return "OUTPUT_INVALID"
	case ErrorCode_ROUTE_NOT_MATCHED:
		return "ROUTE_NOT_MATCHED"
	case ErrorCode_ROUTE_AMBIGUOUS:
		return "ROUTE_AMBIGUOUS"
	case ErrorCode_ROUTE_NOT_ALLOWED:
		return "ROUTE_NOT_ALLOWED"
	case ErrorCode_PROTECTED_DOCUMENT:
		return "PROTECTED_DOCUMENT"
	case ErrorCode_UPSTREAM_AUTH_FAILED:
		return "UPSTREAM_AUTH_FAILED"
	case ErrorCode_NETWORK_FAILED:
		return "NETWORK_FAILED"
	case ErrorCode_TRACE_UPDATE_FAILED:
		return "TRACE_UPDATE_FAILED"
	case ErrorCode_REGISTRY_UPDATE_FAILED:
		return "REGISTRY_UPDATE_FAILED"
	}
	return "<UNSET>"
}

func ErrorCodeFromString(s string) (ErrorCode, error) {
	switch s {
	case "unspecified":
		return ErrorCode_unspecified, nil
	case "INVALID_ARGUMENT":
		return ErrorCode_INVALID_ARGUMENT, nil
	case "INVALID_INPUT_JSON":
		return ErrorCode_INVALID_INPUT_JSON, nil
	case "ROOT_REQUIRED":
		return ErrorCode_ROOT_REQUIRED, nil
	case "WORKFLOW_REQUIRED":
		return ErrorCode_WORKFLOW_REQUIRED, nil
	case "ALREADY_INITIALIZED":
		return ErrorCode_ALREADY_INITIALIZED, nil
	case "NOT_INITIALIZED":
		return ErrorCode_NOT_INITIALIZED, nil
	case "STATE_CORRUPT":
		return ErrorCode_STATE_CORRUPT, nil
	case "STATE_SCHEMA_UNSUPPORTED":
		return ErrorCode_STATE_SCHEMA_UNSUPPORTED, nil
	case "STATE_CONFLICT":
		return ErrorCode_STATE_CONFLICT, nil
	case "STEP_NOT_CURRENT":
		return ErrorCode_STEP_NOT_CURRENT, nil
	case "REPORT_NOT_ALLOWED":
		return ErrorCode_REPORT_NOT_ALLOWED, nil
	case "WORKFLOW_NOT_FOUND":
		return ErrorCode_WORKFLOW_NOT_FOUND, nil
	case "WORKFLOW_MISMATCH":
		return ErrorCode_WORKFLOW_MISMATCH, nil
	case "WORKFLOW_INVALID":
		return ErrorCode_WORKFLOW_INVALID, nil
	case "LOCAL_COMMIT_FAILED":
		return ErrorCode_LOCAL_COMMIT_FAILED, nil
	case "INTERNAL":
		return ErrorCode_INTERNAL, nil
	case "CONDITION_NOT_ALLOWED":
		return ErrorCode_CONDITION_NOT_ALLOWED, nil
	case "CONDITION_CONFLICT":
		return ErrorCode_CONDITION_CONFLICT, nil
	case "OUTPUT_INVALID":
		return ErrorCode_OUTPUT_INVALID, nil
	case "ROUTE_NOT_MATCHED":
		return ErrorCode_ROUTE_NOT_MATCHED, nil
	case "ROUTE_AMBIGUOUS":
		return ErrorCode_ROUTE_AMBIGUOUS, nil
	case "ROUTE_NOT_ALLOWED":
		return ErrorCode_ROUTE_NOT_ALLOWED, nil
	case "PROTECTED_DOCUMENT":
		return ErrorCode_PROTECTED_DOCUMENT, nil
	case "UPSTREAM_AUTH_FAILED":
		return ErrorCode_UPSTREAM_AUTH_FAILED, nil
	case "NETWORK_FAILED":
		return ErrorCode_NETWORK_FAILED, nil
	case "TRACE_UPDATE_FAILED":
		return ErrorCode_TRACE_UPDATE_FAILED, nil
	case "REGISTRY_UPDATE_FAILED":
		return ErrorCode_REGISTRY_UPDATE_FAILED, nil
	}
	return ErrorCode(0), fmt.Errorf("not a valid ErrorCode string")
}

func ErrorCodePtr(v ErrorCode) *ErrorCode { return &v }

func (p ErrorCode) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *ErrorCode) UnmarshalText(text []byte) error {
	q, err := ErrorCodeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *ErrorCode) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ErrorCode(result.Int64)
	return
}

func (p *ErrorCode) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ErrorSpec struct {
	Code      ErrorCode `thrift:"code,1,required,ErrorCode" json:"code"`
	Type      ErrorType `thrift:"type,2,required,ErrorType" json:"type"`
	ExitCode  int32     `thrift:"exit_code,3,required" json:"exit_code"`
	Retryable bool      `thrift:"retryable,4,required" json:"retryable"`
	Hint      string    `thrift:"hint,5,required" json:"hint"`
}

func NewErrorSpec() *ErrorSpec {
	return &ErrorSpec{}
}

func (p *ErrorSpec) InitDefault() {
}

func (p *ErrorSpec) GetCode() (v ErrorCode) {
	return p.Code
}

func (p *ErrorSpec) GetType() (v ErrorType) {
	return p.Type
}

func (p *ErrorSpec) GetExitCode() (v int32) {
	return p.ExitCode
}

func (p *ErrorSpec) GetRetryable() (v bool) {
	return p.Retryable
}

func (p *ErrorSpec) GetHint() (v string) {
	return p.Hint
}

func (p *ErrorSpec) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ErrorSpec(%+v)", *p)
}

func (p *ErrorSpec) DeepEqual(ano *ErrorSpec) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Code) {
		return false
	}
	if !p.Field2DeepEqual(ano.Type) {
		return false
	}
	if !p.Field3DeepEqual(ano.ExitCode) {
		return false
	}
	if !p.Field4DeepEqual(ano.Retryable) {
		return false
	}
	if !p.Field5DeepEqual(ano.Hint) {
		return false
	}
	return true
}

func (p *ErrorSpec) Field1DeepEqual(src ErrorCode) bool {

	if p.Code != src {
		return false
	}
	return true
}
func (p *ErrorSpec) Field2DeepEqual(src ErrorType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *ErrorSpec) Field3DeepEqual(src int32) bool {

	if p.ExitCode != src {
		return false
	}
	return true
}
func (p *ErrorSpec) Field4DeepEqual(src bool) bool {

	if p.Retryable != src {
		return false
	}
	return true
}
func (p *ErrorSpec) Field5DeepEqual(src string) bool {

	if strings.Compare(p.Hint, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_ErrorSpec = map[int16]string{
	1: "code",
	2: "type",
	3: "exit_code",
	4: "retryable",
	5: "hint",
}

type PublicError struct {
	Code    ErrorCode         `thrift:"code,1,required,ErrorCode" json:"code"`
	Message string            `thrift:"message,2,required" json:"message"`
	Details map[string]string `thrift:"details,3,optional" json:"details,omitempty"`
}

func NewPublicError() *PublicError {
	return &PublicError{}
}

func (p *PublicError) InitDefault() {
}

func (p *PublicError) GetCode() (v ErrorCode) {
	return p.Code
}

func (p *PublicError) GetMessage() (v string) {
	return p.Message
}

var PublicError_Details_DEFAULT map[string]string

func (p *PublicError) GetDetails() (v map[string]string) {
	if !p.IsSetDetails() {
		return PublicError_Details_DEFAULT
	}
	return p.Details
}

func (p *PublicError) IsSetDetails() bool {
	return p.Details != nil
}

func (p *PublicError) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublicError(%+v)", *p)
}
func (p *PublicError) Error() string {
	return p.String()
}

func (p *PublicError) DeepEqual(ano *PublicError) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Code) {
		return false
	}
	if !p.Field2DeepEqual(ano.Message) {
		return false
	}
	if !p.Field3DeepEqual(ano.Details) {
		return false
	}
	return true
}

func (p *PublicError) Field1DeepEqual(src ErrorCode) bool {

	if p.Code != src {
		return false
	}
	return true
}
func (p *PublicError) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Message, src) != 0 {
		return false
	}
	return true
}
func (p *PublicError) Field3DeepEqual(src map[string]string) bool {

	if len(p.Details) != len(src) {
		return false
	}
	for k, v := range p.Details {
		_src := src[k]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}

var fieldIDToName_PublicError = map[int16]string{
	1: "code",
	2: "message",
	3: "details",
}
