// Code generated by Validator v0.2.5. DO NOT EDIT.

package erroridl

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *ErrorSpec) IsValid() error {
	if p.Code.String() == "<UNSET>" {
		return fmt.Errorf("field Code defined_only rule failed")
	}
	_src := []ErrorCode{ErrorCode_unspecified}
	for _, src := range _src {
		if p.Code == src {
			return fmt.Errorf("field Code not_in rule failed, current value: %v", p.Code)
		}
	}
	if p.Type.String() == "<UNSET>" {
		return fmt.Errorf("field Type defined_only rule failed")
	}
	_src1 := []ErrorType{ErrorType_unspecified}
	for _, src := range _src1 {
		if p.Type == src {
			return fmt.Errorf("field Type not_in rule failed, current value: %v", p.Type)
		}
	}
	if p.ExitCode < int32(1) {
		return fmt.Errorf("field ExitCode ge rule failed, current value: %v", p.ExitCode)
	}
	if len(p.Hint) < int(1) {
		return fmt.Errorf("field Hint min_len rule failed, current value: %d", len(p.Hint))
	}
	return nil
}
func (p *PublicError) IsValid() error {
	if p.Code.String() == "<UNSET>" {
		return fmt.Errorf("field Code defined_only rule failed")
	}
	_src := []ErrorCode{ErrorCode_unspecified}
	for _, src := range _src {
		if p.Code == src {
			return fmt.Errorf("field Code not_in rule failed, current value: %v", p.Code)
		}
	}
	if len(p.Message) < int(1) {
		return fmt.Errorf("field Message min_len rule failed, current value: %d", len(p.Message))
	}
	return nil
}
