// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package commonidl

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"strings"
)

type CommandRisk int64

const (
	CommandRisk_unspecified    CommandRisk = 0
	CommandRisk_read           CommandRisk = 1
	CommandRisk_local_write    CommandRisk = 2
	CommandRisk_external_write CommandRisk = 3
)

func (p CommandRisk) String() string {
	switch p {
	case CommandRisk_unspecified:
		return "unspecified"
	case CommandRisk_read:
		return "read"
	case CommandRisk_local_write:
		return "local_write"
	case CommandRisk_external_write:
		return "external_write"
	}
	return "<UNSET>"
}

func CommandRiskFromString(s string) (CommandRisk, error) {
	switch s {
	case "unspecified":
		return CommandRisk_unspecified, nil
	case "read":
		return CommandRisk_read, nil
	case "local_write":
		return CommandRisk_local_write, nil
	case "external_write":
		return CommandRisk_external_write, nil
	}
	return CommandRisk(0), fmt.Errorf("not a valid CommandRisk string")
}

func CommandRiskPtr(v CommandRisk) *CommandRisk { return &v }

func (p CommandRisk) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *CommandRisk) UnmarshalText(text []byte) error {
	q, err := CommandRiskFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *CommandRisk) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = CommandRisk(result.Int64)
	return
}

func (p *CommandRisk) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type RequirementScope int64

const (
	RequirementScope_unspecified RequirementScope = 0
	RequirementScope_none        RequirementScope = 1
	RequirementScope_new         RequirementScope = 2
	RequirementScope_existing    RequirementScope = 3
	RequirementScope_optional    RequirementScope = 4
)

func (p RequirementScope) String() string {
	switch p {
	case RequirementScope_unspecified:
		return "unspecified"
	case RequirementScope_none:
		return "none"
	case RequirementScope_new:
		return "new"
	case RequirementScope_existing:
		return "existing"
	case RequirementScope_optional:
		return "optional"
	}
	return "<UNSET>"
}

func RequirementScopeFromString(s string) (RequirementScope, error) {
	switch s {
	case "unspecified":
		return RequirementScope_unspecified, nil
	case "none":
		return RequirementScope_none, nil
	case "new":
		return RequirementScope_new, nil
	case "existing":
		return RequirementScope_existing, nil
	case "optional":
		return RequirementScope_optional, nil
	}
	return RequirementScope(0), fmt.Errorf("not a valid RequirementScope string")
}

func RequirementScopePtr(v RequirementScope) *RequirementScope { return &v }

func (p RequirementScope) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *RequirementScope) UnmarshalText(text []byte) error {
	q, err := RequirementScopeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *RequirementScope) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = RequirementScope(result.Int64)
	return
}

func (p *RequirementScope) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type WorkflowRef struct {
	Id string `thrift:"id,1,required" json:"id"`
	// field 2 retired: Workflow has no business version.
	Digest string `thrift:"digest,3,required" json:"digest"`
}

func NewWorkflowRef() *WorkflowRef {
	return &WorkflowRef{}
}

func (p *WorkflowRef) InitDefault() {
}

func (p *WorkflowRef) GetId() (v string) {
	return p.Id
}

func (p *WorkflowRef) GetDigest() (v string) {
	return p.Digest
}

func (p *WorkflowRef) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WorkflowRef(%+v)", *p)
}

func (p *WorkflowRef) DeepEqual(ano *WorkflowRef) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field3DeepEqual(ano.Digest) {
		return false
	}
	return true
}

func (p *WorkflowRef) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *WorkflowRef) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Digest, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_WorkflowRef = map[int16]string{
	1: "id",
	3: "digest",
}

type DriftNotice struct {
	Components []string `thrift:"components,1,required,list<string>" json:"components"`
	Command    string   `thrift:"command,2,required" json:"command"`
}

func NewDriftNotice() *DriftNotice {
	return &DriftNotice{}
}

func (p *DriftNotice) InitDefault() {
}

func (p *DriftNotice) GetComponents() (v []string) {
	return p.Components
}

func (p *DriftNotice) GetCommand() (v string) {
	return p.Command
}

func (p *DriftNotice) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DriftNotice(%+v)", *p)
}

func (p *DriftNotice) DeepEqual(ano *DriftNotice) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Components) {
		return false
	}
	if !p.Field2DeepEqual(ano.Command) {
		return false
	}
	return true
}

func (p *DriftNotice) Field1DeepEqual(src []string) bool {

	if len(p.Components) != len(src) {
		return false
	}
	for i, v := range p.Components {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *DriftNotice) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Command, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_DriftNotice = map[int16]string{
	1: "components",
	2: "command",
}

type Notice struct {
	// Field 1 is retired with UpdateNotice and must not be reused.
	Drift *DriftNotice `thrift:"drift,2,optional" json:"drift,omitempty"`
}

func NewNotice() *Notice {
	return &Notice{}
}

func (p *Notice) InitDefault() {
}

var Notice_Drift_DEFAULT *DriftNotice

func (p *Notice) GetDrift() (v *DriftNotice) {
	if !p.IsSetDrift() {
		return Notice_Drift_DEFAULT
	}
	return p.Drift
}

func (p *Notice) IsSetDrift() bool {
	return p.Drift != nil
}

func (p *Notice) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Notice(%+v)", *p)
}

func (p *Notice) DeepEqual(ano *Notice) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field2DeepEqual(ano.Drift) {
		return false
	}
	return true
}

func (p *Notice) Field2DeepEqual(src *DriftNotice) bool {

	if !p.Drift.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_Notice = map[int16]string{
	2: "drift",
}

// JsonValue is encoded as natural JSON by commonidl/json_value.go.
type JsonValue struct {
	NullValue    *bool                 `thrift:"null_value,1,optional" json:"null_value,omitempty"`
	StringValue  *string               `thrift:"string_value,2,optional" json:"string_value,omitempty"`
	BoolValue    *bool                 `thrift:"bool_value,3,optional" json:"bool_value,omitempty"`
	IntegerValue *int64                `thrift:"integer_value,4,optional" json:"integer_value,omitempty"`
	NumberValue  *float64              `thrift:"number_value,5,optional" json:"number_value,omitempty"`
	ListValue    []*JsonValue          `thrift:"list_value,6,optional,list<JsonValue>" json:"list_value,omitempty"`
	ObjectValue  map[string]*JsonValue `thrift:"object_value,7,optional" json:"object_value,omitempty"`
}

func NewJsonValue() *JsonValue {
	return &JsonValue{}
}

func (p *JsonValue) InitDefault() {
}

var JsonValue_NullValue_DEFAULT bool

func (p *JsonValue) GetNullValue() (v bool) {
	if !p.IsSetNullValue() {
		return JsonValue_NullValue_DEFAULT
	}
	return *p.NullValue
}

var JsonValue_StringValue_DEFAULT string

func (p *JsonValue) GetStringValue() (v string) {
	if !p.IsSetStringValue() {
		return JsonValue_StringValue_DEFAULT
	}
	return *p.StringValue
}

var JsonValue_BoolValue_DEFAULT bool

func (p *JsonValue) GetBoolValue() (v bool) {
	if !p.IsSetBoolValue() {
		return JsonValue_BoolValue_DEFAULT
	}
	return *p.BoolValue
}

var JsonValue_IntegerValue_DEFAULT int64

func (p *JsonValue) GetIntegerValue() (v int64) {
	if !p.IsSetIntegerValue() {
		return JsonValue_IntegerValue_DEFAULT
	}
	return *p.IntegerValue
}

var JsonValue_NumberValue_DEFAULT float64

func (p *JsonValue) GetNumberValue() (v float64) {
	if !p.IsSetNumberValue() {
		return JsonValue_NumberValue_DEFAULT
	}
	return *p.NumberValue
}

var JsonValue_ListValue_DEFAULT []*JsonValue

func (p *JsonValue) GetListValue() (v []*JsonValue) {
	if !p.IsSetListValue() {
		return JsonValue_ListValue_DEFAULT
	}
	return p.ListValue
}

var JsonValue_ObjectValue_DEFAULT map[string]*JsonValue

func (p *JsonValue) GetObjectValue() (v map[string]*JsonValue) {
	if !p.IsSetObjectValue() {
		return JsonValue_ObjectValue_DEFAULT
	}
	return p.ObjectValue
}

func (p *JsonValue) CountSetFieldsJsonValue() int {
	count := 0
	if p.IsSetNullValue() {
		count++
	}
	if p.IsSetStringValue() {
		count++
	}
	if p.IsSetBoolValue() {
		count++
	}
	if p.IsSetIntegerValue() {
		count++
	}
	if p.IsSetNumberValue() {
		count++
	}
	if p.IsSetListValue() {
		count++
	}
	if p.IsSetObjectValue() {
		count++
	}
	return count
}

func (p *JsonValue) IsSetNullValue() bool {
	return p.NullValue != nil
}

func (p *JsonValue) IsSetStringValue() bool {
	return p.StringValue != nil
}

func (p *JsonValue) IsSetBoolValue() bool {
	return p.BoolValue != nil
}

func (p *JsonValue) IsSetIntegerValue() bool {
	return p.IntegerValue != nil
}

func (p *JsonValue) IsSetNumberValue() bool {
	return p.NumberValue != nil
}

func (p *JsonValue) IsSetListValue() bool {
	return p.ListValue != nil
}

func (p *JsonValue) IsSetObjectValue() bool {
	return p.ObjectValue != nil
}

func (p *JsonValue) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JsonValue(%+v)", *p)
}

func (p *JsonValue) DeepEqual(ano *JsonValue) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.NullValue) {
		return false
	}
	if !p.Field2DeepEqual(ano.StringValue) {
		return false
	}
	if !p.Field3DeepEqual(ano.BoolValue) {
		return false
	}
	if !p.Field4DeepEqual(ano.IntegerValue) {
		return false
	}
	if !p.Field5DeepEqual(ano.NumberValue) {
		return false
	}
	if !p.Field6DeepEqual(ano.ListValue) {
		return false
	}
	if !p.Field7DeepEqual(ano.ObjectValue) {
		return false
	}
	return true
}

func (p *JsonValue) Field1DeepEqual(src *bool) bool {

	if p.NullValue == src {
		return true
	} else if p.NullValue == nil || src == nil {
		return false
	}
	if *p.NullValue != *src {
		return false
	}
	return true
}
func (p *JsonValue) Field2DeepEqual(src *string) bool {

	if p.StringValue == src {
		return true
	} else if p.StringValue == nil || src == nil {
		return false
	}
	if strings.Compare(*p.StringValue, *src) != 0 {
		return false
	}
	return true
}
func (p *JsonValue) Field3DeepEqual(src *bool) bool {

	if p.BoolValue == src {
		return true
	} else if p.BoolValue == nil || src == nil {
		return false
	}
	if *p.BoolValue != *src {
		return false
	}
	return true
}
func (p *JsonValue) Field4DeepEqual(src *int64) bool {

	if p.IntegerValue == src {
		return true
	} else if p.IntegerValue == nil || src == nil {
		return false
	}
	if *p.IntegerValue != *src {
		return false
	}
	return true
}
func (p *JsonValue) Field5DeepEqual(src *float64) bool {

	if p.NumberValue == src {
		return true
	} else if p.NumberValue == nil || src == nil {
		return false
	}
	if *p.NumberValue != *src {
		return false
	}
	return true
}
func (p *JsonValue) Field6DeepEqual(src []*JsonValue) bool {

	if len(p.ListValue) != len(src) {
		return false
	}
	for i, v := range p.ListValue {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *JsonValue) Field7DeepEqual(src map[string]*JsonValue) bool {

	if len(p.ObjectValue) != len(src) {
		return false
	}
	for k, v := range p.ObjectValue {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_JsonValue = map[int16]string{
	1: "null_value",
	2: "string_value",
	3: "bool_value",
	4: "integer_value",
	5: "number_value",
	6: "list_value",
	7: "object_value",
}
