// Code generated by Validator v0.2.5. DO NOT EDIT.

package commonidl

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *WorkflowRef) IsValid() error {
	if len(p.Id) < int(1) {
		return fmt.Errorf("field Id min_len rule failed, current value: %d", len(p.Id))
	}
	if len(p.Digest) < int(1) {
		return fmt.Errorf("field Digest min_len rule failed, current value: %d", len(p.Digest))
	}
	return nil
}
func (p *DriftNotice) IsValid() error {
	return nil
}
func (p *Notice) IsValid() error {
	if p.Drift != nil {
		if err := p.Drift.IsValid(); err != nil {
			return fmt.Errorf("field Drift not valid, %w", err)
		}
	}
	return nil
}
func (p *JsonValue) IsValid() error {
	return nil
}
