// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package opsidl

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/zeefan1555/commonloop/internal/idl/erroridl"
	"strings"
)

type DoctorScope int64

const (
	DoctorScope_unspecified  DoctorScope = 0
	DoctorScope_installation DoctorScope = 1
	DoctorScope_requirement  DoctorScope = 2
)

func (p DoctorScope) String() string {
	switch p {
	case DoctorScope_unspecified:
		return "unspecified"
	case DoctorScope_installation:
		return "installation"
	case DoctorScope_requirement:
		return "requirement"
	}
	return "<UNSET>"
}

func DoctorScopeFromString(s string) (DoctorScope, error) {
	switch s {
	case "unspecified":
		return DoctorScope_unspecified, nil
	case "installation":
		return DoctorScope_installation, nil
	case "requirement":
		return DoctorScope_requirement, nil
	}
	return DoctorScope(0), fmt.Errorf("not a valid DoctorScope string")
}

func DoctorScopePtr(v DoctorScope) *DoctorScope { return &v }

func (p DoctorScope) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *DoctorScope) UnmarshalText(text []byte) error {
	q, err := DoctorScopeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *DoctorScope) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = DoctorScope(result.Int64)
	return
}

func (p *DoctorScope) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type DoctorStatus int64

const (
	DoctorStatus_unspecified DoctorStatus = 0
	DoctorStatus_healthy     DoctorStatus = 1
	DoctorStatus_warning     DoctorStatus = 2
	DoctorStatus_unhealthy   DoctorStatus = 3
)

func (p DoctorStatus) String() string {
	switch p {
	case DoctorStatus_unspecified:
		return "unspecified"
	case DoctorStatus_healthy:
		return "healthy"
	case DoctorStatus_warning:
		return "warning"
	case DoctorStatus_unhealthy:
		return "unhealthy"
	}
	return "<UNSET>"
}

func DoctorStatusFromString(s string) (DoctorStatus, error) {
	switch s {
	case "unspecified":
		return DoctorStatus_unspecified, nil
	case "healthy":
		return DoctorStatus_healthy, nil
	case "warning":
		return DoctorStatus_warning, nil
	case "unhealthy":
		return DoctorStatus_unhealthy, nil
	}
	return DoctorStatus(0), fmt.Errorf("not a valid DoctorStatus string")
}

func DoctorStatusPtr(v DoctorStatus) *DoctorStatus { return &v }

func (p DoctorStatus) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *DoctorStatus) UnmarshalText(text []byte) error {
	q, err := DoctorStatusFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *DoctorStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = DoctorStatus(result.Int64)
	return
}

func (p *DoctorStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type DoctorCheckStatus int64

const (
	DoctorCheckStatus_unspecified DoctorCheckStatus = 0
	DoctorCheckStatus_passed      DoctorCheckStatus = 1
	DoctorCheckStatus_warning     DoctorCheckStatus = 2
	DoctorCheckStatus_failed      DoctorCheckStatus = 3
	DoctorCheckStatus_skipped     DoctorCheckStatus = 4
)

func (p DoctorCheckStatus) String() string {
	switch p {
	case DoctorCheckStatus_unspecified:
		return "unspecified"
	case DoctorCheckStatus_passed:
		return "passed"
	case DoctorCheckStatus_warning:
		return "warning"
	case DoctorCheckStatus_failed:
		return "failed"
	case DoctorCheckStatus_skipped:
		return "skipped"
	}
	return "<UNSET>"
}

func DoctorCheckStatusFromString(s string) (DoctorCheckStatus, error) {
	switch s {
	case "unspecified":
		return DoctorCheckStatus_unspecified, nil
	case "passed":
		return DoctorCheckStatus_passed, nil
	case "warning":
		return DoctorCheckStatus_warning, nil
	case "failed":
		return DoctorCheckStatus_failed, nil
	case "skipped":
		return DoctorCheckStatus_skipped, nil
	}
	return DoctorCheckStatus(0), fmt.Errorf("not a valid DoctorCheckStatus string")
}

func DoctorCheckStatusPtr(v DoctorCheckStatus) *DoctorCheckStatus { return &v }

func (p DoctorCheckStatus) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *DoctorCheckStatus) UnmarshalText(text []byte) error {
	q, err := DoctorCheckStatusFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *DoctorCheckStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = DoctorCheckStatus(result.Int64)
	return
}

func (p *DoctorCheckStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type VersionRequest struct {
}

func NewVersionRequest() *VersionRequest {
	return &VersionRequest{}
}

func (p *VersionRequest) InitDefault() {
}

func (p *VersionRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VersionRequest(%+v)", *p)
}

func (p *VersionRequest) DeepEqual(ano *VersionRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

var fieldIDToName_VersionRequest = map[int16]string{}

type StateSchemaSupport struct {
	ReadVersions []int32 `thrift:"read_versions,1,required,list<i32>" json:"read_versions"`
	WriteVersion int32   `thrift:"write_version,2,required" json:"write_version"`
}

func NewStateSchemaSupport() *StateSchemaSupport {
	return &StateSchemaSupport{}
}

func (p *StateSchemaSupport) InitDefault() {
}

func (p *StateSchemaSupport) GetReadVersions() (v []int32) {
	return p.ReadVersions
}

func (p *StateSchemaSupport) GetWriteVersion() (v int32) {
	return p.WriteVersion
}

func (p *StateSchemaSupport) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StateSchemaSupport(%+v)", *p)
}

func (p *StateSchemaSupport) DeepEqual(ano *StateSchemaSupport) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.ReadVersions) {
		return false
	}
	if !p.Field2DeepEqual(ano.WriteVersion) {
		return false
	}
	return true
}

func (p *StateSchemaSupport) Field1DeepEqual(src []int32) bool {

	if len(p.ReadVersions) != len(src) {
		return false
	}
	for i, v := range p.ReadVersions {
		_src := src[i]
		if v != _src {
			return false
		}
	}
	return true
}
func (p *StateSchemaSupport) Field2DeepEqual(src int32) bool {

	if p.WriteVersion != src {
		return false
	}
	return true
}

var fieldIDToName_StateSchemaSupport = map[int16]string{
	1: "read_versions",
	2: "write_version",
}

type SkillRelease struct {
	Name    string `thrift:"name,1,required" json:"name"`
	Version string `thrift:"version,2,required" json:"version"`
}

func NewSkillRelease() *SkillRelease {
	return &SkillRelease{}
}

func (p *SkillRelease) InitDefault() {
}

func (p *SkillRelease) GetName() (v string) {
	return p.Name
}

func (p *SkillRelease) GetVersion() (v string) {
	return p.Version
}

func (p *SkillRelease) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SkillRelease(%+v)", *p)
}

func (p *SkillRelease) DeepEqual(ano *SkillRelease) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Name) {
		return false
	}
	if !p.Field2DeepEqual(ano.Version) {
		return false
	}
	return true
}

func (p *SkillRelease) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Name, src) != 0 {
		return false
	}
	return true
}
func (p *SkillRelease) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Version, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_SkillRelease = map[int16]string{
	1: "name",
	2: "version",
}

type WorkflowRelease struct {
	Id string `thrift:"id,1,required" json:"id"`
	// fields 2 and 3 retired: Workflow has no business version or default.
	Digest string `thrift:"digest,4,required" json:"digest"`
}

func NewWorkflowRelease() *WorkflowRelease {
	return &WorkflowRelease{}
}

func (p *WorkflowRelease) InitDefault() {
}

func (p *WorkflowRelease) GetId() (v string) {
	return p.Id
}

func (p *WorkflowRelease) GetDigest() (v string) {
	return p.Digest
}

func (p *WorkflowRelease) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WorkflowRelease(%+v)", *p)
}

func (p *WorkflowRelease) DeepEqual(ano *WorkflowRelease) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field4DeepEqual(ano.Digest) {
		return false
	}
	return true
}

func (p *WorkflowRelease) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *WorkflowRelease) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Digest, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_WorkflowRelease = map[int16]string{
	1: "id",
	4: "digest",
}

type VersionResponse struct {
	ReleaseVersion string              `thrift:"release_version,1,required" json:"release_version"`
	CommitSha      string              `thrift:"commit_sha,2,required" json:"commit_sha"`
	StateSchema    *StateSchemaSupport `thrift:"state_schema,3,required" json:"state_schema"`
	Skills         []*SkillRelease     `thrift:"skills,4,required,list<SkillRelease>" json:"skills"`
	Workflows      []*WorkflowRelease  `thrift:"workflows,5,required,list<WorkflowRelease>" json:"workflows"`
}

func NewVersionResponse() *VersionResponse {
	return &VersionResponse{}
}

func (p *VersionResponse) InitDefault() {
}

func (p *VersionResponse) GetReleaseVersion() (v string) {
	return p.ReleaseVersion
}

func (p *VersionResponse) GetCommitSha() (v string) {
	return p.CommitSha
}

var VersionResponse_StateSchema_DEFAULT *StateSchemaSupport

func (p *VersionResponse) GetStateSchema() (v *StateSchemaSupport) {
	if !p.IsSetStateSchema() {
		return VersionResponse_StateSchema_DEFAULT
	}
	return p.StateSchema
}

func (p *VersionResponse) GetSkills() (v []*SkillRelease) {
	return p.Skills
}

func (p *VersionResponse) GetWorkflows() (v []*WorkflowRelease) {
	return p.Workflows
}

func (p *VersionResponse) IsSetStateSchema() bool {
	return p.StateSchema != nil
}

func (p *VersionResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VersionResponse(%+v)", *p)
}

func (p *VersionResponse) DeepEqual(ano *VersionResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.ReleaseVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.CommitSha) {
		return false
	}
	if !p.Field3DeepEqual(ano.StateSchema) {
		return false
	}
	if !p.Field4DeepEqual(ano.Skills) {
		return false
	}
	if !p.Field5DeepEqual(ano.Workflows) {
		return false
	}
	return true
}

func (p *VersionResponse) Field1DeepEqual(src string) bool {

	if strings.Compare(p.ReleaseVersion, src) != 0 {
		return false
	}
	return true
}
func (p *VersionResponse) Field2DeepEqual(src string) bool {

	if strings.Compare(p.CommitSha, src) != 0 {
		return false
	}
	return true
}
func (p *VersionResponse) Field3DeepEqual(src *StateSchemaSupport) bool {

	if !p.StateSchema.DeepEqual(src) {
		return false
	}
	return true
}
func (p *VersionResponse) Field4DeepEqual(src []*SkillRelease) bool {

	if len(p.Skills) != len(src) {
		return false
	}
	for i, v := range p.Skills {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *VersionResponse) Field5DeepEqual(src []*WorkflowRelease) bool {

	if len(p.Workflows) != len(src) {
		return false
	}
	for i, v := range p.Workflows {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_VersionResponse = map[int16]string{
	1: "release_version",
	2: "commit_sha",
	3: "state_schema",
	4: "skills",
	5: "workflows",
}

type DoctorRequest struct {
}

func NewDoctorRequest() *DoctorRequest {
	return &DoctorRequest{}
}

func (p *DoctorRequest) InitDefault() {
}

func (p *DoctorRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DoctorRequest(%+v)", *p)
}

func (p *DoctorRequest) DeepEqual(ano *DoctorRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

var fieldIDToName_DoctorRequest = map[int16]string{}

type DoctorCheck struct {
	Id      string            `thrift:"id,1,required" json:"id"`
	Status  DoctorCheckStatus `thrift:"status,2,required,DoctorCheckStatus" json:"status"`
	Summary string            `thrift:"summary,3,required" json:"summary"`
	Hint    *string           `thrift:"hint,4,optional" json:"hint,omitempty"`
}

func NewDoctorCheck() *DoctorCheck {
	return &DoctorCheck{}
}

func (p *DoctorCheck) InitDefault() {
}

func (p *DoctorCheck) GetId() (v string) {
	return p.Id
}

func (p *DoctorCheck) GetStatus() (v DoctorCheckStatus) {
	return p.Status
}

func (p *DoctorCheck) GetSummary() (v string) {
	return p.Summary
}

var DoctorCheck_Hint_DEFAULT string

func (p *DoctorCheck) GetHint() (v string) {
	if !p.IsSetHint() {
		return DoctorCheck_Hint_DEFAULT
	}
	return *p.Hint
}

func (p *DoctorCheck) IsSetHint() bool {
	return p.Hint != nil
}

func (p *DoctorCheck) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DoctorCheck(%+v)", *p)
}

func (p *DoctorCheck) DeepEqual(ano *DoctorCheck) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.Status) {
		return false
	}
	if !p.Field3DeepEqual(ano.Summary) {
		return false
	}
	if !p.Field4DeepEqual(ano.Hint) {
		return false
	}
	return true
}

func (p *DoctorCheck) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *DoctorCheck) Field2DeepEqual(src DoctorCheckStatus) bool {

	if p.Status != src {
		return false
	}
	return true
}
func (p *DoctorCheck) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Summary, src) != 0 {
		return false
	}
	return true
}
func (p *DoctorCheck) Field4DeepEqual(src *string) bool {

	if p.Hint == src {
		return true
	} else if p.Hint == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Hint, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_DoctorCheck = map[int16]string{
	1: "id",
	2: "status",
	3: "summary",
	4: "hint",
}

type DoctorResponse struct {
	Scope  DoctorScope    `thrift:"scope,1,required,DoctorScope" json:"scope"`
	Status DoctorStatus   `thrift:"status,2,required,DoctorStatus" json:"status"`
	Checks []*DoctorCheck `thrift:"checks,3,required,list<DoctorCheck>" json:"checks"`
}

func NewDoctorResponse() *DoctorResponse {
	return &DoctorResponse{}
}

func (p *DoctorResponse) InitDefault() {
}

func (p *DoctorResponse) GetScope() (v DoctorScope) {
	return p.Scope
}

func (p *DoctorResponse) GetStatus() (v DoctorStatus) {
	return p.Status
}

func (p *DoctorResponse) GetChecks() (v []*DoctorCheck) {
	return p.Checks
}

func (p *DoctorResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DoctorResponse(%+v)", *p)
}

func (p *DoctorResponse) DeepEqual(ano *DoctorResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Scope) {
		return false
	}
	if !p.Field2DeepEqual(ano.Status) {
		return false
	}
	if !p.Field3DeepEqual(ano.Checks) {
		return false
	}
	return true
}

func (p *DoctorResponse) Field1DeepEqual(src DoctorScope) bool {

	if p.Scope != src {
		return false
	}
	return true
}
func (p *DoctorResponse) Field2DeepEqual(src DoctorStatus) bool {

	if p.Status != src {
		return false
	}
	return true
}
func (p *DoctorResponse) Field3DeepEqual(src []*DoctorCheck) bool {

	if len(p.Checks) != len(src) {
		return false
	}
	for i, v := range p.Checks {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_DoctorResponse = map[int16]string{
	1: "scope",
	2: "status",
	3: "checks",
}

type OpsService interface {
	Version(ctx context.Context, request *VersionRequest) (r *VersionResponse, err error)

	Doctor(ctx context.Context, requirementRoot string, request *DoctorRequest) (r *DoctorResponse, err error)
}

type OpsServiceVersionArgs struct {
	Request *VersionRequest `thrift:"request,1,required" json:"request"`
}

func NewOpsServiceVersionArgs() *OpsServiceVersionArgs {
	return &OpsServiceVersionArgs{}
}

func (p *OpsServiceVersionArgs) InitDefault() {
}

var OpsServiceVersionArgs_Request_DEFAULT *VersionRequest

func (p *OpsServiceVersionArgs) GetRequest() (v *VersionRequest) {
	if !p.IsSetRequest() {
		return OpsServiceVersionArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *OpsServiceVersionArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OpsServiceVersionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OpsServiceVersionArgs(%+v)", *p)
}

func (p *OpsServiceVersionArgs) DeepEqual(ano *OpsServiceVersionArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Request) {
		return false
	}
	return true
}

func (p *OpsServiceVersionArgs) Field1DeepEqual(src *VersionRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_OpsServiceVersionArgs = map[int16]string{
	1: "request",
}

type OpsServiceVersionResult struct {
	Success *VersionResponse      `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewOpsServiceVersionResult() *OpsServiceVersionResult {
	return &OpsServiceVersionResult{}
}

func (p *OpsServiceVersionResult) InitDefault() {
}

var OpsServiceVersionResult_Success_DEFAULT *VersionResponse

func (p *OpsServiceVersionResult) GetSuccess() (v *VersionResponse) {
	if !p.IsSetSuccess() {
		return OpsServiceVersionResult_Success_DEFAULT
	}
	return p.Success
}

var OpsServiceVersionResult_Error_DEFAULT *erroridl.PublicError

func (p *OpsServiceVersionResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return OpsServiceVersionResult_Error_DEFAULT
	}
	return p.Error
}

func (p *OpsServiceVersionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OpsServiceVersionResult) IsSetError() bool {
	return p.Error != nil
}

func (p *OpsServiceVersionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OpsServiceVersionResult(%+v)", *p)
}

func (p *OpsServiceVersionResult) DeepEqual(ano *OpsServiceVersionResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *OpsServiceVersionResult) Field0DeepEqual(src *VersionResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *OpsServiceVersionResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_OpsServiceVersionResult = map[int16]string{
	0: "success",
	1: "error",
}

type OpsServiceDoctorArgs struct {
	RequirementRoot string         `thrift:"requirement_root,1" json:"requirement_root"`
	Request         *DoctorRequest `thrift:"request,2,required" json:"request"`
}

func NewOpsServiceDoctorArgs() *OpsServiceDoctorArgs {
	return &OpsServiceDoctorArgs{}
}

func (p *OpsServiceDoctorArgs) InitDefault() {
}

func (p *OpsServiceDoctorArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var OpsServiceDoctorArgs_Request_DEFAULT *DoctorRequest

func (p *OpsServiceDoctorArgs) GetRequest() (v *DoctorRequest) {
	if !p.IsSetRequest() {
		return OpsServiceDoctorArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *OpsServiceDoctorArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *OpsServiceDoctorArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OpsServiceDoctorArgs(%+v)", *p)
}

func (p *OpsServiceDoctorArgs) DeepEqual(ano *OpsServiceDoctorArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	return true
}

func (p *OpsServiceDoctorArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *OpsServiceDoctorArgs) Field2DeepEqual(src *DoctorRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_OpsServiceDoctorArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
}

type OpsServiceDoctorResult struct {
	Success *DoctorResponse       `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewOpsServiceDoctorResult() *OpsServiceDoctorResult {
	return &OpsServiceDoctorResult{}
}

func (p *OpsServiceDoctorResult) InitDefault() {
}

var OpsServiceDoctorResult_Success_DEFAULT *DoctorResponse

func (p *OpsServiceDoctorResult) GetSuccess() (v *DoctorResponse) {
	if !p.IsSetSuccess() {
		return OpsServiceDoctorResult_Success_DEFAULT
	}
	return p.Success
}

var OpsServiceDoctorResult_Error_DEFAULT *erroridl.PublicError

func (p *OpsServiceDoctorResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return OpsServiceDoctorResult_Error_DEFAULT
	}
	return p.Error
}

func (p *OpsServiceDoctorResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OpsServiceDoctorResult) IsSetError() bool {
	return p.Error != nil
}

func (p *OpsServiceDoctorResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OpsServiceDoctorResult(%+v)", *p)
}

func (p *OpsServiceDoctorResult) DeepEqual(ano *OpsServiceDoctorResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *OpsServiceDoctorResult) Field0DeepEqual(src *DoctorResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *OpsServiceDoctorResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_OpsServiceDoctorResult = map[int16]string{
	0: "success",
	1: "error",
}

// exceptions of methods in OpsService.
var (
	_ error = (*erroridl.PublicError)(nil)
)
