// Code generated by Validator v0.2.5. DO NOT EDIT.

package opsidl

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *VersionRequest) IsValid() error {
	return nil
}
func (p *StateSchemaSupport) IsValid() error {
	return nil
}
func (p *SkillRelease) IsValid() error {
	return nil
}
func (p *WorkflowRelease) IsValid() error {
	_src := "^sha256:[0-9a-f]{64}$"
	if ok, _ := regexp.MatchString(_src, p.Digest); !ok {
		return fmt.Errorf("field Digest pattern rule failed, current value: %v", p.Digest)
	}
	return nil
}
func (p *VersionResponse) IsValid() error {
	if p.StateSchema == nil {
		return fmt.Errorf("field StateSchema not_nil rule failed")
	}
	if err := p.StateSchema.IsValid(); err != nil {
		return fmt.Errorf("field StateSchema not valid, %w", err)
	}
	return nil
}
func (p *DoctorRequest) IsValid() error {
	return nil
}
func (p *DoctorCheck) IsValid() error {
	if p.Status.String() == "<UNSET>" {
		return fmt.Errorf("field Status defined_only rule failed")
	}
	_src := []DoctorCheckStatus{DoctorCheckStatus_unspecified}
	for _, src := range _src {
		if p.Status == src {
			return fmt.Errorf("field Status not_in rule failed, current value: %v", p.Status)
		}
	}
	return nil
}
func (p *DoctorResponse) IsValid() error {
	if p.Scope.String() == "<UNSET>" {
		return fmt.Errorf("field Scope defined_only rule failed")
	}
	_src := []DoctorScope{DoctorScope_unspecified}
	for _, src := range _src {
		if p.Scope == src {
			return fmt.Errorf("field Scope not_in rule failed, current value: %v", p.Scope)
		}
	}
	if p.Status.String() == "<UNSET>" {
		return fmt.Errorf("field Status defined_only rule failed")
	}
	_src1 := []DoctorStatus{DoctorStatus_unspecified}
	for _, src := range _src1 {
		if p.Status == src {
			return fmt.Errorf("field Status not_in rule failed, current value: %v", p.Status)
		}
	}
	return nil
}
