// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package yamlidl

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"strings"
)

const (
	// Workflow YAML authoring contract.
	//
	// This file owns the five Workflow YAML document shapes, their enums, stable
	// field IDs, and schema versions. It declares no public command or Service.
	WORKFLOW_SCHEMA_VERSION = 7

	FLOW_SCHEMA_VERSION = 4

	CONDITION_SCHEMA_VERSION = 2

	LOOP_SCHEMA_VERSION = 4

	PROMPT_SCHEMA_VERSION = 1

	PROMPT_FILE = "prompt.yaml"

	OUTPUT_SOURCE_TRACE_DOCUMENT_URL = "integration.trace.document_url"
)

type Executor int64

const (
	Executor_unspecified Executor = 0
	Executor_agent       Executor = 1
	Executor_human       Executor = 2
)

func (p Executor) String() string {
	switch p {
	case Executor_unspecified:
		return "unspecified"
	case Executor_agent:
		return "agent"
	case Executor_human:
		return "human"
	}
	return "<UNSET>"
}

func ExecutorFromString(s string) (Executor, error) {
	switch s {
	case "unspecified":
		return Executor_unspecified, nil
	case "agent":
		return Executor_agent, nil
	case "human":
		return Executor_human, nil
	}
	return Executor(0), fmt.Errorf("not a valid Executor string")
}

func ExecutorPtr(v Executor) *Executor { return &v }

func (p Executor) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *Executor) UnmarshalText(text []byte) error {
	q, err := ExecutorFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *Executor) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Executor(result.Int64)
	return
}

func (p *Executor) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OutputType int64

const (
	OutputType_unspecified OutputType = 0
	OutputType_string      OutputType = 1
	OutputType_boolean     OutputType = 2
	OutputType_integer     OutputType = 3
	OutputType_path        OutputType = 4
	OutputType_url         OutputType = 5
	OutputType_url_list    OutputType = 6
	OutputType_enum_value  OutputType = 7
	OutputType_object      OutputType = 8
)

func (p OutputType) String() string {
	switch p {
	case OutputType_unspecified:
		return "unspecified"
	case OutputType_string:
		return "string"
	case OutputType_boolean:
		return "boolean"
	case OutputType_integer:
		return "integer"
	case OutputType_path:
		return "path"
	case OutputType_url:
		return "url"
	case OutputType_url_list:
		return "url_list"
	case OutputType_enum_value:
		return "enum_value"
	case OutputType_object:
		return "object"
	}
	return "<UNSET>"
}

func OutputTypeFromString(s string) (OutputType, error) {
	switch s {
	case "unspecified":
		return OutputType_unspecified, nil
	case "string":
		return OutputType_string, nil
	case "boolean":
		return OutputType_boolean, nil
	case "integer":
		return OutputType_integer, nil
	case "path":
		return OutputType_path, nil
	case "url":
		return OutputType_url, nil
	case "url_list":
		return OutputType_url_list, nil
	case "enum_value":
		return OutputType_enum_value, nil
	case "object":
		return OutputType_object, nil
	}
	return OutputType(0), fmt.Errorf("not a valid OutputType string")
}

func OutputTypePtr(v OutputType) *OutputType { return &v }

func (p OutputType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *OutputType) UnmarshalText(text []byte) error {
	q, err := OutputTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *OutputType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OutputType(result.Int64)
	return
}

func (p *OutputType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Step struct {
	Id       string   `thrift:"id,1,required" yaml:"id" json:"id"`
	Name     string   `thrift:"name,2,required" yaml:"name" json:"name"`
	Executor Executor `thrift:"executor,3,required,Executor" yaml:"executor" json:"executor"`
}

func NewStep() *Step {
	return &Step{}
}

func (p *Step) InitDefault() {
}

func (p *Step) GetId() (v string) {
	return p.Id
}

func (p *Step) GetName() (v string) {
	return p.Name
}

func (p *Step) GetExecutor() (v Executor) {
	return p.Executor
}

func (p *Step) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Step(%+v)", *p)
}

func (p *Step) DeepEqual(ano *Step) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.Name) {
		return false
	}
	if !p.Field3DeepEqual(ano.Executor) {
		return false
	}
	return true
}

func (p *Step) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *Step) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Name, src) != 0 {
		return false
	}
	return true
}
func (p *Step) Field3DeepEqual(src Executor) bool {

	if p.Executor != src {
		return false
	}
	return true
}

var fieldIDToName_Step = map[int16]string{
	1: "id",
	2: "name",
	3: "executor",
}

type Job struct {
	Id    string  `thrift:"id,1,required" yaml:"id" json:"id"`
	Name  string  `thrift:"name,2,required" yaml:"name" json:"name"`
	Steps []*Step `thrift:"steps,3,required,list<Step>" yaml:"steps" json:"steps"`
}

func NewJob() *Job {
	return &Job{}
}

func (p *Job) InitDefault() {
}

func (p *Job) GetId() (v string) {
	return p.Id
}

func (p *Job) GetName() (v string) {
	return p.Name
}

func (p *Job) GetSteps() (v []*Step) {
	return p.Steps
}

func (p *Job) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Job(%+v)", *p)
}

func (p *Job) DeepEqual(ano *Job) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.Name) {
		return false
	}
	if !p.Field3DeepEqual(ano.Steps) {
		return false
	}
	return true
}

func (p *Job) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *Job) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Name, src) != 0 {
		return false
	}
	return true
}
func (p *Job) Field3DeepEqual(src []*Step) bool {

	if len(p.Steps) != len(src) {
		return false
	}
	for i, v := range p.Steps {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_Job = map[int16]string{
	1: "id",
	2: "name",
	3: "steps",
}

type Stage struct {
	Id   string `thrift:"id,1,required" yaml:"id" json:"id"`
	Name string `thrift:"name,2,required" yaml:"name" json:"name"`
	Jobs []*Job `thrift:"jobs,3,required,list<Job>" yaml:"jobs" json:"jobs"`
}

func NewStage() *Stage {
	return &Stage{}
}

func (p *Stage) InitDefault() {
}

func (p *Stage) GetId() (v string) {
	return p.Id
}

func (p *Stage) GetName() (v string) {
	return p.Name
}

func (p *Stage) GetJobs() (v []*Job) {
	return p.Jobs
}

func (p *Stage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Stage(%+v)", *p)
}

func (p *Stage) DeepEqual(ano *Stage) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.Name) {
		return false
	}
	if !p.Field3DeepEqual(ano.Jobs) {
		return false
	}
	return true
}

func (p *Stage) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *Stage) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Name, src) != 0 {
		return false
	}
	return true
}
func (p *Stage) Field3DeepEqual(src []*Job) bool {

	if len(p.Jobs) != len(src) {
		return false
	}
	for i, v := range p.Jobs {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_Stage = map[int16]string{
	1: "id",
	2: "name",
	3: "jobs",
}

type PromptRef struct {
	File     string `thrift:"file,1,required" yaml:"file" json:"file"`
	PromptId string `thrift:"prompt_id,2,required" yaml:"prompt_id" json:"prompt_id"`
}

func NewPromptRef() *PromptRef {
	return &PromptRef{}
}

func (p *PromptRef) InitDefault() {
}

func (p *PromptRef) GetFile() (v string) {
	return p.File
}

func (p *PromptRef) GetPromptId() (v string) {
	return p.PromptId
}

func (p *PromptRef) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PromptRef(%+v)", *p)
}

func (p *PromptRef) DeepEqual(ano *PromptRef) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.File) {
		return false
	}
	if !p.Field2DeepEqual(ano.PromptId) {
		return false
	}
	return true
}

func (p *PromptRef) Field1DeepEqual(src string) bool {

	if strings.Compare(p.File, src) != 0 {
		return false
	}
	return true
}
func (p *PromptRef) Field2DeepEqual(src string) bool {

	if strings.Compare(p.PromptId, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_PromptRef = map[int16]string{
	1: "file",
	2: "prompt_id",
}

type When struct {
	AnyOf [][]string `thrift:"any_of,1,required,list<list<string>>" yaml:"any_of" json:"any_of"`
}

func NewWhen() *When {
	return &When{}
}

func (p *When) InitDefault() {
}

func (p *When) GetAnyOf() (v [][]string) {
	return p.AnyOf
}

func (p *When) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("When(%+v)", *p)
}

func (p *When) DeepEqual(ano *When) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.AnyOf) {
		return false
	}
	return true
}

func (p *When) Field1DeepEqual(src [][]string) bool {

	if len(p.AnyOf) != len(src) {
		return false
	}
	for i, v := range p.AnyOf {
		_src := src[i]
		if len(v) != len(_src) {
			return false
		}
		for i, v := range v {
			_src1 := _src[i]
			if strings.Compare(v, _src1) != 0 {
				return false
			}
		}
	}
	return true
}

var fieldIDToName_When = map[int16]string{
	1: "any_of",
}

type FlowRoute struct {
	PromptRef  *PromptRef `thrift:"prompt_ref,1,required" yaml:"prompt_ref" json:"prompt_ref"`
	When       *When      `thrift:"when,2,required" yaml:"when" json:"when"`
	NextStepId *string    `thrift:"next_step_id,3,optional" yaml:"next_step_id,omitempty" json:"next_step_id,omitempty"`
	Terminal   *bool      `thrift:"terminal,4,optional" yaml:"terminal,omitempty" json:"terminal,omitempty"`
}

func NewFlowRoute() *FlowRoute {
	return &FlowRoute{}
}

func (p *FlowRoute) InitDefault() {
}

var FlowRoute_PromptRef_DEFAULT *PromptRef

func (p *FlowRoute) GetPromptRef() (v *PromptRef) {
	if !p.IsSetPromptRef() {
		return FlowRoute_PromptRef_DEFAULT
	}
	return p.PromptRef
}

var FlowRoute_When_DEFAULT *When

func (p *FlowRoute) GetWhen() (v *When) {
	if !p.IsSetWhen() {
		return FlowRoute_When_DEFAULT
	}
	return p.When
}

var FlowRoute_NextStepId_DEFAULT string

func (p *FlowRoute) GetNextStepId() (v string) {
	if !p.IsSetNextStepId() {
		return FlowRoute_NextStepId_DEFAULT
	}
	return *p.NextStepId
}

var FlowRoute_Terminal_DEFAULT bool

func (p *FlowRoute) GetTerminal() (v bool) {
	if !p.IsSetTerminal() {
		return FlowRoute_Terminal_DEFAULT
	}
	return *p.Terminal
}

func (p *FlowRoute) IsSetPromptRef() bool {
	return p.PromptRef != nil
}

func (p *FlowRoute) IsSetWhen() bool {
	return p.When != nil
}

func (p *FlowRoute) IsSetNextStepId() bool {
	return p.NextStepId != nil
}

func (p *FlowRoute) IsSetTerminal() bool {
	return p.Terminal != nil
}

func (p *FlowRoute) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowRoute(%+v)", *p)
}

func (p *FlowRoute) DeepEqual(ano *FlowRoute) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.PromptRef) {
		return false
	}
	if !p.Field2DeepEqual(ano.When) {
		return false
	}
	if !p.Field3DeepEqual(ano.NextStepId) {
		return false
	}
	if !p.Field4DeepEqual(ano.Terminal) {
		return false
	}
	return true
}

func (p *FlowRoute) Field1DeepEqual(src *PromptRef) bool {

	if !p.PromptRef.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowRoute) Field2DeepEqual(src *When) bool {

	if !p.When.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowRoute) Field3DeepEqual(src *string) bool {

	if p.NextStepId == src {
		return true
	} else if p.NextStepId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.NextStepId, *src) != 0 {
		return false
	}
	return true
}
func (p *FlowRoute) Field4DeepEqual(src *bool) bool {

	if p.Terminal == src {
		return true
	} else if p.Terminal == nil || src == nil {
		return false
	}
	if *p.Terminal != *src {
		return false
	}
	return true
}

var fieldIDToName_FlowRoute = map[int16]string{
	1: "prompt_ref",
	2: "when",
	3: "next_step_id",
	4: "terminal",
}

type LoopRoute struct {
	PromptRef  *PromptRef `thrift:"prompt_ref,1,required" yaml:"prompt_ref" json:"prompt_ref"`
	When       *When      `thrift:"when,2,required" yaml:"when" json:"when"`
	BackStepId string     `thrift:"back_step_id,3,required" yaml:"back_step_id" json:"back_step_id"`
}

func NewLoopRoute() *LoopRoute {
	return &LoopRoute{}
}

func (p *LoopRoute) InitDefault() {
}

var LoopRoute_PromptRef_DEFAULT *PromptRef

func (p *LoopRoute) GetPromptRef() (v *PromptRef) {
	if !p.IsSetPromptRef() {
		return LoopRoute_PromptRef_DEFAULT
	}
	return p.PromptRef
}

var LoopRoute_When_DEFAULT *When

func (p *LoopRoute) GetWhen() (v *When) {
	if !p.IsSetWhen() {
		return LoopRoute_When_DEFAULT
	}
	return p.When
}

func (p *LoopRoute) GetBackStepId() (v string) {
	return p.BackStepId
}

func (p *LoopRoute) IsSetPromptRef() bool {
	return p.PromptRef != nil
}

func (p *LoopRoute) IsSetWhen() bool {
	return p.When != nil
}

func (p *LoopRoute) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoopRoute(%+v)", *p)
}

func (p *LoopRoute) DeepEqual(ano *LoopRoute) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.PromptRef) {
		return false
	}
	if !p.Field2DeepEqual(ano.When) {
		return false
	}
	if !p.Field3DeepEqual(ano.BackStepId) {
		return false
	}
	return true
}

func (p *LoopRoute) Field1DeepEqual(src *PromptRef) bool {

	if !p.PromptRef.DeepEqual(src) {
		return false
	}
	return true
}
func (p *LoopRoute) Field2DeepEqual(src *When) bool {

	if !p.When.DeepEqual(src) {
		return false
	}
	return true
}
func (p *LoopRoute) Field3DeepEqual(src string) bool {

	if strings.Compare(p.BackStepId, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_LoopRoute = map[int16]string{
	1: "prompt_ref",
	2: "when",
	3: "back_step_id",
}

type OutputDefinition struct {
	Key         string     `thrift:"key,1,required" yaml:"key" json:"key"`
	Type        OutputType `thrift:"type,2,required,OutputType" yaml:"type" json:"type"`
	Source      *string    `thrift:"source,3,optional" yaml:"source,omitempty" json:"source,omitempty"`
	Description *string    `thrift:"description,4,optional" yaml:"description,omitempty" json:"description,omitempty"`
	Values      []string   `thrift:"values,5,optional,list<string>" yaml:"values,omitempty" json:"values,omitempty"`
	Minimum     *int64     `thrift:"minimum,6,optional" yaml:"minimum,omitempty" json:"minimum,omitempty"`
	Maximum     *int64     `thrift:"maximum,7,optional" yaml:"maximum,omitempty" json:"maximum,omitempty"`
	MinItems    *int32     `thrift:"min_items,8,optional" yaml:"min_items,omitempty" json:"min_items,omitempty"`
	MaxItems    *int32     `thrift:"max_items,9,optional" yaml:"max_items,omitempty" json:"max_items,omitempty"`
}

func NewOutputDefinition() *OutputDefinition {
	return &OutputDefinition{}
}

func (p *OutputDefinition) InitDefault() {
}

func (p *OutputDefinition) GetKey() (v string) {
	return p.Key
}

func (p *OutputDefinition) GetType() (v OutputType) {
	return p.Type
}

var OutputDefinition_Source_DEFAULT string

func (p *OutputDefinition) GetSource() (v string) {
	if !p.IsSetSource() {
		return OutputDefinition_Source_DEFAULT
	}
	return *p.Source
}

var OutputDefinition_Description_DEFAULT string

func (p *OutputDefinition) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return OutputDefinition_Description_DEFAULT
	}
	return *p.Description
}

var OutputDefinition_Values_DEFAULT []string

func (p *OutputDefinition) GetValues() (v []string) {
	if !p.IsSetValues() {
		return OutputDefinition_Values_DEFAULT
	}
	return p.Values
}

var OutputDefinition_Minimum_DEFAULT int64

func (p *OutputDefinition) GetMinimum() (v int64) {
	if !p.IsSetMinimum() {
		return OutputDefinition_Minimum_DEFAULT
	}
	return *p.Minimum
}

var OutputDefinition_Maximum_DEFAULT int64

func (p *OutputDefinition) GetMaximum() (v int64) {
	if !p.IsSetMaximum() {
		return OutputDefinition_Maximum_DEFAULT
	}
	return *p.Maximum
}

var OutputDefinition_MinItems_DEFAULT int32

func (p *OutputDefinition) GetMinItems() (v int32) {
	if !p.IsSetMinItems() {
		return OutputDefinition_MinItems_DEFAULT
	}
	return *p.MinItems
}

var OutputDefinition_MaxItems_DEFAULT int32

func (p *OutputDefinition) GetMaxItems() (v int32) {
	if !p.IsSetMaxItems() {
		return OutputDefinition_MaxItems_DEFAULT
	}
	return *p.MaxItems
}

func (p *OutputDefinition) IsSetSource() bool {
	return p.Source != nil
}

func (p *OutputDefinition) IsSetDescription() bool {
	return p.Description != nil
}

func (p *OutputDefinition) IsSetValues() bool {
	return p.Values != nil
}

func (p *OutputDefinition) IsSetMinimum() bool {
	return p.Minimum != nil
}

func (p *OutputDefinition) IsSetMaximum() bool {
	return p.Maximum != nil
}

func (p *OutputDefinition) IsSetMinItems() bool {
	return p.MinItems != nil
}

func (p *OutputDefinition) IsSetMaxItems() bool {
	return p.MaxItems != nil
}

func (p *OutputDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OutputDefinition(%+v)", *p)
}

func (p *OutputDefinition) DeepEqual(ano *OutputDefinition) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Key) {
		return false
	}
	if !p.Field2DeepEqual(ano.Type) {
		return false
	}
	if !p.Field3DeepEqual(ano.Source) {
		return false
	}
	if !p.Field4DeepEqual(ano.Description) {
		return false
	}
	if !p.Field5DeepEqual(ano.Values) {
		return false
	}
	if !p.Field6DeepEqual(ano.Minimum) {
		return false
	}
	if !p.Field7DeepEqual(ano.Maximum) {
		return false
	}
	if !p.Field8DeepEqual(ano.MinItems) {
		return false
	}
	if !p.Field9DeepEqual(ano.MaxItems) {
		return false
	}
	return true
}

func (p *OutputDefinition) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Key, src) != 0 {
		return false
	}
	return true
}
func (p *OutputDefinition) Field2DeepEqual(src OutputType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *OutputDefinition) Field3DeepEqual(src *string) bool {

	if p.Source == src {
		return true
	} else if p.Source == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Source, *src) != 0 {
		return false
	}
	return true
}
func (p *OutputDefinition) Field4DeepEqual(src *string) bool {

	if p.Description == src {
		return true
	} else if p.Description == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Description, *src) != 0 {
		return false
	}
	return true
}
func (p *OutputDefinition) Field5DeepEqual(src []string) bool {

	if len(p.Values) != len(src) {
		return false
	}
	for i, v := range p.Values {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *OutputDefinition) Field6DeepEqual(src *int64) bool {

	if p.Minimum == src {
		return true
	} else if p.Minimum == nil || src == nil {
		return false
	}
	if *p.Minimum != *src {
		return false
	}
	return true
}
func (p *OutputDefinition) Field7DeepEqual(src *int64) bool {

	if p.Maximum == src {
		return true
	} else if p.Maximum == nil || src == nil {
		return false
	}
	if *p.Maximum != *src {
		return false
	}
	return true
}
func (p *OutputDefinition) Field8DeepEqual(src *int32) bool {

	if p.MinItems == src {
		return true
	} else if p.MinItems == nil || src == nil {
		return false
	}
	if *p.MinItems != *src {
		return false
	}
	return true
}
func (p *OutputDefinition) Field9DeepEqual(src *int32) bool {

	if p.MaxItems == src {
		return true
	} else if p.MaxItems == nil || src == nil {
		return false
	}
	if *p.MaxItems != *src {
		return false
	}
	return true
}

var fieldIDToName_OutputDefinition = map[int16]string{
	1: "key",
	2: "type",
	3: "source",
	4: "description",
	5: "values",
	6: "minimum",
	7: "maximum",
	8: "min_items",
	9: "max_items",
}

type ConditionDefinition struct {
	PromptRef      *PromptRef        `thrift:"prompt_ref,1,required" yaml:"prompt_ref" json:"prompt_ref"`
	Output         *OutputDefinition `thrift:"output,2,required" yaml:"output" json:"output"`
	ExclusiveGroup *string           `thrift:"exclusive_group,3,optional" yaml:"exclusive_group,omitempty" json:"exclusive_group,omitempty"`
}

func NewConditionDefinition() *ConditionDefinition {
	return &ConditionDefinition{}
}

func (p *ConditionDefinition) InitDefault() {
}

var ConditionDefinition_PromptRef_DEFAULT *PromptRef

func (p *ConditionDefinition) GetPromptRef() (v *PromptRef) {
	if !p.IsSetPromptRef() {
		return ConditionDefinition_PromptRef_DEFAULT
	}
	return p.PromptRef
}

var ConditionDefinition_Output_DEFAULT *OutputDefinition

func (p *ConditionDefinition) GetOutput() (v *OutputDefinition) {
	if !p.IsSetOutput() {
		return ConditionDefinition_Output_DEFAULT
	}
	return p.Output
}

var ConditionDefinition_ExclusiveGroup_DEFAULT string

func (p *ConditionDefinition) GetExclusiveGroup() (v string) {
	if !p.IsSetExclusiveGroup() {
		return ConditionDefinition_ExclusiveGroup_DEFAULT
	}
	return *p.ExclusiveGroup
}

func (p *ConditionDefinition) IsSetPromptRef() bool {
	return p.PromptRef != nil
}

func (p *ConditionDefinition) IsSetOutput() bool {
	return p.Output != nil
}

func (p *ConditionDefinition) IsSetExclusiveGroup() bool {
	return p.ExclusiveGroup != nil
}

func (p *ConditionDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConditionDefinition(%+v)", *p)
}

func (p *ConditionDefinition) DeepEqual(ano *ConditionDefinition) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.PromptRef) {
		return false
	}
	if !p.Field2DeepEqual(ano.Output) {
		return false
	}
	if !p.Field3DeepEqual(ano.ExclusiveGroup) {
		return false
	}
	return true
}

func (p *ConditionDefinition) Field1DeepEqual(src *PromptRef) bool {

	if !p.PromptRef.DeepEqual(src) {
		return false
	}
	return true
}
func (p *ConditionDefinition) Field2DeepEqual(src *OutputDefinition) bool {

	if !p.Output.DeepEqual(src) {
		return false
	}
	return true
}
func (p *ConditionDefinition) Field3DeepEqual(src *string) bool {

	if p.ExclusiveGroup == src {
		return true
	} else if p.ExclusiveGroup == nil || src == nil {
		return false
	}
	if strings.Compare(*p.ExclusiveGroup, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_ConditionDefinition = map[int16]string{
	1: "prompt_ref",
	2: "output",
	3: "exclusive_group",
}

type SkillBinding struct {
	Id     string `thrift:"id,1,required" yaml:"id" json:"id"`
	Prompt string `thrift:"prompt,2,required" yaml:"prompt" json:"prompt"`
	// Optional at the Thrift layer so YAML omission remains distinguishable from
	// an explicit false. Bundle validation requires the field to be present.
	Optional *bool `thrift:"optional,3,optional" yaml:"optional" json:"optional,omitempty"`
}

func NewSkillBinding() *SkillBinding {
	return &SkillBinding{}
}

func (p *SkillBinding) InitDefault() {
}

func (p *SkillBinding) GetId() (v string) {
	return p.Id
}

func (p *SkillBinding) GetPrompt() (v string) {
	return p.Prompt
}

var SkillBinding_Optional_DEFAULT bool

func (p *SkillBinding) GetOptional() (v bool) {
	if !p.IsSetOptional() {
		return SkillBinding_Optional_DEFAULT
	}
	return *p.Optional
}

func (p *SkillBinding) IsSetOptional() bool {
	return p.Optional != nil
}

func (p *SkillBinding) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SkillBinding(%+v)", *p)
}

func (p *SkillBinding) DeepEqual(ano *SkillBinding) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.Prompt) {
		return false
	}
	if !p.Field3DeepEqual(ano.Optional) {
		return false
	}
	return true
}

func (p *SkillBinding) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *SkillBinding) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Prompt, src) != 0 {
		return false
	}
	return true
}
func (p *SkillBinding) Field3DeepEqual(src *bool) bool {

	if p.Optional == src {
		return true
	} else if p.Optional == nil || src == nil {
		return false
	}
	if *p.Optional != *src {
		return false
	}
	return true
}

var fieldIDToName_SkillBinding = map[int16]string{
	1: "id",
	2: "prompt",
	3: "optional",
}

type PromptDefinition struct {
	Prompt string          `thrift:"prompt,1,required" yaml:"prompt" json:"prompt"`
	Skills []*SkillBinding `thrift:"skills,2,required,list<SkillBinding>" yaml:"skills" json:"skills"`
}

func NewPromptDefinition() *PromptDefinition {
	return &PromptDefinition{}
}

func (p *PromptDefinition) InitDefault() {
}

func (p *PromptDefinition) GetPrompt() (v string) {
	return p.Prompt
}

func (p *PromptDefinition) GetSkills() (v []*SkillBinding) {
	return p.Skills
}

func (p *PromptDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PromptDefinition(%+v)", *p)
}

func (p *PromptDefinition) DeepEqual(ano *PromptDefinition) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Prompt) {
		return false
	}
	if !p.Field2DeepEqual(ano.Skills) {
		return false
	}
	return true
}

func (p *PromptDefinition) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Prompt, src) != 0 {
		return false
	}
	return true
}
func (p *PromptDefinition) Field2DeepEqual(src []*SkillBinding) bool {

	if len(p.Skills) != len(src) {
		return false
	}
	for i, v := range p.Skills {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_PromptDefinition = map[int16]string{
	1: "prompt",
	2: "skills",
}

type WorkflowDocument struct {
	SchemaVersion int32  `thrift:"schema_version,1,required" yaml:"schema_version" json:"schema_version"`
	Id            string `thrift:"id,2,required" yaml:"id" json:"id"`
	// field 3 retired: Workflow has no business version.
	Stages []*Stage `thrift:"stages,4,required,list<Stage>" yaml:"stages" json:"stages"`
}

func NewWorkflowDocument() *WorkflowDocument {
	return &WorkflowDocument{}
}

func (p *WorkflowDocument) InitDefault() {
}

func (p *WorkflowDocument) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

func (p *WorkflowDocument) GetId() (v string) {
	return p.Id
}

func (p *WorkflowDocument) GetStages() (v []*Stage) {
	return p.Stages
}

func (p *WorkflowDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("WorkflowDocument(%+v)", *p)
}

func (p *WorkflowDocument) DeepEqual(ano *WorkflowDocument) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.Id) {
		return false
	}
	if !p.Field4DeepEqual(ano.Stages) {
		return false
	}
	return true
}

func (p *WorkflowDocument) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *WorkflowDocument) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *WorkflowDocument) Field4DeepEqual(src []*Stage) bool {

	if len(p.Stages) != len(src) {
		return false
	}
	for i, v := range p.Stages {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_WorkflowDocument = map[int16]string{
	1: "schema_version",
	2: "id",
	4: "stages",
}

type FlowDocument struct {
	SchemaVersion int32                   `thrift:"schema_version,1,required" yaml:"schema_version" json:"schema_version"`
	Flow          map[string][]*FlowRoute `thrift:"flow,2,required,map<string:list<FlowRoute>>" yaml:"flow" json:"flow"`
}

func NewFlowDocument() *FlowDocument {
	return &FlowDocument{}
}

func (p *FlowDocument) InitDefault() {
}

func (p *FlowDocument) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

func (p *FlowDocument) GetFlow() (v map[string][]*FlowRoute) {
	return p.Flow
}

func (p *FlowDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowDocument(%+v)", *p)
}

func (p *FlowDocument) DeepEqual(ano *FlowDocument) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.Flow) {
		return false
	}
	return true
}

func (p *FlowDocument) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *FlowDocument) Field2DeepEqual(src map[string][]*FlowRoute) bool {

	if len(p.Flow) != len(src) {
		return false
	}
	for k, v := range p.Flow {
		_src := src[k]
		if len(v) != len(_src) {
			return false
		}
		for i, v := range v {
			_src1 := _src[i]
			if !v.DeepEqual(_src1) {
				return false
			}
		}
	}
	return true
}

var fieldIDToName_FlowDocument = map[int16]string{
	1: "schema_version",
	2: "flow",
}

type ConditionDocument struct {
	SchemaVersion int32                           `thrift:"schema_version,1,required" yaml:"schema_version" json:"schema_version"`
	Conditions    map[string]*ConditionDefinition `thrift:"conditions,2,required" yaml:"conditions" json:"conditions"`
}

func NewConditionDocument() *ConditionDocument {
	return &ConditionDocument{}
}

func (p *ConditionDocument) InitDefault() {
}

func (p *ConditionDocument) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

func (p *ConditionDocument) GetConditions() (v map[string]*ConditionDefinition) {
	return p.Conditions
}

func (p *ConditionDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConditionDocument(%+v)", *p)
}

func (p *ConditionDocument) DeepEqual(ano *ConditionDocument) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.Conditions) {
		return false
	}
	return true
}

func (p *ConditionDocument) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *ConditionDocument) Field2DeepEqual(src map[string]*ConditionDefinition) bool {

	if len(p.Conditions) != len(src) {
		return false
	}
	for k, v := range p.Conditions {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_ConditionDocument = map[int16]string{
	1: "schema_version",
	2: "conditions",
}

type LoopDocument struct {
	SchemaVersion int32                   `thrift:"schema_version,1,required" yaml:"schema_version" json:"schema_version"`
	Loop          map[string][]*LoopRoute `thrift:"loop,2,required,map<string:list<LoopRoute>>" yaml:"loop" json:"loop"`
}

func NewLoopDocument() *LoopDocument {
	return &LoopDocument{}
}

func (p *LoopDocument) InitDefault() {
}

func (p *LoopDocument) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

func (p *LoopDocument) GetLoop() (v map[string][]*LoopRoute) {
	return p.Loop
}

func (p *LoopDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoopDocument(%+v)", *p)
}

func (p *LoopDocument) DeepEqual(ano *LoopDocument) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.Loop) {
		return false
	}
	return true
}

func (p *LoopDocument) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *LoopDocument) Field2DeepEqual(src map[string][]*LoopRoute) bool {

	if len(p.Loop) != len(src) {
		return false
	}
	for k, v := range p.Loop {
		_src := src[k]
		if len(v) != len(_src) {
			return false
		}
		for i, v := range v {
			_src1 := _src[i]
			if !v.DeepEqual(_src1) {
				return false
			}
		}
	}
	return true
}

var fieldIDToName_LoopDocument = map[int16]string{
	1: "schema_version",
	2: "loop",
}

type PromptDocument struct {
	SchemaVersion int32                        `thrift:"schema_version,1,required" yaml:"schema_version" json:"schema_version"`
	Prompts       map[string]*PromptDefinition `thrift:"prompts,2,required" yaml:"prompts" json:"prompts"`
}

func NewPromptDocument() *PromptDocument {
	return &PromptDocument{}
}

func (p *PromptDocument) InitDefault() {
}

func (p *PromptDocument) GetSchemaVersion() (v int32) {
	return p.SchemaVersion
}

func (p *PromptDocument) GetPrompts() (v map[string]*PromptDefinition) {
	return p.Prompts
}

func (p *PromptDocument) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PromptDocument(%+v)", *p)
}

func (p *PromptDocument) DeepEqual(ano *PromptDocument) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.SchemaVersion) {
		return false
	}
	if !p.Field2DeepEqual(ano.Prompts) {
		return false
	}
	return true
}

func (p *PromptDocument) Field1DeepEqual(src int32) bool {

	if p.SchemaVersion != src {
		return false
	}
	return true
}
func (p *PromptDocument) Field2DeepEqual(src map[string]*PromptDefinition) bool {

	if len(p.Prompts) != len(src) {
		return false
	}
	for k, v := range p.Prompts {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_PromptDocument = map[int16]string{
	1: "schema_version",
	2: "prompts",
}
