// Code generated by Validator v0.2.5. DO NOT EDIT.

package yamlidl

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *Step) IsValid() error {
	if len(p.Id) < int(1) {
		return fmt.Errorf("field Id min_len rule failed, current value: %d", len(p.Id))
	}
	if len(p.Name) < int(1) {
		return fmt.Errorf("field Name min_len rule failed, current value: %d", len(p.Name))
	}
	if p.Executor.String() == "<UNSET>" {
		return fmt.Errorf("field Executor defined_only rule failed")
	}
	_src := []Executor{Executor_unspecified}
	for _, src := range _src {
		if p.Executor == src {
			return fmt.Errorf("field Executor not_in rule failed, current value: %v", p.Executor)
		}
	}
	return nil
}
func (p *Job) IsValid() error {
	if len(p.Id) < int(1) {
		return fmt.Errorf("field Id min_len rule failed, current value: %d", len(p.Id))
	}
	if len(p.Name) < int(1) {
		return fmt.Errorf("field Name min_len rule failed, current value: %d", len(p.Name))
	}
	return nil
}
func (p *Stage) IsValid() error {
	if len(p.Id) < int(1) {
		return fmt.Errorf("field Id min_len rule failed, current value: %d", len(p.Id))
	}
	if len(p.Name) < int(1) {
		return fmt.Errorf("field Name min_len rule failed, current value: %d", len(p.Name))
	}
	return nil
}
func (p *PromptRef) IsValid() error {
	if len(p.File) < int(1) {
		return fmt.Errorf("field File min_len rule failed, current value: %d", len(p.File))
	}
	if len(p.PromptId) < int(1) {
		return fmt.Errorf("field PromptId min_len rule failed, current value: %d", len(p.PromptId))
	}
	return nil
}
func (p *When) IsValid() error {
	if len(p.AnyOf) < int(1) {
		return fmt.Errorf("field AnyOf MinLen rule failed, current value: %v", p.AnyOf)
	}
	return nil
}
func (p *FlowRoute) IsValid() error {
	if p.PromptRef == nil {
		return fmt.Errorf("field PromptRef not_nil rule failed")
	}
	if err := p.PromptRef.IsValid(); err != nil {
		return fmt.Errorf("field PromptRef not valid, %w", err)
	}
	if p.When == nil {
		return fmt.Errorf("field When not_nil rule failed")
	}
	if err := p.When.IsValid(); err != nil {
		return fmt.Errorf("field When not valid, %w", err)
	}
	if p.NextStepId != nil {
		if len(*p.NextStepId) < int(1) {
			return fmt.Errorf("field NextStepId min_len rule failed, current value: %d", len(*p.NextStepId))
		}
	}
	return nil
}
func (p *LoopRoute) IsValid() error {
	if p.PromptRef == nil {
		return fmt.Errorf("field PromptRef not_nil rule failed")
	}
	if err := p.PromptRef.IsValid(); err != nil {
		return fmt.Errorf("field PromptRef not valid, %w", err)
	}
	if p.When == nil {
		return fmt.Errorf("field When not_nil rule failed")
	}
	if err := p.When.IsValid(); err != nil {
		return fmt.Errorf("field When not valid, %w", err)
	}
	if len(p.BackStepId) < int(1) {
		return fmt.Errorf("field BackStepId min_len rule failed, current value: %d", len(p.BackStepId))
	}
	return nil
}
func (p *OutputDefinition) IsValid() error {
	if len(p.Key) < int(1) {
		return fmt.Errorf("field Key min_len rule failed, current value: %d", len(p.Key))
	}
	if p.Type.String() == "<UNSET>" {
		return fmt.Errorf("field Type defined_only rule failed")
	}
	_src := []OutputType{OutputType_unspecified}
	for _, src := range _src {
		if p.Type == src {
			return fmt.Errorf("field Type not_in rule failed, current value: %v", p.Type)
		}
	}
	return nil
}
func (p *ConditionDefinition) IsValid() error {
	if p.PromptRef == nil {
		return fmt.Errorf("field PromptRef not_nil rule failed")
	}
	if err := p.PromptRef.IsValid(); err != nil {
		return fmt.Errorf("field PromptRef not valid, %w", err)
	}
	if p.Output == nil {
		return fmt.Errorf("field Output not_nil rule failed")
	}
	if err := p.Output.IsValid(); err != nil {
		return fmt.Errorf("field Output not valid, %w", err)
	}
	return nil
}
func (p *SkillBinding) IsValid() error {
	if len(p.Id) < int(1) {
		return fmt.Errorf("field Id min_len rule failed, current value: %d", len(p.Id))
	}
	if len(p.Prompt) < int(1) {
		return fmt.Errorf("field Prompt min_len rule failed, current value: %d", len(p.Prompt))
	}
	return nil
}
func (p *PromptDefinition) IsValid() error {
	if len(p.Prompt) < int(1) {
		return fmt.Errorf("field Prompt min_len rule failed, current value: %d", len(p.Prompt))
	}
	return nil
}
func (p *WorkflowDocument) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	if len(p.Id) < int(1) {
		return fmt.Errorf("field Id min_len rule failed, current value: %d", len(p.Id))
	}
	return nil
}
func (p *FlowDocument) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	return nil
}
func (p *ConditionDocument) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	return nil
}
func (p *LoopDocument) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	return nil
}
func (p *PromptDocument) IsValid() error {
	if p.SchemaVersion < int32(1) {
		return fmt.Errorf("field SchemaVersion ge rule failed, current value: %v", p.SchemaVersion)
	}
	return nil
}
