// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package flowidl

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/zeefan1555/commonloop/internal/idl/commonidl"
	"github.com/zeefan1555/commonloop/internal/idl/erroridl"
	"strings"
)

type EvidenceSource int64

const (
	EvidenceSource_unspecified EvidenceSource = 0
	EvidenceSource_human       EvidenceSource = 1
	EvidenceSource_system      EvidenceSource = 2
	EvidenceSource_ai          EvidenceSource = 3
	EvidenceSource_file        EvidenceSource = 4
	EvidenceSource_url         EvidenceSource = 5
)

func (p EvidenceSource) String() string {
	switch p {
	case EvidenceSource_unspecified:
		return "unspecified"
	case EvidenceSource_human:
		return "human"
	case EvidenceSource_system:
		return "system"
	case EvidenceSource_ai:
		return "ai"
	case EvidenceSource_file:
		return "file"
	case EvidenceSource_url:
		return "url"
	}
	return "<UNSET>"
}

func EvidenceSourceFromString(s string) (EvidenceSource, error) {
	switch s {
	case "unspecified":
		return EvidenceSource_unspecified, nil
	case "human":
		return EvidenceSource_human, nil
	case "system":
		return EvidenceSource_system, nil
	case "ai":
		return EvidenceSource_ai, nil
	case "file":
		return EvidenceSource_file, nil
	case "url":
		return EvidenceSource_url, nil
	}
	return EvidenceSource(0), fmt.Errorf("not a valid EvidenceSource string")
}

func EvidenceSourcePtr(v EvidenceSource) *EvidenceSource { return &v }

func (p EvidenceSource) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *EvidenceSource) UnmarshalText(text []byte) error {
	q, err := EvidenceSourceFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *EvidenceSource) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = EvidenceSource(result.Int64)
	return
}

func (p *EvidenceSource) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type WorkflowStatus int64

const (
	WorkflowStatus_unspecified WorkflowStatus = 0
	WorkflowStatus_running     WorkflowStatus = 1
	WorkflowStatus_completed   WorkflowStatus = 2
)

func (p WorkflowStatus) String() string {
	switch p {
	case WorkflowStatus_unspecified:
		return "unspecified"
	case WorkflowStatus_running:
		return "running"
	case WorkflowStatus_completed:
		return "completed"
	}
	return "<UNSET>"
}

func WorkflowStatusFromString(s string) (WorkflowStatus, error) {
	switch s {
	case "unspecified":
		return WorkflowStatus_unspecified, nil
	case "running":
		return WorkflowStatus_running, nil
	case "completed":
		return WorkflowStatus_completed, nil
	}
	return WorkflowStatus(0), fmt.Errorf("not a valid WorkflowStatus string")
}

func WorkflowStatusPtr(v WorkflowStatus) *WorkflowStatus { return &v }

func (p WorkflowStatus) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *WorkflowStatus) UnmarshalText(text []byte) error {
	q, err := WorkflowStatusFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *WorkflowStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = WorkflowStatus(result.Int64)
	return
}

func (p *WorkflowStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type StepStatus int64

const (
	StepStatus_unspecified StepStatus = 0
	StepStatus_ready       StepStatus = 1
	StepStatus_in_progress StepStatus = 2
	StepStatus_fixing      StepStatus = 3
	StepStatus_blocked     StepStatus = 4
)

func (p StepStatus) String() string {
	switch p {
	case StepStatus_unspecified:
		return "unspecified"
	case StepStatus_ready:
		return "ready"
	case StepStatus_in_progress:
		return "in_progress"
	case StepStatus_fixing:
		return "fixing"
	case StepStatus_blocked:
		return "blocked"
	}
	return "<UNSET>"
}

func StepStatusFromString(s string) (StepStatus, error) {
	switch s {
	case "unspecified":
		return StepStatus_unspecified, nil
	case "ready":
		return StepStatus_ready, nil
	case "in_progress":
		return StepStatus_in_progress, nil
	case "fixing":
		return StepStatus_fixing, nil
	case "blocked":
		return StepStatus_blocked, nil
	}
	return StepStatus(0), fmt.Errorf("not a valid StepStatus string")
}

func StepStatusPtr(v StepStatus) *StepStatus { return &v }

func (p StepStatus) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *StepStatus) UnmarshalText(text []byte) error {
	q, err := StepStatusFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *StepStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = StepStatus(result.Int64)
	return
}

func (p *StepStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Executor int64

const (
	Executor_unspecified Executor = 0
	Executor_agent       Executor = 1
	Executor_human       Executor = 2
)

func (p Executor) String() string {
	switch p {
	case Executor_unspecified:
		return "unspecified"
	case Executor_agent:
		return "agent"
	case Executor_human:
		return "human"
	}
	return "<UNSET>"
}

func ExecutorFromString(s string) (Executor, error) {
	switch s {
	case "unspecified":
		return Executor_unspecified, nil
	case "agent":
		return Executor_agent, nil
	case "human":
		return Executor_human, nil
	}
	return Executor(0), fmt.Errorf("not a valid Executor string")
}

func ExecutorPtr(v Executor) *Executor { return &v }

func (p Executor) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *Executor) UnmarshalText(text []byte) error {
	q, err := ExecutorFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *Executor) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Executor(result.Int64)
	return
}

func (p *Executor) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ProgressStatus int64

const (
	ProgressStatus_unspecified ProgressStatus = 0
	ProgressStatus_in_progress ProgressStatus = 1
	ProgressStatus_fixing      ProgressStatus = 2
	ProgressStatus_blocked     ProgressStatus = 3
)

func (p ProgressStatus) String() string {
	switch p {
	case ProgressStatus_unspecified:
		return "unspecified"
	case ProgressStatus_in_progress:
		return "in_progress"
	case ProgressStatus_fixing:
		return "fixing"
	case ProgressStatus_blocked:
		return "blocked"
	}
	return "<UNSET>"
}

func ProgressStatusFromString(s string) (ProgressStatus, error) {
	switch s {
	case "unspecified":
		return ProgressStatus_unspecified, nil
	case "in_progress":
		return ProgressStatus_in_progress, nil
	case "fixing":
		return ProgressStatus_fixing, nil
	case "blocked":
		return ProgressStatus_blocked, nil
	}
	return ProgressStatus(0), fmt.Errorf("not a valid ProgressStatus string")
}

func ProgressStatusPtr(v ProgressStatus) *ProgressStatus { return &v }

func (p ProgressStatus) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *ProgressStatus) UnmarshalText(text []byte) error {
	q, err := ProgressStatusFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *ProgressStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ProgressStatus(result.Int64)
	return
}

func (p *ProgressStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OutputType int64

const (
	OutputType_unspecified OutputType = 0
	OutputType_string      OutputType = 1
	OutputType_boolean     OutputType = 2
	OutputType_integer     OutputType = 3
	OutputType_path        OutputType = 4
	OutputType_url         OutputType = 5
	OutputType_url_list    OutputType = 6
	OutputType_enum_value  OutputType = 7
	OutputType_object      OutputType = 8
)

func (p OutputType) String() string {
	switch p {
	case OutputType_unspecified:
		return "unspecified"
	case OutputType_string:
		return "string"
	case OutputType_boolean:
		return "boolean"
	case OutputType_integer:
		return "integer"
	case OutputType_path:
		return "path"
	case OutputType_url:
		return "url"
	case OutputType_url_list:
		return "url_list"
	case OutputType_enum_value:
		return "enum_value"
	case OutputType_object:
		return "object"
	}
	return "<UNSET>"
}

func OutputTypeFromString(s string) (OutputType, error) {
	switch s {
	case "unspecified":
		return OutputType_unspecified, nil
	case "string":
		return OutputType_string, nil
	case "boolean":
		return OutputType_boolean, nil
	case "integer":
		return OutputType_integer, nil
	case "path":
		return OutputType_path, nil
	case "url":
		return OutputType_url, nil
	case "url_list":
		return OutputType_url_list, nil
	case "enum_value":
		return OutputType_enum_value, nil
	case "object":
		return OutputType_object, nil
	}
	return OutputType(0), fmt.Errorf("not a valid OutputType string")
}

func OutputTypePtr(v OutputType) *OutputType { return &v }

func (p OutputType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *OutputType) UnmarshalText(text []byte) error {
	q, err := OutputTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *OutputType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OutputType(result.Int64)
	return
}

func (p *OutputType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type RouteDirection int64

const (
	RouteDirection_unspecified RouteDirection = 0
	RouteDirection_flow        RouteDirection = 1
	RouteDirection_loop        RouteDirection = 2
)

func (p RouteDirection) String() string {
	switch p {
	case RouteDirection_unspecified:
		return "unspecified"
	case RouteDirection_flow:
		return "flow"
	case RouteDirection_loop:
		return "loop"
	}
	return "<UNSET>"
}

func RouteDirectionFromString(s string) (RouteDirection, error) {
	switch s {
	case "unspecified":
		return RouteDirection_unspecified, nil
	case "flow":
		return RouteDirection_flow, nil
	case "loop":
		return RouteDirection_loop, nil
	}
	return RouteDirection(0), fmt.Errorf("not a valid RouteDirection string")
}

func RouteDirectionPtr(v RouteDirection) *RouteDirection { return &v }

func (p RouteDirection) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *RouteDirection) UnmarshalText(text []byte) error {
	q, err := RouteDirectionFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *RouteDirection) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = RouteDirection(result.Int64)
	return
}

func (p *RouteDirection) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type InitEffect int64

const (
	InitEffect_unspecified InitEffect = 0
	InitEffect_initialized InitEffect = 1
)

func (p InitEffect) String() string {
	switch p {
	case InitEffect_unspecified:
		return "unspecified"
	case InitEffect_initialized:
		return "initialized"
	}
	return "<UNSET>"
}

func InitEffectFromString(s string) (InitEffect, error) {
	switch s {
	case "unspecified":
		return InitEffect_unspecified, nil
	case "initialized":
		return InitEffect_initialized, nil
	}
	return InitEffect(0), fmt.Errorf("not a valid InitEffect string")
}

func InitEffectPtr(v InitEffect) *InitEffect { return &v }

func (p InitEffect) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *InitEffect) UnmarshalText(text []byte) error {
	q, err := InitEffectFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *InitEffect) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = InitEffect(result.Int64)
	return
}

func (p *InitEffect) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ProgressEffect int64

const (
	ProgressEffect_unspecified    ProgressEffect = 0
	ProgressEffect_status_updated ProgressEffect = 1
)

func (p ProgressEffect) String() string {
	switch p {
	case ProgressEffect_unspecified:
		return "unspecified"
	case ProgressEffect_status_updated:
		return "status_updated"
	}
	return "<UNSET>"
}

func ProgressEffectFromString(s string) (ProgressEffect, error) {
	switch s {
	case "unspecified":
		return ProgressEffect_unspecified, nil
	case "status_updated":
		return ProgressEffect_status_updated, nil
	}
	return ProgressEffect(0), fmt.Errorf("not a valid ProgressEffect string")
}

func ProgressEffectPtr(v ProgressEffect) *ProgressEffect { return &v }

func (p ProgressEffect) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *ProgressEffect) UnmarshalText(text []byte) error {
	q, err := ProgressEffectFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *ProgressEffect) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ProgressEffect(result.Int64)
	return
}

func (p *ProgressEffect) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ResultEffect int64

const (
	ResultEffect_unspecified ResultEffect = 0
	ResultEffect_advanced    ResultEffect = 1
	ResultEffect_looped      ResultEffect = 2
	ResultEffect_completed   ResultEffect = 3
)

func (p ResultEffect) String() string {
	switch p {
	case ResultEffect_unspecified:
		return "unspecified"
	case ResultEffect_advanced:
		return "advanced"
	case ResultEffect_looped:
		return "looped"
	case ResultEffect_completed:
		return "completed"
	}
	return "<UNSET>"
}

func ResultEffectFromString(s string) (ResultEffect, error) {
	switch s {
	case "unspecified":
		return ResultEffect_unspecified, nil
	case "advanced":
		return ResultEffect_advanced, nil
	case "looped":
		return ResultEffect_looped, nil
	case "completed":
		return ResultEffect_completed, nil
	}
	return ResultEffect(0), fmt.Errorf("not a valid ResultEffect string")
}

func ResultEffectPtr(v ResultEffect) *ResultEffect { return &v }

func (p ResultEffect) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *ResultEffect) UnmarshalText(text []byte) error {
	q, err := ResultEffectFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *ResultEffect) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ResultEffect(result.Int64)
	return
}

func (p *ResultEffect) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TransitionDirection int64

const (
	TransitionDirection_unspecified TransitionDirection = 0
	TransitionDirection_flow        TransitionDirection = 1
	TransitionDirection_loop        TransitionDirection = 2
)

func (p TransitionDirection) String() string {
	switch p {
	case TransitionDirection_unspecified:
		return "unspecified"
	case TransitionDirection_flow:
		return "flow"
	case TransitionDirection_loop:
		return "loop"
	}
	return "<UNSET>"
}

func TransitionDirectionFromString(s string) (TransitionDirection, error) {
	switch s {
	case "unspecified":
		return TransitionDirection_unspecified, nil
	case "flow":
		return TransitionDirection_flow, nil
	case "loop":
		return TransitionDirection_loop, nil
	}
	return TransitionDirection(0), fmt.Errorf("not a valid TransitionDirection string")
}

func TransitionDirectionPtr(v TransitionDirection) *TransitionDirection { return &v }

func (p TransitionDirection) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TransitionDirection) UnmarshalText(text []byte) error {
	q, err := TransitionDirectionFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TransitionDirection) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TransitionDirection(result.Int64)
	return
}

func (p *TransitionDirection) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Flow public command contract.
//
// Responsibility boundary:
//   - This Thrift file owns command methods, request/response types, enums,
//     dynamic Output values, and public errors.
//   - Workflow YAML owns Stage/Job/Step, Prompt, Condition, Flow, and Loop.
//   - Generated Go files are read-only and must not be edited by hand.
type Requirement struct {
	Title     string  `thrift:"title,1,required" json:"title"`
	SourceUrl *string `thrift:"source_url,2,optional" json:"source_url,omitempty"`
}

func NewRequirement() *Requirement {
	return &Requirement{}
}

func (p *Requirement) InitDefault() {
}

func (p *Requirement) GetTitle() (v string) {
	return p.Title
}

var Requirement_SourceUrl_DEFAULT string

func (p *Requirement) GetSourceUrl() (v string) {
	if !p.IsSetSourceUrl() {
		return Requirement_SourceUrl_DEFAULT
	}
	return *p.SourceUrl
}

func (p *Requirement) IsSetSourceUrl() bool {
	return p.SourceUrl != nil
}

func (p *Requirement) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Requirement(%+v)", *p)
}

func (p *Requirement) DeepEqual(ano *Requirement) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Title) {
		return false
	}
	if !p.Field2DeepEqual(ano.SourceUrl) {
		return false
	}
	return true
}

func (p *Requirement) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Title, src) != 0 {
		return false
	}
	return true
}
func (p *Requirement) Field2DeepEqual(src *string) bool {

	if p.SourceUrl == src {
		return true
	} else if p.SourceUrl == nil || src == nil {
		return false
	}
	if strings.Compare(*p.SourceUrl, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_Requirement = map[int16]string{
	1: "title",
	2: "source_url",
}

// Evidence is audited but never participates in Route matching.
type Evidence struct {
	Source  EvidenceSource `thrift:"source,1,required,EvidenceSource" json:"source"`
	Content string         `thrift:"content,2,required" json:"content"`
	Ref     *string        `thrift:"ref,3,optional" json:"ref,omitempty"`
}

func NewEvidence() *Evidence {
	return &Evidence{}
}

func (p *Evidence) InitDefault() {
}

func (p *Evidence) GetSource() (v EvidenceSource) {
	return p.Source
}

func (p *Evidence) GetContent() (v string) {
	return p.Content
}

var Evidence_Ref_DEFAULT string

func (p *Evidence) GetRef() (v string) {
	if !p.IsSetRef() {
		return Evidence_Ref_DEFAULT
	}
	return *p.Ref
}

func (p *Evidence) IsSetRef() bool {
	return p.Ref != nil
}

func (p *Evidence) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Evidence(%+v)", *p)
}

func (p *Evidence) DeepEqual(ano *Evidence) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Source) {
		return false
	}
	if !p.Field2DeepEqual(ano.Content) {
		return false
	}
	if !p.Field3DeepEqual(ano.Ref) {
		return false
	}
	return true
}

func (p *Evidence) Field1DeepEqual(src EvidenceSource) bool {

	if p.Source != src {
		return false
	}
	return true
}
func (p *Evidence) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Content, src) != 0 {
		return false
	}
	return true
}
func (p *Evidence) Field3DeepEqual(src *string) bool {

	if p.Ref == src {
		return true
	} else if p.Ref == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Ref, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_Evidence = map[int16]string{
	1: "source",
	2: "content",
	3: "ref",
}

// Agent-submitted value. The Condition definition owns the key.
type OutputValue struct {
	Type  OutputType           `thrift:"type,1,required,OutputType" json:"type"`
	Value *commonidl.JsonValue `thrift:"value,2,required" json:"value"`
}

func NewOutputValue() *OutputValue {
	return &OutputValue{}
}

func (p *OutputValue) InitDefault() {
}

func (p *OutputValue) GetType() (v OutputType) {
	return p.Type
}

var OutputValue_Value_DEFAULT *commonidl.JsonValue

func (p *OutputValue) GetValue() (v *commonidl.JsonValue) {
	if !p.IsSetValue() {
		return OutputValue_Value_DEFAULT
	}
	return p.Value
}

func (p *OutputValue) IsSetValue() bool {
	return p.Value != nil
}

func (p *OutputValue) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OutputValue(%+v)", *p)
}

func (p *OutputValue) DeepEqual(ano *OutputValue) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Type) {
		return false
	}
	if !p.Field2DeepEqual(ano.Value) {
		return false
	}
	return true
}

func (p *OutputValue) Field1DeepEqual(src OutputType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *OutputValue) Field2DeepEqual(src *commonidl.JsonValue) bool {

	if !p.Value.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_OutputValue = map[int16]string{
	1: "type",
	2: "value",
}

type OutputSpec struct {
	Key         string     `thrift:"key,1,required" json:"key"`
	Type        OutputType `thrift:"type,2,required,OutputType" json:"type"`
	Description *string    `thrift:"description,3,optional" json:"description,omitempty"`
	Values      []string   `thrift:"values,4,optional,list<string>" json:"values,omitempty"`
	Minimum     *int64     `thrift:"minimum,5,optional" json:"minimum,omitempty"`
	Maximum     *int64     `thrift:"maximum,6,optional" json:"maximum,omitempty"`
	MinItems    *int32     `thrift:"min_items,7,optional" json:"min_items,omitempty"`
	MaxItems    *int32     `thrift:"max_items,8,optional" json:"max_items,omitempty"`
	Source      *string    `thrift:"source,9,optional" json:"source,omitempty"`
}

func NewOutputSpec() *OutputSpec {
	return &OutputSpec{}
}

func (p *OutputSpec) InitDefault() {
}

func (p *OutputSpec) GetKey() (v string) {
	return p.Key
}

func (p *OutputSpec) GetType() (v OutputType) {
	return p.Type
}

var OutputSpec_Description_DEFAULT string

func (p *OutputSpec) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return OutputSpec_Description_DEFAULT
	}
	return *p.Description
}

var OutputSpec_Values_DEFAULT []string

func (p *OutputSpec) GetValues() (v []string) {
	if !p.IsSetValues() {
		return OutputSpec_Values_DEFAULT
	}
	return p.Values
}

var OutputSpec_Minimum_DEFAULT int64

func (p *OutputSpec) GetMinimum() (v int64) {
	if !p.IsSetMinimum() {
		return OutputSpec_Minimum_DEFAULT
	}
	return *p.Minimum
}

var OutputSpec_Maximum_DEFAULT int64

func (p *OutputSpec) GetMaximum() (v int64) {
	if !p.IsSetMaximum() {
		return OutputSpec_Maximum_DEFAULT
	}
	return *p.Maximum
}

var OutputSpec_MinItems_DEFAULT int32

func (p *OutputSpec) GetMinItems() (v int32) {
	if !p.IsSetMinItems() {
		return OutputSpec_MinItems_DEFAULT
	}
	return *p.MinItems
}

var OutputSpec_MaxItems_DEFAULT int32

func (p *OutputSpec) GetMaxItems() (v int32) {
	if !p.IsSetMaxItems() {
		return OutputSpec_MaxItems_DEFAULT
	}
	return *p.MaxItems
}

var OutputSpec_Source_DEFAULT string

func (p *OutputSpec) GetSource() (v string) {
	if !p.IsSetSource() {
		return OutputSpec_Source_DEFAULT
	}
	return *p.Source
}

func (p *OutputSpec) IsSetDescription() bool {
	return p.Description != nil
}

func (p *OutputSpec) IsSetValues() bool {
	return p.Values != nil
}

func (p *OutputSpec) IsSetMinimum() bool {
	return p.Minimum != nil
}

func (p *OutputSpec) IsSetMaximum() bool {
	return p.Maximum != nil
}

func (p *OutputSpec) IsSetMinItems() bool {
	return p.MinItems != nil
}

func (p *OutputSpec) IsSetMaxItems() bool {
	return p.MaxItems != nil
}

func (p *OutputSpec) IsSetSource() bool {
	return p.Source != nil
}

func (p *OutputSpec) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OutputSpec(%+v)", *p)
}

func (p *OutputSpec) DeepEqual(ano *OutputSpec) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Key) {
		return false
	}
	if !p.Field2DeepEqual(ano.Type) {
		return false
	}
	if !p.Field3DeepEqual(ano.Description) {
		return false
	}
	if !p.Field4DeepEqual(ano.Values) {
		return false
	}
	if !p.Field5DeepEqual(ano.Minimum) {
		return false
	}
	if !p.Field6DeepEqual(ano.Maximum) {
		return false
	}
	if !p.Field7DeepEqual(ano.MinItems) {
		return false
	}
	if !p.Field8DeepEqual(ano.MaxItems) {
		return false
	}
	if !p.Field9DeepEqual(ano.Source) {
		return false
	}
	return true
}

func (p *OutputSpec) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Key, src) != 0 {
		return false
	}
	return true
}
func (p *OutputSpec) Field2DeepEqual(src OutputType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *OutputSpec) Field3DeepEqual(src *string) bool {

	if p.Description == src {
		return true
	} else if p.Description == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Description, *src) != 0 {
		return false
	}
	return true
}
func (p *OutputSpec) Field4DeepEqual(src []string) bool {

	if len(p.Values) != len(src) {
		return false
	}
	for i, v := range p.Values {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}
func (p *OutputSpec) Field5DeepEqual(src *int64) bool {

	if p.Minimum == src {
		return true
	} else if p.Minimum == nil || src == nil {
		return false
	}
	if *p.Minimum != *src {
		return false
	}
	return true
}
func (p *OutputSpec) Field6DeepEqual(src *int64) bool {

	if p.Maximum == src {
		return true
	} else if p.Maximum == nil || src == nil {
		return false
	}
	if *p.Maximum != *src {
		return false
	}
	return true
}
func (p *OutputSpec) Field7DeepEqual(src *int32) bool {

	if p.MinItems == src {
		return true
	} else if p.MinItems == nil || src == nil {
		return false
	}
	if *p.MinItems != *src {
		return false
	}
	return true
}
func (p *OutputSpec) Field8DeepEqual(src *int32) bool {

	if p.MaxItems == src {
		return true
	} else if p.MaxItems == nil || src == nil {
		return false
	}
	if *p.MaxItems != *src {
		return false
	}
	return true
}
func (p *OutputSpec) Field9DeepEqual(src *string) bool {

	if p.Source == src {
		return true
	} else if p.Source == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Source, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_OutputSpec = map[int16]string{
	1: "key",
	2: "type",
	3: "description",
	4: "values",
	5: "minimum",
	6: "maximum",
	7: "min_items",
	8: "max_items",
	9: "source",
}

type RegisteredOutput struct {
	Type           OutputType           `thrift:"type,1,required,OutputType" json:"type"`
	Value          *commonidl.JsonValue `thrift:"value,2,required" json:"value"`
	ProducerStepId string               `thrift:"producer_step_id,3,required" json:"producer_step_id"`
}

func NewRegisteredOutput() *RegisteredOutput {
	return &RegisteredOutput{}
}

func (p *RegisteredOutput) InitDefault() {
}

func (p *RegisteredOutput) GetType() (v OutputType) {
	return p.Type
}

var RegisteredOutput_Value_DEFAULT *commonidl.JsonValue

func (p *RegisteredOutput) GetValue() (v *commonidl.JsonValue) {
	if !p.IsSetValue() {
		return RegisteredOutput_Value_DEFAULT
	}
	return p.Value
}

func (p *RegisteredOutput) GetProducerStepId() (v string) {
	return p.ProducerStepId
}

func (p *RegisteredOutput) IsSetValue() bool {
	return p.Value != nil
}

func (p *RegisteredOutput) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisteredOutput(%+v)", *p)
}

func (p *RegisteredOutput) DeepEqual(ano *RegisteredOutput) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Type) {
		return false
	}
	if !p.Field2DeepEqual(ano.Value) {
		return false
	}
	if !p.Field3DeepEqual(ano.ProducerStepId) {
		return false
	}
	return true
}

func (p *RegisteredOutput) Field1DeepEqual(src OutputType) bool {

	if p.Type != src {
		return false
	}
	return true
}
func (p *RegisteredOutput) Field2DeepEqual(src *commonidl.JsonValue) bool {

	if !p.Value.DeepEqual(src) {
		return false
	}
	return true
}
func (p *RegisteredOutput) Field3DeepEqual(src string) bool {

	if strings.Compare(p.ProducerStepId, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_RegisteredOutput = map[int16]string{
	1: "type",
	2: "value",
	3: "producer_step_id",
}

type CurrentContext struct {
	// Fields 1-3 are retired and must not be reused.
	StageId   string   `thrift:"stage_id,4,required" json:"stage_id"`
	StageName string   `thrift:"stage_name,5,required" json:"stage_name"`
	JobId     string   `thrift:"job_id,6,required" json:"job_id"`
	JobName   string   `thrift:"job_name,7,required" json:"job_name"`
	StepId    string   `thrift:"step_id,8,required" json:"step_id"`
	StepName  string   `thrift:"step_name,9,required" json:"step_name"`
	Executor  Executor `thrift:"executor,10,required,Executor" json:"executor"`
}

func NewCurrentContext() *CurrentContext {
	return &CurrentContext{}
}

func (p *CurrentContext) InitDefault() {
}

func (p *CurrentContext) GetStageId() (v string) {
	return p.StageId
}

func (p *CurrentContext) GetStageName() (v string) {
	return p.StageName
}

func (p *CurrentContext) GetJobId() (v string) {
	return p.JobId
}

func (p *CurrentContext) GetJobName() (v string) {
	return p.JobName
}

func (p *CurrentContext) GetStepId() (v string) {
	return p.StepId
}

func (p *CurrentContext) GetStepName() (v string) {
	return p.StepName
}

func (p *CurrentContext) GetExecutor() (v Executor) {
	return p.Executor
}

func (p *CurrentContext) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CurrentContext(%+v)", *p)
}

func (p *CurrentContext) DeepEqual(ano *CurrentContext) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field4DeepEqual(ano.StageId) {
		return false
	}
	if !p.Field5DeepEqual(ano.StageName) {
		return false
	}
	if !p.Field6DeepEqual(ano.JobId) {
		return false
	}
	if !p.Field7DeepEqual(ano.JobName) {
		return false
	}
	if !p.Field8DeepEqual(ano.StepId) {
		return false
	}
	if !p.Field9DeepEqual(ano.StepName) {
		return false
	}
	if !p.Field10DeepEqual(ano.Executor) {
		return false
	}
	return true
}

func (p *CurrentContext) Field4DeepEqual(src string) bool {

	if strings.Compare(p.StageId, src) != 0 {
		return false
	}
	return true
}
func (p *CurrentContext) Field5DeepEqual(src string) bool {

	if strings.Compare(p.StageName, src) != 0 {
		return false
	}
	return true
}
func (p *CurrentContext) Field6DeepEqual(src string) bool {

	if strings.Compare(p.JobId, src) != 0 {
		return false
	}
	return true
}
func (p *CurrentContext) Field7DeepEqual(src string) bool {

	if strings.Compare(p.JobName, src) != 0 {
		return false
	}
	return true
}
func (p *CurrentContext) Field8DeepEqual(src string) bool {

	if strings.Compare(p.StepId, src) != 0 {
		return false
	}
	return true
}
func (p *CurrentContext) Field9DeepEqual(src string) bool {

	if strings.Compare(p.StepName, src) != 0 {
		return false
	}
	return true
}
func (p *CurrentContext) Field10DeepEqual(src Executor) bool {

	if p.Executor != src {
		return false
	}
	return true
}

var fieldIDToName_CurrentContext = map[int16]string{
	4:  "stage_id",
	5:  "stage_name",
	6:  "job_id",
	7:  "job_name",
	8:  "step_id",
	9:  "step_name",
	10: "executor",
}

type Execution struct {
	Status   StepStatus  `thrift:"status,1,required,StepStatus" json:"status"`
	Summary  *string     `thrift:"summary,2,optional" json:"summary,omitempty"`
	Evidence []*Evidence `thrift:"evidence,3,required,list<Evidence>" json:"evidence"`
}

func NewExecution() *Execution {
	return &Execution{}
}

func (p *Execution) InitDefault() {
}

func (p *Execution) GetStatus() (v StepStatus) {
	return p.Status
}

var Execution_Summary_DEFAULT string

func (p *Execution) GetSummary() (v string) {
	if !p.IsSetSummary() {
		return Execution_Summary_DEFAULT
	}
	return *p.Summary
}

func (p *Execution) GetEvidence() (v []*Evidence) {
	return p.Evidence
}

func (p *Execution) IsSetSummary() bool {
	return p.Summary != nil
}

func (p *Execution) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Execution(%+v)", *p)
}

func (p *Execution) DeepEqual(ano *Execution) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Status) {
		return false
	}
	if !p.Field2DeepEqual(ano.Summary) {
		return false
	}
	if !p.Field3DeepEqual(ano.Evidence) {
		return false
	}
	return true
}

func (p *Execution) Field1DeepEqual(src StepStatus) bool {

	if p.Status != src {
		return false
	}
	return true
}
func (p *Execution) Field2DeepEqual(src *string) bool {

	if p.Summary == src {
		return true
	} else if p.Summary == nil || src == nil {
		return false
	}
	if strings.Compare(*p.Summary, *src) != 0 {
		return false
	}
	return true
}
func (p *Execution) Field3DeepEqual(src []*Evidence) bool {

	if len(p.Evidence) != len(src) {
		return false
	}
	for i, v := range p.Evidence {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_Execution = map[int16]string{
	1: "status",
	2: "summary",
	3: "evidence",
}

type Skill struct {
	Id       string `thrift:"id,1,required" json:"id"`
	Prompt   string `thrift:"prompt,2,required" json:"prompt"`
	Optional bool   `thrift:"optional,3,required" json:"optional"`
	Path     string `thrift:"path,4,required" json:"path"`
}

func NewSkill() *Skill {
	return &Skill{}
}

func (p *Skill) InitDefault() {
}

func (p *Skill) GetId() (v string) {
	return p.Id
}

func (p *Skill) GetPrompt() (v string) {
	return p.Prompt
}

func (p *Skill) GetOptional() (v bool) {
	return p.Optional
}

func (p *Skill) GetPath() (v string) {
	return p.Path
}

func (p *Skill) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Skill(%+v)", *p)
}

func (p *Skill) DeepEqual(ano *Skill) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.Prompt) {
		return false
	}
	if !p.Field3DeepEqual(ano.Optional) {
		return false
	}
	if !p.Field4DeepEqual(ano.Path) {
		return false
	}
	return true
}

func (p *Skill) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *Skill) Field2DeepEqual(src string) bool {

	if strings.Compare(p.Prompt, src) != 0 {
		return false
	}
	return true
}
func (p *Skill) Field3DeepEqual(src bool) bool {

	if p.Optional != src {
		return false
	}
	return true
}
func (p *Skill) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Path, src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_Skill = map[int16]string{
	1: "id",
	2: "prompt",
	3: "optional",
	4: "path",
}

type Prompt struct {
	Content string   `thrift:"content,1,required" json:"content"`
	Skills  []*Skill `thrift:"skills,2,required,list<Skill>" json:"skills"`
}

func NewPrompt() *Prompt {
	return &Prompt{}
}

func (p *Prompt) InitDefault() {
}

func (p *Prompt) GetContent() (v string) {
	return p.Content
}

func (p *Prompt) GetSkills() (v []*Skill) {
	return p.Skills
}

func (p *Prompt) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Prompt(%+v)", *p)
}

func (p *Prompt) DeepEqual(ano *Prompt) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Content) {
		return false
	}
	if !p.Field2DeepEqual(ano.Skills) {
		return false
	}
	return true
}

func (p *Prompt) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Content, src) != 0 {
		return false
	}
	return true
}
func (p *Prompt) Field2DeepEqual(src []*Skill) bool {

	if len(p.Skills) != len(src) {
		return false
	}
	for i, v := range p.Skills {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_Prompt = map[int16]string{
	1: "content",
	2: "skills",
}

type ConditionView struct {
	Id             string      `thrift:"id,1,required" json:"id"`
	Prompt         *Prompt     `thrift:"prompt,2,required" json:"prompt"`
	Output         *OutputSpec `thrift:"output,3,required" json:"output"`
	ExclusiveGroup *string     `thrift:"exclusive_group,4,optional" json:"exclusive_group,omitempty"`
}

func NewConditionView() *ConditionView {
	return &ConditionView{}
}

func (p *ConditionView) InitDefault() {
}

func (p *ConditionView) GetId() (v string) {
	return p.Id
}

var ConditionView_Prompt_DEFAULT *Prompt

func (p *ConditionView) GetPrompt() (v *Prompt) {
	if !p.IsSetPrompt() {
		return ConditionView_Prompt_DEFAULT
	}
	return p.Prompt
}

var ConditionView_Output_DEFAULT *OutputSpec

func (p *ConditionView) GetOutput() (v *OutputSpec) {
	if !p.IsSetOutput() {
		return ConditionView_Output_DEFAULT
	}
	return p.Output
}

var ConditionView_ExclusiveGroup_DEFAULT string

func (p *ConditionView) GetExclusiveGroup() (v string) {
	if !p.IsSetExclusiveGroup() {
		return ConditionView_ExclusiveGroup_DEFAULT
	}
	return *p.ExclusiveGroup
}

func (p *ConditionView) IsSetPrompt() bool {
	return p.Prompt != nil
}

func (p *ConditionView) IsSetOutput() bool {
	return p.Output != nil
}

func (p *ConditionView) IsSetExclusiveGroup() bool {
	return p.ExclusiveGroup != nil
}

func (p *ConditionView) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConditionView(%+v)", *p)
}

func (p *ConditionView) DeepEqual(ano *ConditionView) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.Prompt) {
		return false
	}
	if !p.Field3DeepEqual(ano.Output) {
		return false
	}
	if !p.Field4DeepEqual(ano.ExclusiveGroup) {
		return false
	}
	return true
}

func (p *ConditionView) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *ConditionView) Field2DeepEqual(src *Prompt) bool {

	if !p.Prompt.DeepEqual(src) {
		return false
	}
	return true
}
func (p *ConditionView) Field3DeepEqual(src *OutputSpec) bool {

	if !p.Output.DeepEqual(src) {
		return false
	}
	return true
}
func (p *ConditionView) Field4DeepEqual(src *string) bool {

	if p.ExclusiveGroup == src {
		return true
	} else if p.ExclusiveGroup == nil || src == nil {
		return false
	}
	if strings.Compare(*p.ExclusiveGroup, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_ConditionView = map[int16]string{
	1: "id",
	2: "prompt",
	3: "output",
	4: "exclusive_group",
}

type RouteWhen struct {
	AnyOf [][]string `thrift:"any_of,1,required,list<list<string>>" json:"any_of"`
}

func NewRouteWhen() *RouteWhen {
	return &RouteWhen{}
}

func (p *RouteWhen) InitDefault() {
}

func (p *RouteWhen) GetAnyOf() (v [][]string) {
	return p.AnyOf
}

func (p *RouteWhen) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RouteWhen(%+v)", *p)
}

func (p *RouteWhen) DeepEqual(ano *RouteWhen) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.AnyOf) {
		return false
	}
	return true
}

func (p *RouteWhen) Field1DeepEqual(src [][]string) bool {

	if len(p.AnyOf) != len(src) {
		return false
	}
	for i, v := range p.AnyOf {
		_src := src[i]
		if len(v) != len(_src) {
			return false
		}
		for i, v := range v {
			_src1 := _src[i]
			if strings.Compare(v, _src1) != 0 {
				return false
			}
		}
	}
	return true
}

var fieldIDToName_RouteWhen = map[int16]string{
	1: "any_of",
}

type AvailableRoute struct {
	Direction RouteDirection  `thrift:"direction,1,required,RouteDirection" json:"direction"`
	When      *RouteWhen      `thrift:"when,2,required" json:"when"`
	Route     *RouteSelection `thrift:"route,3,required" json:"route"`
	Prompt    *Prompt         `thrift:"prompt,4,required" json:"prompt"`
}

func NewAvailableRoute() *AvailableRoute {
	return &AvailableRoute{}
}

func (p *AvailableRoute) InitDefault() {
}

func (p *AvailableRoute) GetDirection() (v RouteDirection) {
	return p.Direction
}

var AvailableRoute_When_DEFAULT *RouteWhen

func (p *AvailableRoute) GetWhen() (v *RouteWhen) {
	if !p.IsSetWhen() {
		return AvailableRoute_When_DEFAULT
	}
	return p.When
}

var AvailableRoute_Route_DEFAULT *RouteSelection

func (p *AvailableRoute) GetRoute() (v *RouteSelection) {
	if !p.IsSetRoute() {
		return AvailableRoute_Route_DEFAULT
	}
	return p.Route
}

var AvailableRoute_Prompt_DEFAULT *Prompt

func (p *AvailableRoute) GetPrompt() (v *Prompt) {
	if !p.IsSetPrompt() {
		return AvailableRoute_Prompt_DEFAULT
	}
	return p.Prompt
}

func (p *AvailableRoute) IsSetWhen() bool {
	return p.When != nil
}

func (p *AvailableRoute) IsSetRoute() bool {
	return p.Route != nil
}

func (p *AvailableRoute) IsSetPrompt() bool {
	return p.Prompt != nil
}

func (p *AvailableRoute) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AvailableRoute(%+v)", *p)
}

func (p *AvailableRoute) DeepEqual(ano *AvailableRoute) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Direction) {
		return false
	}
	if !p.Field2DeepEqual(ano.When) {
		return false
	}
	if !p.Field3DeepEqual(ano.Route) {
		return false
	}
	if !p.Field4DeepEqual(ano.Prompt) {
		return false
	}
	return true
}

func (p *AvailableRoute) Field1DeepEqual(src RouteDirection) bool {

	if p.Direction != src {
		return false
	}
	return true
}
func (p *AvailableRoute) Field2DeepEqual(src *RouteWhen) bool {

	if !p.When.DeepEqual(src) {
		return false
	}
	return true
}
func (p *AvailableRoute) Field3DeepEqual(src *RouteSelection) bool {

	if !p.Route.DeepEqual(src) {
		return false
	}
	return true
}
func (p *AvailableRoute) Field4DeepEqual(src *Prompt) bool {

	if !p.Prompt.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_AvailableRoute = map[int16]string{
	1: "direction",
	2: "when",
	3: "route",
	4: "prompt",
}

type CurrentTask struct {
	Context    *CurrentContext  `thrift:"context,1,required" json:"context"`
	Execution  *Execution       `thrift:"execution,2,required" json:"execution"`
	Prompt     *Prompt          `thrift:"prompt,3,required" json:"prompt"`
	Conditions []*ConditionView `thrift:"conditions,4,required,list<ConditionView>" json:"conditions"`
	// Fields 5-6 are retired and must not be reused.
	AvailableRoutes []*AvailableRoute `thrift:"available_routes,7,required,list<AvailableRoute>" json:"available_routes"`
}

func NewCurrentTask() *CurrentTask {
	return &CurrentTask{}
}

func (p *CurrentTask) InitDefault() {
}

var CurrentTask_Context_DEFAULT *CurrentContext

func (p *CurrentTask) GetContext() (v *CurrentContext) {
	if !p.IsSetContext() {
		return CurrentTask_Context_DEFAULT
	}
	return p.Context
}

var CurrentTask_Execution_DEFAULT *Execution

func (p *CurrentTask) GetExecution() (v *Execution) {
	if !p.IsSetExecution() {
		return CurrentTask_Execution_DEFAULT
	}
	return p.Execution
}

var CurrentTask_Prompt_DEFAULT *Prompt

func (p *CurrentTask) GetPrompt() (v *Prompt) {
	if !p.IsSetPrompt() {
		return CurrentTask_Prompt_DEFAULT
	}
	return p.Prompt
}

func (p *CurrentTask) GetConditions() (v []*ConditionView) {
	return p.Conditions
}

func (p *CurrentTask) GetAvailableRoutes() (v []*AvailableRoute) {
	return p.AvailableRoutes
}

func (p *CurrentTask) IsSetContext() bool {
	return p.Context != nil
}

func (p *CurrentTask) IsSetExecution() bool {
	return p.Execution != nil
}

func (p *CurrentTask) IsSetPrompt() bool {
	return p.Prompt != nil
}

func (p *CurrentTask) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CurrentTask(%+v)", *p)
}

func (p *CurrentTask) DeepEqual(ano *CurrentTask) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Context) {
		return false
	}
	if !p.Field2DeepEqual(ano.Execution) {
		return false
	}
	if !p.Field3DeepEqual(ano.Prompt) {
		return false
	}
	if !p.Field4DeepEqual(ano.Conditions) {
		return false
	}
	if !p.Field7DeepEqual(ano.AvailableRoutes) {
		return false
	}
	return true
}

func (p *CurrentTask) Field1DeepEqual(src *CurrentContext) bool {

	if !p.Context.DeepEqual(src) {
		return false
	}
	return true
}
func (p *CurrentTask) Field2DeepEqual(src *Execution) bool {

	if !p.Execution.DeepEqual(src) {
		return false
	}
	return true
}
func (p *CurrentTask) Field3DeepEqual(src *Prompt) bool {

	if !p.Prompt.DeepEqual(src) {
		return false
	}
	return true
}
func (p *CurrentTask) Field4DeepEqual(src []*ConditionView) bool {

	if len(p.Conditions) != len(src) {
		return false
	}
	for i, v := range p.Conditions {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *CurrentTask) Field7DeepEqual(src []*AvailableRoute) bool {

	if len(p.AvailableRoutes) != len(src) {
		return false
	}
	for i, v := range p.AvailableRoutes {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_CurrentTask = map[int16]string{
	1: "context",
	2: "execution",
	3: "prompt",
	4: "conditions",
	7: "available_routes",
}

type FlowState struct {
	Status  WorkflowStatus               `thrift:"status,1,required,WorkflowStatus" json:"status"`
	Current *CurrentTask                 `thrift:"current,2,optional" json:"current,omitempty"`
	Outputs map[string]*RegisteredOutput `thrift:"outputs,3,required" json:"outputs"`
}

func NewFlowState() *FlowState {
	return &FlowState{}
}

func (p *FlowState) InitDefault() {
}

func (p *FlowState) GetStatus() (v WorkflowStatus) {
	return p.Status
}

var FlowState_Current_DEFAULT *CurrentTask

func (p *FlowState) GetCurrent() (v *CurrentTask) {
	if !p.IsSetCurrent() {
		return FlowState_Current_DEFAULT
	}
	return p.Current
}

func (p *FlowState) GetOutputs() (v map[string]*RegisteredOutput) {
	return p.Outputs
}

func (p *FlowState) IsSetCurrent() bool {
	return p.Current != nil
}

func (p *FlowState) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowState(%+v)", *p)
}

func (p *FlowState) DeepEqual(ano *FlowState) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Status) {
		return false
	}
	if !p.Field2DeepEqual(ano.Current) {
		return false
	}
	if !p.Field3DeepEqual(ano.Outputs) {
		return false
	}
	return true
}

func (p *FlowState) Field1DeepEqual(src WorkflowStatus) bool {

	if p.Status != src {
		return false
	}
	return true
}
func (p *FlowState) Field2DeepEqual(src *CurrentTask) bool {

	if !p.Current.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowState) Field3DeepEqual(src map[string]*RegisteredOutput) bool {

	if len(p.Outputs) != len(src) {
		return false
	}
	for k, v := range p.Outputs {
		_src := src[k]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_FlowState = map[int16]string{
	1: "status",
	2: "current",
	3: "outputs",
}

type FlowInitRequest struct {
	Workflow    string       `thrift:"workflow,1,required" json:"workflow"`
	Requirement *Requirement `thrift:"requirement,2,required" json:"requirement"`
}

func NewFlowInitRequest() *FlowInitRequest {
	return &FlowInitRequest{}
}

func (p *FlowInitRequest) InitDefault() {
}

func (p *FlowInitRequest) GetWorkflow() (v string) {
	return p.Workflow
}

var FlowInitRequest_Requirement_DEFAULT *Requirement

func (p *FlowInitRequest) GetRequirement() (v *Requirement) {
	if !p.IsSetRequirement() {
		return FlowInitRequest_Requirement_DEFAULT
	}
	return p.Requirement
}

func (p *FlowInitRequest) IsSetRequirement() bool {
	return p.Requirement != nil
}

func (p *FlowInitRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowInitRequest(%+v)", *p)
}

func (p *FlowInitRequest) DeepEqual(ano *FlowInitRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Workflow) {
		return false
	}
	if !p.Field2DeepEqual(ano.Requirement) {
		return false
	}
	return true
}

func (p *FlowInitRequest) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Workflow, src) != 0 {
		return false
	}
	return true
}
func (p *FlowInitRequest) Field2DeepEqual(src *Requirement) bool {

	if !p.Requirement.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowInitRequest = map[int16]string{
	1: "workflow",
	2: "requirement",
}

type FlowInitResponse struct {
	Effect   InitEffect             `thrift:"effect,1,required,InitEffect" json:"effect"`
	Workflow *commonidl.WorkflowRef `thrift:"workflow,2,required" json:"workflow"`
	State    *FlowState             `thrift:"state,3,required" json:"state"`
}

func NewFlowInitResponse() *FlowInitResponse {
	return &FlowInitResponse{}
}

func (p *FlowInitResponse) InitDefault() {
}

func (p *FlowInitResponse) GetEffect() (v InitEffect) {
	return p.Effect
}

var FlowInitResponse_Workflow_DEFAULT *commonidl.WorkflowRef

func (p *FlowInitResponse) GetWorkflow() (v *commonidl.WorkflowRef) {
	if !p.IsSetWorkflow() {
		return FlowInitResponse_Workflow_DEFAULT
	}
	return p.Workflow
}

var FlowInitResponse_State_DEFAULT *FlowState

func (p *FlowInitResponse) GetState() (v *FlowState) {
	if !p.IsSetState() {
		return FlowInitResponse_State_DEFAULT
	}
	return p.State
}

func (p *FlowInitResponse) IsSetWorkflow() bool {
	return p.Workflow != nil
}

func (p *FlowInitResponse) IsSetState() bool {
	return p.State != nil
}

func (p *FlowInitResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowInitResponse(%+v)", *p)
}

func (p *FlowInitResponse) DeepEqual(ano *FlowInitResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Effect) {
		return false
	}
	if !p.Field2DeepEqual(ano.Workflow) {
		return false
	}
	if !p.Field3DeepEqual(ano.State) {
		return false
	}
	return true
}

func (p *FlowInitResponse) Field1DeepEqual(src InitEffect) bool {

	if p.Effect != src {
		return false
	}
	return true
}
func (p *FlowInitResponse) Field2DeepEqual(src *commonidl.WorkflowRef) bool {

	if !p.Workflow.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowInitResponse) Field3DeepEqual(src *FlowState) bool {

	if !p.State.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowInitResponse = map[int16]string{
	1: "effect",
	2: "workflow",
	3: "state",
}

type FlowStatusRequest struct {
}

func NewFlowStatusRequest() *FlowStatusRequest {
	return &FlowStatusRequest{}
}

func (p *FlowStatusRequest) InitDefault() {
}

func (p *FlowStatusRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowStatusRequest(%+v)", *p)
}

func (p *FlowStatusRequest) DeepEqual(ano *FlowStatusRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	return true
}

var fieldIDToName_FlowStatusRequest = map[int16]string{}

type FlowStatusResponse struct {
	Requirement *Requirement           `thrift:"requirement,1,required" json:"requirement"`
	Workflow    *commonidl.WorkflowRef `thrift:"workflow,2,required" json:"workflow"`
	State       *FlowState             `thrift:"state,3,required" json:"state"`
}

func NewFlowStatusResponse() *FlowStatusResponse {
	return &FlowStatusResponse{}
}

func (p *FlowStatusResponse) InitDefault() {
}

var FlowStatusResponse_Requirement_DEFAULT *Requirement

func (p *FlowStatusResponse) GetRequirement() (v *Requirement) {
	if !p.IsSetRequirement() {
		return FlowStatusResponse_Requirement_DEFAULT
	}
	return p.Requirement
}

var FlowStatusResponse_Workflow_DEFAULT *commonidl.WorkflowRef

func (p *FlowStatusResponse) GetWorkflow() (v *commonidl.WorkflowRef) {
	if !p.IsSetWorkflow() {
		return FlowStatusResponse_Workflow_DEFAULT
	}
	return p.Workflow
}

var FlowStatusResponse_State_DEFAULT *FlowState

func (p *FlowStatusResponse) GetState() (v *FlowState) {
	if !p.IsSetState() {
		return FlowStatusResponse_State_DEFAULT
	}
	return p.State
}

func (p *FlowStatusResponse) IsSetRequirement() bool {
	return p.Requirement != nil
}

func (p *FlowStatusResponse) IsSetWorkflow() bool {
	return p.Workflow != nil
}

func (p *FlowStatusResponse) IsSetState() bool {
	return p.State != nil
}

func (p *FlowStatusResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowStatusResponse(%+v)", *p)
}

func (p *FlowStatusResponse) DeepEqual(ano *FlowStatusResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Requirement) {
		return false
	}
	if !p.Field2DeepEqual(ano.Workflow) {
		return false
	}
	if !p.Field3DeepEqual(ano.State) {
		return false
	}
	return true
}

func (p *FlowStatusResponse) Field1DeepEqual(src *Requirement) bool {

	if !p.Requirement.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowStatusResponse) Field2DeepEqual(src *commonidl.WorkflowRef) bool {

	if !p.Workflow.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowStatusResponse) Field3DeepEqual(src *FlowState) bool {

	if !p.State.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowStatusResponse = map[int16]string{
	1: "requirement",
	2: "workflow",
	3: "state",
}

type FlowProgressRequest struct {
	StepId   string         `thrift:"step_id,1,required" json:"step_id"`
	Status   ProgressStatus `thrift:"status,2,required,ProgressStatus" json:"status"`
	Summary  string         `thrift:"summary,3,required" json:"summary"`
	Evidence []*Evidence    `thrift:"evidence,4,required,list<Evidence>" json:"evidence"`
}

func NewFlowProgressRequest() *FlowProgressRequest {
	return &FlowProgressRequest{}
}

func (p *FlowProgressRequest) InitDefault() {
}

func (p *FlowProgressRequest) GetStepId() (v string) {
	return p.StepId
}

func (p *FlowProgressRequest) GetStatus() (v ProgressStatus) {
	return p.Status
}

func (p *FlowProgressRequest) GetSummary() (v string) {
	return p.Summary
}

func (p *FlowProgressRequest) GetEvidence() (v []*Evidence) {
	return p.Evidence
}

func (p *FlowProgressRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowProgressRequest(%+v)", *p)
}

func (p *FlowProgressRequest) DeepEqual(ano *FlowProgressRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.StepId) {
		return false
	}
	if !p.Field2DeepEqual(ano.Status) {
		return false
	}
	if !p.Field3DeepEqual(ano.Summary) {
		return false
	}
	if !p.Field4DeepEqual(ano.Evidence) {
		return false
	}
	return true
}

func (p *FlowProgressRequest) Field1DeepEqual(src string) bool {

	if strings.Compare(p.StepId, src) != 0 {
		return false
	}
	return true
}
func (p *FlowProgressRequest) Field2DeepEqual(src ProgressStatus) bool {

	if p.Status != src {
		return false
	}
	return true
}
func (p *FlowProgressRequest) Field3DeepEqual(src string) bool {

	if strings.Compare(p.Summary, src) != 0 {
		return false
	}
	return true
}
func (p *FlowProgressRequest) Field4DeepEqual(src []*Evidence) bool {

	if len(p.Evidence) != len(src) {
		return false
	}
	for i, v := range p.Evidence {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}

var fieldIDToName_FlowProgressRequest = map[int16]string{
	1: "step_id",
	2: "status",
	3: "summary",
	4: "evidence",
}

type FlowProgressResponse struct {
	Effect ProgressEffect `thrift:"effect,1,required,ProgressEffect" json:"effect"`
	State  *FlowState     `thrift:"state,2,required" json:"state"`
}

func NewFlowProgressResponse() *FlowProgressResponse {
	return &FlowProgressResponse{}
}

func (p *FlowProgressResponse) InitDefault() {
}

func (p *FlowProgressResponse) GetEffect() (v ProgressEffect) {
	return p.Effect
}

var FlowProgressResponse_State_DEFAULT *FlowState

func (p *FlowProgressResponse) GetState() (v *FlowState) {
	if !p.IsSetState() {
		return FlowProgressResponse_State_DEFAULT
	}
	return p.State
}

func (p *FlowProgressResponse) IsSetState() bool {
	return p.State != nil
}

func (p *FlowProgressResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowProgressResponse(%+v)", *p)
}

func (p *FlowProgressResponse) DeepEqual(ano *FlowProgressResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Effect) {
		return false
	}
	if !p.Field2DeepEqual(ano.State) {
		return false
	}
	return true
}

func (p *FlowProgressResponse) Field1DeepEqual(src ProgressEffect) bool {

	if p.Effect != src {
		return false
	}
	return true
}
func (p *FlowProgressResponse) Field2DeepEqual(src *FlowState) bool {

	if !p.State.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowProgressResponse = map[int16]string{
	1: "effect",
	2: "state",
}

type ConditionResult struct {
	ConditionId string       `thrift:"condition_id,1,required" json:"condition_id"`
	Output      *OutputValue `thrift:"output,2,required" json:"output"`
}

func NewConditionResult() *ConditionResult {
	return &ConditionResult{}
}

func (p *ConditionResult) InitDefault() {
}

func (p *ConditionResult) GetConditionId() (v string) {
	return p.ConditionId
}

var ConditionResult_Output_DEFAULT *OutputValue

func (p *ConditionResult) GetOutput() (v *OutputValue) {
	if !p.IsSetOutput() {
		return ConditionResult_Output_DEFAULT
	}
	return p.Output
}

func (p *ConditionResult) IsSetOutput() bool {
	return p.Output != nil
}

func (p *ConditionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConditionResult(%+v)", *p)
}

func (p *ConditionResult) DeepEqual(ano *ConditionResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.ConditionId) {
		return false
	}
	if !p.Field2DeepEqual(ano.Output) {
		return false
	}
	return true
}

func (p *ConditionResult) Field1DeepEqual(src string) bool {

	if strings.Compare(p.ConditionId, src) != 0 {
		return false
	}
	return true
}
func (p *ConditionResult) Field2DeepEqual(src *OutputValue) bool {

	if !p.Output.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_ConditionResult = map[int16]string{
	1: "condition_id",
	2: "output",
}

type Transition struct {
	Direction  TransitionDirection `thrift:"direction,1,required,TransitionDirection" json:"direction"`
	FromStepId string              `thrift:"from_step_id,2,required" json:"from_step_id"`
	ToStepId   *string             `thrift:"to_step_id,3,optional" json:"to_step_id,omitempty"`
}

func NewTransition() *Transition {
	return &Transition{}
}

func (p *Transition) InitDefault() {
}

func (p *Transition) GetDirection() (v TransitionDirection) {
	return p.Direction
}

func (p *Transition) GetFromStepId() (v string) {
	return p.FromStepId
}

var Transition_ToStepId_DEFAULT string

func (p *Transition) GetToStepId() (v string) {
	if !p.IsSetToStepId() {
		return Transition_ToStepId_DEFAULT
	}
	return *p.ToStepId
}

func (p *Transition) IsSetToStepId() bool {
	return p.ToStepId != nil
}

func (p *Transition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Transition(%+v)", *p)
}

func (p *Transition) DeepEqual(ano *Transition) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Direction) {
		return false
	}
	if !p.Field2DeepEqual(ano.FromStepId) {
		return false
	}
	if !p.Field3DeepEqual(ano.ToStepId) {
		return false
	}
	return true
}

func (p *Transition) Field1DeepEqual(src TransitionDirection) bool {

	if p.Direction != src {
		return false
	}
	return true
}
func (p *Transition) Field2DeepEqual(src string) bool {

	if strings.Compare(p.FromStepId, src) != 0 {
		return false
	}
	return true
}
func (p *Transition) Field3DeepEqual(src *string) bool {

	if p.ToStepId == src {
		return true
	} else if p.ToStepId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.ToStepId, *src) != 0 {
		return false
	}
	return true
}

var fieldIDToName_Transition = map[int16]string{
	1: "direction",
	2: "from_step_id",
	3: "to_step_id",
}

type FlowResultRequest struct {
	StepId           string             `thrift:"step_id,1,required" json:"step_id"`
	ConditionResults []*ConditionResult `thrift:"condition_results,2,required,list<ConditionResult>" json:"condition_results"`
	Evidence         []*Evidence        `thrift:"evidence,3,required,list<Evidence>" json:"evidence"`
	Summary          string             `thrift:"summary,4,required" json:"summary"`
	// Field 5 is retired and must not be reused.
	Route *RouteSelection `thrift:"route,6,required" json:"route"`
}

func NewFlowResultRequest() *FlowResultRequest {
	return &FlowResultRequest{}
}

func (p *FlowResultRequest) InitDefault() {
}

func (p *FlowResultRequest) GetStepId() (v string) {
	return p.StepId
}

func (p *FlowResultRequest) GetConditionResults() (v []*ConditionResult) {
	return p.ConditionResults
}

func (p *FlowResultRequest) GetEvidence() (v []*Evidence) {
	return p.Evidence
}

func (p *FlowResultRequest) GetSummary() (v string) {
	return p.Summary
}

var FlowResultRequest_Route_DEFAULT *RouteSelection

func (p *FlowResultRequest) GetRoute() (v *RouteSelection) {
	if !p.IsSetRoute() {
		return FlowResultRequest_Route_DEFAULT
	}
	return p.Route
}

func (p *FlowResultRequest) IsSetRoute() bool {
	return p.Route != nil
}

func (p *FlowResultRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowResultRequest(%+v)", *p)
}

func (p *FlowResultRequest) DeepEqual(ano *FlowResultRequest) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.StepId) {
		return false
	}
	if !p.Field2DeepEqual(ano.ConditionResults) {
		return false
	}
	if !p.Field3DeepEqual(ano.Evidence) {
		return false
	}
	if !p.Field4DeepEqual(ano.Summary) {
		return false
	}
	if !p.Field6DeepEqual(ano.Route) {
		return false
	}
	return true
}

func (p *FlowResultRequest) Field1DeepEqual(src string) bool {

	if strings.Compare(p.StepId, src) != 0 {
		return false
	}
	return true
}
func (p *FlowResultRequest) Field2DeepEqual(src []*ConditionResult) bool {

	if len(p.ConditionResults) != len(src) {
		return false
	}
	for i, v := range p.ConditionResults {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FlowResultRequest) Field3DeepEqual(src []*Evidence) bool {

	if len(p.Evidence) != len(src) {
		return false
	}
	for i, v := range p.Evidence {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *FlowResultRequest) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Summary, src) != 0 {
		return false
	}
	return true
}
func (p *FlowResultRequest) Field6DeepEqual(src *RouteSelection) bool {

	if !p.Route.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowResultRequest = map[int16]string{
	1: "step_id",
	2: "condition_results",
	3: "evidence",
	4: "summary",
	6: "route",
}

type FlowResultResponse struct {
	Effect             ResultEffect `thrift:"effect,1,required,ResultEffect" json:"effect"`
	EventId            *string      `thrift:"event_id,2,optional" json:"event_id,omitempty"`
	Transition         *Transition  `thrift:"transition,3,required" json:"transition"`
	State              *FlowState   `thrift:"state,4,required" json:"state"`
	InvalidatedOutputs []string     `thrift:"invalidated_outputs,5,required,list<string>" json:"invalidated_outputs"`
}

func NewFlowResultResponse() *FlowResultResponse {
	return &FlowResultResponse{}
}

func (p *FlowResultResponse) InitDefault() {
}

func (p *FlowResultResponse) GetEffect() (v ResultEffect) {
	return p.Effect
}

var FlowResultResponse_EventId_DEFAULT string

func (p *FlowResultResponse) GetEventId() (v string) {
	if !p.IsSetEventId() {
		return FlowResultResponse_EventId_DEFAULT
	}
	return *p.EventId
}

var FlowResultResponse_Transition_DEFAULT *Transition

func (p *FlowResultResponse) GetTransition() (v *Transition) {
	if !p.IsSetTransition() {
		return FlowResultResponse_Transition_DEFAULT
	}
	return p.Transition
}

var FlowResultResponse_State_DEFAULT *FlowState

func (p *FlowResultResponse) GetState() (v *FlowState) {
	if !p.IsSetState() {
		return FlowResultResponse_State_DEFAULT
	}
	return p.State
}

func (p *FlowResultResponse) GetInvalidatedOutputs() (v []string) {
	return p.InvalidatedOutputs
}

func (p *FlowResultResponse) IsSetEventId() bool {
	return p.EventId != nil
}

func (p *FlowResultResponse) IsSetTransition() bool {
	return p.Transition != nil
}

func (p *FlowResultResponse) IsSetState() bool {
	return p.State != nil
}

func (p *FlowResultResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowResultResponse(%+v)", *p)
}

func (p *FlowResultResponse) DeepEqual(ano *FlowResultResponse) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Effect) {
		return false
	}
	if !p.Field2DeepEqual(ano.EventId) {
		return false
	}
	if !p.Field3DeepEqual(ano.Transition) {
		return false
	}
	if !p.Field4DeepEqual(ano.State) {
		return false
	}
	if !p.Field5DeepEqual(ano.InvalidatedOutputs) {
		return false
	}
	return true
}

func (p *FlowResultResponse) Field1DeepEqual(src ResultEffect) bool {

	if p.Effect != src {
		return false
	}
	return true
}
func (p *FlowResultResponse) Field2DeepEqual(src *string) bool {

	if p.EventId == src {
		return true
	} else if p.EventId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.EventId, *src) != 0 {
		return false
	}
	return true
}
func (p *FlowResultResponse) Field3DeepEqual(src *Transition) bool {

	if !p.Transition.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowResultResponse) Field4DeepEqual(src *FlowState) bool {

	if !p.State.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowResultResponse) Field5DeepEqual(src []string) bool {

	if len(p.InvalidatedOutputs) != len(src) {
		return false
	}
	for i, v := range p.InvalidatedOutputs {
		_src := src[i]
		if strings.Compare(v, _src) != 0 {
			return false
		}
	}
	return true
}

var fieldIDToName_FlowResultResponse = map[int16]string{
	1: "effect",
	2: "event_id",
	3: "transition",
	4: "state",
	5: "invalidated_outputs",
}

type RouteSelection struct {
	NextStepId *string `thrift:"next_step_id,1,optional" json:"next_step_id,omitempty"`
	BackStepId *string `thrift:"back_step_id,2,optional" json:"back_step_id,omitempty"`
	Terminal   *bool   `thrift:"terminal,3,optional" json:"terminal,omitempty"`
}

func NewRouteSelection() *RouteSelection {
	return &RouteSelection{}
}

func (p *RouteSelection) InitDefault() {
}

var RouteSelection_NextStepId_DEFAULT string

func (p *RouteSelection) GetNextStepId() (v string) {
	if !p.IsSetNextStepId() {
		return RouteSelection_NextStepId_DEFAULT
	}
	return *p.NextStepId
}

var RouteSelection_BackStepId_DEFAULT string

func (p *RouteSelection) GetBackStepId() (v string) {
	if !p.IsSetBackStepId() {
		return RouteSelection_BackStepId_DEFAULT
	}
	return *p.BackStepId
}

var RouteSelection_Terminal_DEFAULT bool

func (p *RouteSelection) GetTerminal() (v bool) {
	if !p.IsSetTerminal() {
		return RouteSelection_Terminal_DEFAULT
	}
	return *p.Terminal
}

func (p *RouteSelection) CountSetFieldsRouteSelection() int {
	count := 0
	if p.IsSetNextStepId() {
		count++
	}
	if p.IsSetBackStepId() {
		count++
	}
	if p.IsSetTerminal() {
		count++
	}
	return count
}

func (p *RouteSelection) IsSetNextStepId() bool {
	return p.NextStepId != nil
}

func (p *RouteSelection) IsSetBackStepId() bool {
	return p.BackStepId != nil
}

func (p *RouteSelection) IsSetTerminal() bool {
	return p.Terminal != nil
}

func (p *RouteSelection) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RouteSelection(%+v)", *p)
}

func (p *RouteSelection) DeepEqual(ano *RouteSelection) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.NextStepId) {
		return false
	}
	if !p.Field2DeepEqual(ano.BackStepId) {
		return false
	}
	if !p.Field3DeepEqual(ano.Terminal) {
		return false
	}
	return true
}

func (p *RouteSelection) Field1DeepEqual(src *string) bool {

	if p.NextStepId == src {
		return true
	} else if p.NextStepId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.NextStepId, *src) != 0 {
		return false
	}
	return true
}
func (p *RouteSelection) Field2DeepEqual(src *string) bool {

	if p.BackStepId == src {
		return true
	} else if p.BackStepId == nil || src == nil {
		return false
	}
	if strings.Compare(*p.BackStepId, *src) != 0 {
		return false
	}
	return true
}
func (p *RouteSelection) Field3DeepEqual(src *bool) bool {

	if p.Terminal == src {
		return true
	} else if p.Terminal == nil || src == nil {
		return false
	}
	if *p.Terminal != *src {
		return false
	}
	return true
}

var fieldIDToName_RouteSelection = map[int16]string{
	1: "next_step_id",
	2: "back_step_id",
	3: "terminal",
}

// One method maps to one public CLI command:
// Init     -> commonloop flow init
// Status   -> commonloop flow status
// Progress -> commonloop flow report progress
// Result   -> commonloop flow report result
type FlowService interface {
	Init(ctx context.Context, requirementRoot string, request *FlowInitRequest, dryRun bool) (r *FlowInitResponse, err error)

	Status(ctx context.Context, requirementRoot string, request *FlowStatusRequest) (r *FlowStatusResponse, err error)

	Progress(ctx context.Context, requirementRoot string, request *FlowProgressRequest, dryRun bool) (r *FlowProgressResponse, err error)

	Result(ctx context.Context, requirementRoot string, request *FlowResultRequest, dryRun bool) (r *FlowResultResponse, err error)
}

type FlowServiceInitArgs struct {
	RequirementRoot string           `thrift:"requirement_root,1,required" json:"requirement_root"`
	Request         *FlowInitRequest `thrift:"request,2,required" json:"request"`
	DryRun          bool             `thrift:"dry_run,3,required" json:"dry_run"`
}

func NewFlowServiceInitArgs() *FlowServiceInitArgs {
	return &FlowServiceInitArgs{}
}

func (p *FlowServiceInitArgs) InitDefault() {
}

func (p *FlowServiceInitArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var FlowServiceInitArgs_Request_DEFAULT *FlowInitRequest

func (p *FlowServiceInitArgs) GetRequest() (v *FlowInitRequest) {
	if !p.IsSetRequest() {
		return FlowServiceInitArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *FlowServiceInitArgs) GetDryRun() (v bool) {
	return p.DryRun
}

func (p *FlowServiceInitArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *FlowServiceInitArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowServiceInitArgs(%+v)", *p)
}

func (p *FlowServiceInitArgs) DeepEqual(ano *FlowServiceInitArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	if !p.Field3DeepEqual(ano.DryRun) {
		return false
	}
	return true
}

func (p *FlowServiceInitArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *FlowServiceInitArgs) Field2DeepEqual(src *FlowInitRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowServiceInitArgs) Field3DeepEqual(src bool) bool {

	if p.DryRun != src {
		return false
	}
	return true
}

var fieldIDToName_FlowServiceInitArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
	3: "dry_run",
}

type FlowServiceInitResult struct {
	Success *FlowInitResponse     `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewFlowServiceInitResult() *FlowServiceInitResult {
	return &FlowServiceInitResult{}
}

func (p *FlowServiceInitResult) InitDefault() {
}

var FlowServiceInitResult_Success_DEFAULT *FlowInitResponse

func (p *FlowServiceInitResult) GetSuccess() (v *FlowInitResponse) {
	if !p.IsSetSuccess() {
		return FlowServiceInitResult_Success_DEFAULT
	}
	return p.Success
}

var FlowServiceInitResult_Error_DEFAULT *erroridl.PublicError

func (p *FlowServiceInitResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return FlowServiceInitResult_Error_DEFAULT
	}
	return p.Error
}

func (p *FlowServiceInitResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FlowServiceInitResult) IsSetError() bool {
	return p.Error != nil
}

func (p *FlowServiceInitResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowServiceInitResult(%+v)", *p)
}

func (p *FlowServiceInitResult) DeepEqual(ano *FlowServiceInitResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *FlowServiceInitResult) Field0DeepEqual(src *FlowInitResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowServiceInitResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowServiceInitResult = map[int16]string{
	0: "success",
	1: "error",
}

type FlowServiceStatusArgs struct {
	RequirementRoot string             `thrift:"requirement_root,1,required" json:"requirement_root"`
	Request         *FlowStatusRequest `thrift:"request,2,required" json:"request"`
}

func NewFlowServiceStatusArgs() *FlowServiceStatusArgs {
	return &FlowServiceStatusArgs{}
}

func (p *FlowServiceStatusArgs) InitDefault() {
}

func (p *FlowServiceStatusArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var FlowServiceStatusArgs_Request_DEFAULT *FlowStatusRequest

func (p *FlowServiceStatusArgs) GetRequest() (v *FlowStatusRequest) {
	if !p.IsSetRequest() {
		return FlowServiceStatusArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *FlowServiceStatusArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *FlowServiceStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowServiceStatusArgs(%+v)", *p)
}

func (p *FlowServiceStatusArgs) DeepEqual(ano *FlowServiceStatusArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	return true
}

func (p *FlowServiceStatusArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *FlowServiceStatusArgs) Field2DeepEqual(src *FlowStatusRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowServiceStatusArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
}

type FlowServiceStatusResult struct {
	Success *FlowStatusResponse   `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewFlowServiceStatusResult() *FlowServiceStatusResult {
	return &FlowServiceStatusResult{}
}

func (p *FlowServiceStatusResult) InitDefault() {
}

var FlowServiceStatusResult_Success_DEFAULT *FlowStatusResponse

func (p *FlowServiceStatusResult) GetSuccess() (v *FlowStatusResponse) {
	if !p.IsSetSuccess() {
		return FlowServiceStatusResult_Success_DEFAULT
	}
	return p.Success
}

var FlowServiceStatusResult_Error_DEFAULT *erroridl.PublicError

func (p *FlowServiceStatusResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return FlowServiceStatusResult_Error_DEFAULT
	}
	return p.Error
}

func (p *FlowServiceStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FlowServiceStatusResult) IsSetError() bool {
	return p.Error != nil
}

func (p *FlowServiceStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowServiceStatusResult(%+v)", *p)
}

func (p *FlowServiceStatusResult) DeepEqual(ano *FlowServiceStatusResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *FlowServiceStatusResult) Field0DeepEqual(src *FlowStatusResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowServiceStatusResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowServiceStatusResult = map[int16]string{
	0: "success",
	1: "error",
}

type FlowServiceProgressArgs struct {
	RequirementRoot string               `thrift:"requirement_root,1,required" json:"requirement_root"`
	Request         *FlowProgressRequest `thrift:"request,2,required" json:"request"`
	DryRun          bool                 `thrift:"dry_run,3,required" json:"dry_run"`
}

func NewFlowServiceProgressArgs() *FlowServiceProgressArgs {
	return &FlowServiceProgressArgs{}
}

func (p *FlowServiceProgressArgs) InitDefault() {
}

func (p *FlowServiceProgressArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var FlowServiceProgressArgs_Request_DEFAULT *FlowProgressRequest

func (p *FlowServiceProgressArgs) GetRequest() (v *FlowProgressRequest) {
	if !p.IsSetRequest() {
		return FlowServiceProgressArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *FlowServiceProgressArgs) GetDryRun() (v bool) {
	return p.DryRun
}

func (p *FlowServiceProgressArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *FlowServiceProgressArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowServiceProgressArgs(%+v)", *p)
}

func (p *FlowServiceProgressArgs) DeepEqual(ano *FlowServiceProgressArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	if !p.Field3DeepEqual(ano.DryRun) {
		return false
	}
	return true
}

func (p *FlowServiceProgressArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *FlowServiceProgressArgs) Field2DeepEqual(src *FlowProgressRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowServiceProgressArgs) Field3DeepEqual(src bool) bool {

	if p.DryRun != src {
		return false
	}
	return true
}

var fieldIDToName_FlowServiceProgressArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
	3: "dry_run",
}

type FlowServiceProgressResult struct {
	Success *FlowProgressResponse `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewFlowServiceProgressResult() *FlowServiceProgressResult {
	return &FlowServiceProgressResult{}
}

func (p *FlowServiceProgressResult) InitDefault() {
}

var FlowServiceProgressResult_Success_DEFAULT *FlowProgressResponse

func (p *FlowServiceProgressResult) GetSuccess() (v *FlowProgressResponse) {
	if !p.IsSetSuccess() {
		return FlowServiceProgressResult_Success_DEFAULT
	}
	return p.Success
}

var FlowServiceProgressResult_Error_DEFAULT *erroridl.PublicError

func (p *FlowServiceProgressResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return FlowServiceProgressResult_Error_DEFAULT
	}
	return p.Error
}

func (p *FlowServiceProgressResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FlowServiceProgressResult) IsSetError() bool {
	return p.Error != nil
}

func (p *FlowServiceProgressResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowServiceProgressResult(%+v)", *p)
}

func (p *FlowServiceProgressResult) DeepEqual(ano *FlowServiceProgressResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *FlowServiceProgressResult) Field0DeepEqual(src *FlowProgressResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowServiceProgressResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowServiceProgressResult = map[int16]string{
	0: "success",
	1: "error",
}

type FlowServiceResultArgs struct {
	RequirementRoot string             `thrift:"requirement_root,1,required" json:"requirement_root"`
	Request         *FlowResultRequest `thrift:"request,2,required" json:"request"`
	DryRun          bool               `thrift:"dry_run,3,required" json:"dry_run"`
}

func NewFlowServiceResultArgs() *FlowServiceResultArgs {
	return &FlowServiceResultArgs{}
}

func (p *FlowServiceResultArgs) InitDefault() {
}

func (p *FlowServiceResultArgs) GetRequirementRoot() (v string) {
	return p.RequirementRoot
}

var FlowServiceResultArgs_Request_DEFAULT *FlowResultRequest

func (p *FlowServiceResultArgs) GetRequest() (v *FlowResultRequest) {
	if !p.IsSetRequest() {
		return FlowServiceResultArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *FlowServiceResultArgs) GetDryRun() (v bool) {
	return p.DryRun
}

func (p *FlowServiceResultArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *FlowServiceResultArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowServiceResultArgs(%+v)", *p)
}

func (p *FlowServiceResultArgs) DeepEqual(ano *FlowServiceResultArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.RequirementRoot) {
		return false
	}
	if !p.Field2DeepEqual(ano.Request) {
		return false
	}
	if !p.Field3DeepEqual(ano.DryRun) {
		return false
	}
	return true
}

func (p *FlowServiceResultArgs) Field1DeepEqual(src string) bool {

	if strings.Compare(p.RequirementRoot, src) != 0 {
		return false
	}
	return true
}
func (p *FlowServiceResultArgs) Field2DeepEqual(src *FlowResultRequest) bool {

	if !p.Request.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowServiceResultArgs) Field3DeepEqual(src bool) bool {

	if p.DryRun != src {
		return false
	}
	return true
}

var fieldIDToName_FlowServiceResultArgs = map[int16]string{
	1: "requirement_root",
	2: "request",
	3: "dry_run",
}

type FlowServiceResultResult struct {
	Success *FlowResultResponse   `thrift:"success,0,optional" json:"success,omitempty"`
	Error   *erroridl.PublicError `thrift:"error,1,optional" json:"error,omitempty"`
}

func NewFlowServiceResultResult() *FlowServiceResultResult {
	return &FlowServiceResultResult{}
}

func (p *FlowServiceResultResult) InitDefault() {
}

var FlowServiceResultResult_Success_DEFAULT *FlowResultResponse

func (p *FlowServiceResultResult) GetSuccess() (v *FlowResultResponse) {
	if !p.IsSetSuccess() {
		return FlowServiceResultResult_Success_DEFAULT
	}
	return p.Success
}

var FlowServiceResultResult_Error_DEFAULT *erroridl.PublicError

func (p *FlowServiceResultResult) GetError() (v *erroridl.PublicError) {
	if !p.IsSetError() {
		return FlowServiceResultResult_Error_DEFAULT
	}
	return p.Error
}

func (p *FlowServiceResultResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FlowServiceResultResult) IsSetError() bool {
	return p.Error != nil
}

func (p *FlowServiceResultResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FlowServiceResultResult(%+v)", *p)
}

func (p *FlowServiceResultResult) DeepEqual(ano *FlowServiceResultResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	if !p.Field1DeepEqual(ano.Error) {
		return false
	}
	return true
}

func (p *FlowServiceResultResult) Field0DeepEqual(src *FlowResultResponse) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
func (p *FlowServiceResultResult) Field1DeepEqual(src *erroridl.PublicError) bool {

	if !p.Error.DeepEqual(src) {
		return false
	}
	return true
}

var fieldIDToName_FlowServiceResultResult = map[int16]string{
	0: "success",
	1: "error",
}

// exceptions of methods in FlowService.
var (
	_ error = (*erroridl.PublicError)(nil)
)
