// Code generated by Validator v0.2.5. DO NOT EDIT.

package flowidl

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *Requirement) IsValid() error {
	if len(p.Title) < int(1) {
		return fmt.Errorf("field Title min_len rule failed, current value: %d", len(p.Title))
	}
	return nil
}
func (p *Evidence) IsValid() error {
	if p.Source.String() == "<UNSET>" {
		return fmt.Errorf("field Source defined_only rule failed")
	}
	_src := []EvidenceSource{EvidenceSource_unspecified}
	for _, src := range _src {
		if p.Source == src {
			return fmt.Errorf("field Source not_in rule failed, current value: %v", p.Source)
		}
	}
	if len(p.Content) < int(1) {
		return fmt.Errorf("field Content min_len rule failed, current value: %d", len(p.Content))
	}
	return nil
}
func (p *OutputValue) IsValid() error {
	if p.Type.String() == "<UNSET>" {
		return fmt.Errorf("field Type defined_only rule failed")
	}
	_src := []OutputType{OutputType_unspecified}
	for _, src := range _src {
		if p.Type == src {
			return fmt.Errorf("field Type not_in rule failed, current value: %v", p.Type)
		}
	}
	if p.Value == nil {
		return fmt.Errorf("field Value not_nil rule failed")
	}
	if err := p.Value.IsValid(); err != nil {
		return fmt.Errorf("field Value not valid, %w", err)
	}
	return nil
}
func (p *OutputSpec) IsValid() error {
	if len(p.Key) < int(1) {
		return fmt.Errorf("field Key min_len rule failed, current value: %d", len(p.Key))
	}
	if p.Type.String() == "<UNSET>" {
		return fmt.Errorf("field Type defined_only rule failed")
	}
	_src := []OutputType{OutputType_unspecified}
	for _, src := range _src {
		if p.Type == src {
			return fmt.Errorf("field Type not_in rule failed, current value: %v", p.Type)
		}
	}
	return nil
}
func (p *RegisteredOutput) IsValid() error {
	if p.Type.String() == "<UNSET>" {
		return fmt.Errorf("field Type defined_only rule failed")
	}
	_src := []OutputType{OutputType_unspecified}
	for _, src := range _src {
		if p.Type == src {
			return fmt.Errorf("field Type not_in rule failed, current value: %v", p.Type)
		}
	}
	if p.Value == nil {
		return fmt.Errorf("field Value not_nil rule failed")
	}
	if err := p.Value.IsValid(); err != nil {
		return fmt.Errorf("field Value not valid, %w", err)
	}
	if len(p.ProducerStepId) < int(1) {
		return fmt.Errorf("field ProducerStepId min_len rule failed, current value: %d", len(p.ProducerStepId))
	}
	return nil
}
func (p *CurrentContext) IsValid() error {
	if len(p.StageId) < int(1) {
		return fmt.Errorf("field StageId min_len rule failed, current value: %d", len(p.StageId))
	}
	if len(p.StageName) < int(1) {
		return fmt.Errorf("field StageName min_len rule failed, current value: %d", len(p.StageName))
	}
	if len(p.JobId) < int(1) {
		return fmt.Errorf("field JobId min_len rule failed, current value: %d", len(p.JobId))
	}
	if len(p.JobName) < int(1) {
		return fmt.Errorf("field JobName min_len rule failed, current value: %d", len(p.JobName))
	}
	if len(p.StepId) < int(1) {
		return fmt.Errorf("field StepId min_len rule failed, current value: %d", len(p.StepId))
	}
	if len(p.StepName) < int(1) {
		return fmt.Errorf("field StepName min_len rule failed, current value: %d", len(p.StepName))
	}
	if p.Executor.String() == "<UNSET>" {
		return fmt.Errorf("field Executor defined_only rule failed")
	}
	_src := []Executor{Executor_unspecified}
	for _, src := range _src {
		if p.Executor == src {
			return fmt.Errorf("field Executor not_in rule failed, current value: %v", p.Executor)
		}
	}
	return nil
}
func (p *Execution) IsValid() error {
	if p.Status.String() == "<UNSET>" {
		return fmt.Errorf("field Status defined_only rule failed")
	}
	_src := []StepStatus{StepStatus_unspecified}
	for _, src := range _src {
		if p.Status == src {
			return fmt.Errorf("field Status not_in rule failed, current value: %v", p.Status)
		}
	}
	return nil
}
func (p *Skill) IsValid() error {
	if len(p.Id) < int(1) {
		return fmt.Errorf("field Id min_len rule failed, current value: %d", len(p.Id))
	}
	if len(p.Prompt) < int(1) {
		return fmt.Errorf("field Prompt min_len rule failed, current value: %d", len(p.Prompt))
	}
	if len(p.Path) < int(1) {
		return fmt.Errorf("field Path min_len rule failed, current value: %d", len(p.Path))
	}
	return nil
}
func (p *Prompt) IsValid() error {
	if len(p.Content) < int(1) {
		return fmt.Errorf("field Content min_len rule failed, current value: %d", len(p.Content))
	}
	return nil
}
func (p *ConditionView) IsValid() error {
	if len(p.Id) < int(1) {
		return fmt.Errorf("field Id min_len rule failed, current value: %d", len(p.Id))
	}
	if p.Prompt == nil {
		return fmt.Errorf("field Prompt not_nil rule failed")
	}
	if err := p.Prompt.IsValid(); err != nil {
		return fmt.Errorf("field Prompt not valid, %w", err)
	}
	if p.Output == nil {
		return fmt.Errorf("field Output not_nil rule failed")
	}
	if err := p.Output.IsValid(); err != nil {
		return fmt.Errorf("field Output not valid, %w", err)
	}
	return nil
}
func (p *RouteWhen) IsValid() error {
	if len(p.AnyOf) < int(1) {
		return fmt.Errorf("field AnyOf MinLen rule failed, current value: %v", p.AnyOf)
	}
	return nil
}
func (p *AvailableRoute) IsValid() error {
	if p.Direction.String() == "<UNSET>" {
		return fmt.Errorf("field Direction defined_only rule failed")
	}
	_src := []RouteDirection{RouteDirection_unspecified}
	for _, src := range _src {
		if p.Direction == src {
			return fmt.Errorf("field Direction not_in rule failed, current value: %v", p.Direction)
		}
	}
	if p.When == nil {
		return fmt.Errorf("field When not_nil rule failed")
	}
	if err := p.When.IsValid(); err != nil {
		return fmt.Errorf("field When not valid, %w", err)
	}
	if p.Route == nil {
		return fmt.Errorf("field Route not_nil rule failed")
	}
	if err := p.Route.IsValid(); err != nil {
		return fmt.Errorf("field Route not valid, %w", err)
	}
	if p.Prompt == nil {
		return fmt.Errorf("field Prompt not_nil rule failed")
	}
	if err := p.Prompt.IsValid(); err != nil {
		return fmt.Errorf("field Prompt not valid, %w", err)
	}
	return nil
}
func (p *CurrentTask) IsValid() error {
	if p.Context == nil {
		return fmt.Errorf("field Context not_nil rule failed")
	}
	if err := p.Context.IsValid(); err != nil {
		return fmt.Errorf("field Context not valid, %w", err)
	}
	if p.Execution == nil {
		return fmt.Errorf("field Execution not_nil rule failed")
	}
	if err := p.Execution.IsValid(); err != nil {
		return fmt.Errorf("field Execution not valid, %w", err)
	}
	if p.Prompt == nil {
		return fmt.Errorf("field Prompt not_nil rule failed")
	}
	if err := p.Prompt.IsValid(); err != nil {
		return fmt.Errorf("field Prompt not valid, %w", err)
	}
	return nil
}
func (p *FlowState) IsValid() error {
	if p.Status.String() == "<UNSET>" {
		return fmt.Errorf("field Status defined_only rule failed")
	}
	_src := []WorkflowStatus{WorkflowStatus_unspecified}
	for _, src := range _src {
		if p.Status == src {
			return fmt.Errorf("field Status not_in rule failed, current value: %v", p.Status)
		}
	}
	if p.Current != nil {
		if err := p.Current.IsValid(); err != nil {
			return fmt.Errorf("field Current not valid, %w", err)
		}
	}
	return nil
}
func (p *FlowInitRequest) IsValid() error {
	if len(p.Workflow) < int(1) {
		return fmt.Errorf("field Workflow min_len rule failed, current value: %d", len(p.Workflow))
	}
	if p.Requirement == nil {
		return fmt.Errorf("field Requirement not_nil rule failed")
	}
	if err := p.Requirement.IsValid(); err != nil {
		return fmt.Errorf("field Requirement not valid, %w", err)
	}
	return nil
}
func (p *FlowInitResponse) IsValid() error {
	if p.Effect.String() == "<UNSET>" {
		return fmt.Errorf("field Effect defined_only rule failed")
	}
	_src := []InitEffect{InitEffect_unspecified}
	for _, src := range _src {
		if p.Effect == src {
			return fmt.Errorf("field Effect not_in rule failed, current value: %v", p.Effect)
		}
	}
	if p.Workflow == nil {
		return fmt.Errorf("field Workflow not_nil rule failed")
	}
	if err := p.Workflow.IsValid(); err != nil {
		return fmt.Errorf("field Workflow not valid, %w", err)
	}
	if p.State == nil {
		return fmt.Errorf("field State not_nil rule failed")
	}
	if err := p.State.IsValid(); err != nil {
		return fmt.Errorf("field State not valid, %w", err)
	}
	return nil
}
func (p *FlowStatusRequest) IsValid() error {
	return nil
}
func (p *FlowStatusResponse) IsValid() error {
	if p.Requirement == nil {
		return fmt.Errorf("field Requirement not_nil rule failed")
	}
	if err := p.Requirement.IsValid(); err != nil {
		return fmt.Errorf("field Requirement not valid, %w", err)
	}
	if p.Workflow == nil {
		return fmt.Errorf("field Workflow not_nil rule failed")
	}
	if err := p.Workflow.IsValid(); err != nil {
		return fmt.Errorf("field Workflow not valid, %w", err)
	}
	if p.State == nil {
		return fmt.Errorf("field State not_nil rule failed")
	}
	if err := p.State.IsValid(); err != nil {
		return fmt.Errorf("field State not valid, %w", err)
	}
	return nil
}
func (p *FlowProgressRequest) IsValid() error {
	if len(p.StepId) < int(1) {
		return fmt.Errorf("field StepId min_len rule failed, current value: %d", len(p.StepId))
	}
	if p.Status.String() == "<UNSET>" {
		return fmt.Errorf("field Status defined_only rule failed")
	}
	_src := []ProgressStatus{ProgressStatus_unspecified}
	for _, src := range _src {
		if p.Status == src {
			return fmt.Errorf("field Status not_in rule failed, current value: %v", p.Status)
		}
	}
	if len(p.Summary) < int(1) {
		return fmt.Errorf("field Summary min_len rule failed, current value: %d", len(p.Summary))
	}
	return nil
}
func (p *FlowProgressResponse) IsValid() error {
	if p.Effect.String() == "<UNSET>" {
		return fmt.Errorf("field Effect defined_only rule failed")
	}
	_src := []ProgressEffect{ProgressEffect_unspecified}
	for _, src := range _src {
		if p.Effect == src {
			return fmt.Errorf("field Effect not_in rule failed, current value: %v", p.Effect)
		}
	}
	if p.State == nil {
		return fmt.Errorf("field State not_nil rule failed")
	}
	if err := p.State.IsValid(); err != nil {
		return fmt.Errorf("field State not valid, %w", err)
	}
	return nil
}
func (p *ConditionResult) IsValid() error {
	if len(p.ConditionId) < int(1) {
		return fmt.Errorf("field ConditionId min_len rule failed, current value: %d", len(p.ConditionId))
	}
	if p.Output == nil {
		return fmt.Errorf("field Output not_nil rule failed")
	}
	if err := p.Output.IsValid(); err != nil {
		return fmt.Errorf("field Output not valid, %w", err)
	}
	return nil
}
func (p *Transition) IsValid() error {
	if p.Direction.String() == "<UNSET>" {
		return fmt.Errorf("field Direction defined_only rule failed")
	}
	_src := []TransitionDirection{TransitionDirection_unspecified}
	for _, src := range _src {
		if p.Direction == src {
			return fmt.Errorf("field Direction not_in rule failed, current value: %v", p.Direction)
		}
	}
	if len(p.FromStepId) < int(1) {
		return fmt.Errorf("field FromStepId min_len rule failed, current value: %d", len(p.FromStepId))
	}
	return nil
}
func (p *FlowResultRequest) IsValid() error {
	if len(p.StepId) < int(1) {
		return fmt.Errorf("field StepId min_len rule failed, current value: %d", len(p.StepId))
	}
	if len(p.ConditionResults) < int(1) {
		return fmt.Errorf("field ConditionResults MinLen rule failed, current value: %v", p.ConditionResults)
	}
	if len(p.Summary) < int(1) {
		return fmt.Errorf("field Summary min_len rule failed, current value: %d", len(p.Summary))
	}
	if p.Route == nil {
		return fmt.Errorf("field Route not_nil rule failed")
	}
	if err := p.Route.IsValid(); err != nil {
		return fmt.Errorf("field Route not valid, %w", err)
	}
	return nil
}
func (p *FlowResultResponse) IsValid() error {
	if p.Effect.String() == "<UNSET>" {
		return fmt.Errorf("field Effect defined_only rule failed")
	}
	_src := []ResultEffect{ResultEffect_unspecified}
	for _, src := range _src {
		if p.Effect == src {
			return fmt.Errorf("field Effect not_in rule failed, current value: %v", p.Effect)
		}
	}
	if p.Transition == nil {
		return fmt.Errorf("field Transition not_nil rule failed")
	}
	if err := p.Transition.IsValid(); err != nil {
		return fmt.Errorf("field Transition not valid, %w", err)
	}
	if p.State == nil {
		return fmt.Errorf("field State not_nil rule failed")
	}
	if err := p.State.IsValid(); err != nil {
		return fmt.Errorf("field State not valid, %w", err)
	}
	return nil
}
func (p *RouteSelection) IsValid() error {
	if p.NextStepId != nil {
		if len(*p.NextStepId) < int(1) {
			return fmt.Errorf("field NextStepId min_len rule failed, current value: %d", len(*p.NextStepId))
		}
	}
	if p.BackStepId != nil {
		if len(*p.BackStepId) < int(1) {
			return fmt.Errorf("field BackStepId min_len rule failed, current value: %d", len(*p.BackStepId))
		}
	}
	return nil
}
